// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.tax;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link TaxClient#getOrganizationInfo}, XYP operation {@code
 * WS100624_getOrganizationInfo}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GetOrganizationInfoParams implements RequestParams {
  private final String companyRegnum;
  private final String usage;
  private final String forUsage;
  private final Long year;

  private GetOrganizationInfoParams(Builder builder) {
    this.companyRegnum = builder.companyRegnum;
    this.usage = builder.usage;
    this.forUsage = builder.forUsage;
    this.year = builder.year;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Байгууллагын регистрийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String companyRegnum() {
    return companyRegnum;
  }

  /**
   * Зориулалт.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String usage() {
    return usage;
  }

  /**
   * Хаана зориулж.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String forUsage() {
    return forUsage;
  }

  /**
   * жил.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long year() {
    return year;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("companyRegnum", companyRegnum)
        .add("usage", usage)
        .add("forUsage", forUsage)
        .add("year", year)
        .build();
  }

  /**
   * Builds a {@link GetOrganizationInfoParams}. Every setter accepts {@code null}, which leaves the
   * field out of the request. A builder is not thread-safe; it can be reused, and setting a field
   * again does not change the params it has already built.
   */
  public static final class Builder {
    private String companyRegnum;
    private String usage;
    private String forUsage;
    private Long year;

    private Builder() {}

    /**
     * Байгууллагын регистрийн дугаар.
     *
     * @param companyRegnum the value, or {@code null}
     * @return this builder
     */
    public Builder companyRegnum(String companyRegnum) {
      this.companyRegnum = companyRegnum;
      return this;
    }

    /**
     * Зориулалт.
     *
     * @param usage the value, or {@code null}
     * @return this builder
     */
    public Builder usage(String usage) {
      this.usage = usage;
      return this;
    }

    /**
     * Хаана зориулж.
     *
     * @param forUsage the value, or {@code null}
     * @return this builder
     */
    public Builder forUsage(String forUsage) {
      this.forUsage = forUsage;
      return this;
    }

    /**
     * жил.
     *
     * @param year the value, or {@code null}
     * @return this builder
     */
    public Builder year(Long year) {
      this.year = year;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GetOrganizationInfoParams}
     */
    public GetOrganizationInfoParams build() {
      return new GetOrganizationInfoParams(this);
    }
  }
}
