// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.property;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100253_getPropertyInfoCertificate}: Үл хөдлөхийн гэрчилгээний хуулбар
 * харах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param list Жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record GetPropertyInfoCertificateResponse(List<Object> list, Extras extras) {

  static GetPropertyInfoCertificateResponse decode(ResponseReader reader) {
    return new GetPropertyInfoCertificateResponse(
        reader.get("list", Decoders.list(Decoders.ANY)), reader.extras());
  }
}
