// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.property;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link PropertyClient#landInfoByPersonIdAndParcelId}, XYP operation {@code
 * WS100240_landInfoByPersonIdAndParcelId}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class LandInfoByPersonIdAndParcelIdParams implements RequestParams {
  private final String personId;
  private final String parcelId;

  private LandInfoByPersonIdAndParcelIdParams(Builder builder) {
    this.personId = builder.personId;
    this.parcelId = builder.parcelId;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Хэрэглэгчийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String personId() {
    return personId;
  }

  /**
   * Нэгж талбарын дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String parcelId() {
    return parcelId;
  }

  @Override
  public Params toParams() {
    return Params.builder().add("personId", personId).add("parcelId", parcelId).build();
  }

  /**
   * Builds a {@link LandInfoByPersonIdAndParcelIdParams}. Every setter accepts {@code null}, which
   * leaves the field out of the request. A builder is not thread-safe; it can be reused, and
   * setting a field again does not change the params it has already built.
   */
  public static final class Builder {
    private String personId;
    private String parcelId;

    private Builder() {}

    /**
     * Хэрэглэгчийн дугаар.
     *
     * @param personId the value, or {@code null}
     * @return this builder
     */
    public Builder personId(String personId) {
      this.personId = personId;
      return this;
    }

    /**
     * Нэгж талбарын дугаар.
     *
     * @param parcelId the value, or {@code null}
     * @return this builder
     */
    public Builder parcelId(String parcelId) {
      this.parcelId = parcelId;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link LandInfoByPersonIdAndParcelIdParams}
     */
    public LandInfoByPersonIdAndParcelIdParams build() {
      return new LandInfoByPersonIdAndParcelIdParams(this);
    }
  }
}
