/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * GS10089_EnergyQualificationCertificateService (governmentService, Эрчим хүчний яам)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "GS10089_EnergyQualificationCertificateService";

/** Input of GS10089_EnergyQualificationCertificateService. */
export interface EnergyQualificationCertificateServiceParams {
  /** Сертификатын id (GS10088_EnergyQualificationService сервисийн listData-аас авна) */
  readonly id?: string;
}

/** GS10089_EnergyQualificationCertificateService: Эрчим хүчний салбарын мэргэшлийн зэрэг эзэмшигчийн сертификатын мэдээлэл id-аар лавлах */
export interface EnergyQualificationCertificateServiceResponse {
  /** Овог */
  readonly lastName: string | null;
  /** Нэр */
  readonly firstName: string | null;
  /** Сертификатын id */
  readonly id: string | null;
  /** Тушаалын дугаар */
  readonly decisionNum: string | null;
  /** Тушаалын огноо */
  readonly decisionDate: string | null;
  /** Гэрчилгээний дугаар */
  readonly certificateNum: string | null;
  /** Мэргэжлийн код */
  readonly professionCode: string | null;
  /** Мэргэшлийн зэргийн нэр */
  readonly certificateName: string | null;
  /** Тушаалын огнооноос хүчинтэй байх жил (0 бол хугацаагүй сунгасан) */
  readonly validYear: string | null;
  /** Мэргэжлийн нэр */
  readonly professionDesc: string | null;
  /** Сертификатын дуусах огноо (Хоосон бол хугацаагүй сунгасан буюу үргэлж хүчинтэй байна) */
  readonly expireDate: string | null;
  /** Төлөв: "Хүчинтэй" / "Хүчингүй" */
  readonly certificateStatus: string | null;
}

const SCHEMA: Schema = { lastName: "string", firstName: "string", id: "string", decisionNum: "string", decisionDate: "string", certificateNum: "string", professionCode: "string", certificateName: "string", validYear: "string", professionDesc: "string", expireDate: "string", certificateStatus: "string" };

/**
 * GS10089_EnergyQualificationCertificateService: Эрчим хүчний салбарын мэргэшлийн зэрэг эзэмшигчийн сертификатын мэдээлэл id-аар лавлах
 *
 * Provider: Эрчим хүчний яам
 */
export async function energyQualificationCertificateService(transport: Transport, params: EnergyQualificationCertificateServiceParams = {}, options: CallOptions = {}): Promise<XypResult<EnergyQualificationCertificateServiceResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      id: params.id,
    },
    options,
  );
  return decodeResponse<EnergyQualificationCertificateServiceResponse>("EnergyQualificationCertificateServiceResponse", SCHEMA, data);
}
