/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * GS10086_RiskRegistrationService (governmentService, И-Монголиа академи)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "GS10086_RiskRegistrationService";

/** Input of GS10086_RiskRegistrationService. */
export interface RiskRegistrationServiceParams {
  readonly ctpid?: string;
  readonly sttpid?: string;
  /** эрсдэлийн тайлбар */
  readonly desc?: string;
  readonly tpid?: string;
  readonly envpid?: string;
  readonly systempid?: string;
  readonly orgregnum?: string;
  readonly orgname?: string;
  readonly imgurl?: string;
  readonly videourl?: string;
  readonly lt?: number;
  readonly ln?: number;
  readonly civilid?: string;
}

/** GS10086_RiskRegistrationService: Эрсдэл бүртгэх нэгдсэн үйлдэл */
export interface RiskRegistrationServiceResponse {
  readonly risk: unknown | null;
  readonly rschlog: unknown | null;
  readonly org: unknown | null;
  readonly orgCreated: boolean | null;
}

const SCHEMA: Schema = { risk: "any", rschlog: "any", org: "any", orgCreated: "bool" };

/**
 * GS10086_RiskRegistrationService: Эрсдэл бүртгэх нэгдсэн үйлдэл
 *
 * Provider: И-Монголиа академи
 */
export async function riskRegistrationService(transport: Transport, params: RiskRegistrationServiceParams = {}, options: CallOptions = {}): Promise<XypResult<RiskRegistrationServiceResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      ctpid: params.ctpid,
      sttpid: params.sttpid,
      desc: params.desc,
      tpid: params.tpid,
      envpid: params.envpid,
      systempid: params.systempid,
      orgregnum: params.orgregnum,
      orgname: params.orgname,
      imgurl: params.imgurl,
      videourl: params.videourl,
      lt: params.lt,
      ln: params.ln,
      civilid: params.civilid,
    },
    options,
  );
  return decodeResponse<RiskRegistrationServiceResponse>("RiskRegistrationServiceResponse", SCHEMA, data);
}
