"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100101_getCitizenIDCardInfo (citizen, Улсын бүртгэлийн ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Base64Bytes, Field

from xyp._models import XypDate, XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100101_getCitizenIDCardInfo"


class GetCitizenIdCardInfoListAddress(XypModel):
    """Хаягын жагсаалт"""

    aimag_city_name: str | None = Field(
        default=None, alias="aimagCityName", description="Аймгийн нэр"
    )
    soum_district_name: str | None = Field(
        default=None, alias="soumDistrictName", description="Сумын нэр"
    )
    bag_khoroo_name: str | None = Field(
        default=None, alias="bagKhorooName", description="Багын нэр"
    )
    address_region_name: str | None = Field(
        default=None, alias="addressRegionName", description="Хороололын нэр"
    )
    address_town_name: str | None = Field(
        default=None, alias="addressTownName", description="Хотхон"
    )
    address_street_name: str | None = Field(
        default=None, alias="addressStreetName", description="Гудамж"
    )
    address_apartment_name: str | None = Field(
        default=None, alias="addressApartmentName", description="Байр"
    )
    address_door: str | None = Field(default=None, alias="addressDoor", description="Тоот")
    register_date: XypDate | None = Field(
        default=None, alias="registerDate", description="Бүртгэлийн огноо"
    )


class GetCitizenIdCardInfoResponse(XypModel):
    """WS100101_getCitizenIDCardInfo: Иргэний үнэмлэхний мэдээлэл дамжуулах сервис"""

    passport_num: str | None = Field(
        default=None, alias="passportNum", description="Гадаад пасспортын дугаар"
    )
    list_address: list[GetCitizenIdCardInfoListAddress] | None = Field(
        default=None, alias="listAddress", description="Хаягын жагсаалт"
    )
    pass_time: str | None = Field(default=None, alias="passTime", description="Хэддэх удаагаа")
    passport_date: XypDate | None = Field(
        default=None, alias="passportDate", description="Гадаад пасспортын огноо"
    )
    regnum: str | None = Field(default=None, alias="regnum", description="Регистрийн дугаар")
    civil_id: str | None = Field(default=None, alias="civilId", description="Иргэний хувийн дугаар")
    firstname: str | None = Field(default=None, alias="firstname", description="Нэр")
    lastname: str | None = Field(default=None, alias="lastname", description="Овог")
    surname: str | None = Field(default=None, alias="surname", description="Ургийн овог")
    image: Base64Bytes | None = Field(default=None, alias="image", description="Зураг")
    nationality: str | None = Field(default=None, alias="nationality", description="Үндэс")
    gender: str | None = Field(default=None, alias="gender", description="Хүйс")
    birth_date: XypDate | None = Field(default=None, alias="birthDate", description="Төрсөн өдөр")
    birth_date_as_text: str | None = Field(
        default=None, alias="birthDateAsText", description="Төрсөн өдөр"
    )
    birth_place: str | None = Field(default=None, alias="birthPlace", description="Төрсөн газар")
    passport_issue_date: str | None = Field(
        default=None, alias="passportIssueDate", description="Үнэмлэх олгосон өдөр"
    )
    passport_expire_date: str | None = Field(
        default=None, alias="passportExpireDate", description="Үнэмлэх хүчинтэй хугацаа"
    )
    passport_address: str | None = Field(
        default=None, alias="passportAddress", description="Иргэний үнэмлэх дээрх хаяг"
    )
    aimag_city_code: str | None = Field(
        default=None, alias="aimagCityCode", description="Аймаг, хотын код"
    )
    aimag_city_name: str | None = Field(
        default=None, alias="aimagCityName", description="Аймаг, хотын нэр"
    )
    soum_district_code: str | None = Field(
        default=None, alias="soumDistrictCode", description="Сум, дүүрэгийн код"
    )
    soum_district_name: str | None = Field(
        default=None, alias="soumDistrictName", description="Сум, дүүрэгийн нэр"
    )
    bag_khoroo_code: str | None = Field(
        default=None, alias="bagKhorooCode", description="Баг, хорооны нэр"
    )
    bag_khoroo_name: str | None = Field(
        default=None, alias="bagKhorooName", description="Баг, хорооны нэр"
    )
    address_region_name: str | None = Field(
        default=None, alias="addressRegionName", description="Хорооллын нэр"
    )
    address_street_name: str | None = Field(
        default=None, alias="addressStreetName", description="Гудамжны нэр"
    )
    address_town_name: str | None = Field(
        default=None, alias="addressTownName", description="Хотхоны нэр"
    )
    address_apartment_name: str | None = Field(
        default=None, alias="addressApartmentName", description="Байрны нэр"
    )
    address_detail: str | None = Field(
        default=None, alias="addressDetail", description="Хаяг дэлгэрэнгүй"
    )
    person_id: str | None = Field(default=None, alias="personId", description="Иргэний дугаар")


def get_citizen_id_card_info(
    self: SyncService,
    *,
    civil_id: str | None = None,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetCitizenIdCardInfoResponse:
    """WS100101_getCitizenIDCardInfo: Иргэний үнэмлэхний мэдээлэл дамжуулах сервис

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        civil_id: Иргэний хувийн дугаар
        regnum: регистрийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "civilId": civil_id,
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetCitizenIdCardInfoResponse, data)


async def get_citizen_id_card_info_async(
    self: AsyncService,
    *,
    civil_id: str | None = None,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetCitizenIdCardInfoResponse:
    """WS100101_getCitizenIDCardInfo: Иргэний үнэмлэхний мэдээлэл дамжуулах сервис

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        civil_id: Иргэний хувийн дугаар
        regnum: регистрийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "civilId": civil_id,
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetCitizenIdCardInfoResponse, data)
