// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.citizen;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link CitizenClient#deceaseListByDate}, XYP operation {@code
 * WS101133_deceaseListByDate}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class DeceaseListByDateParams implements RequestParams {
  private final String orgCode;
  private final String orgName;
  private final String orgPassword;
  private final String orgToken;
  private final String serviceCode;
  private final String endDate;
  private final String startDate;

  private DeceaseListByDateParams(Builder builder) {
    this.orgCode = builder.orgCode;
    this.orgName = builder.orgName;
    this.orgPassword = builder.orgPassword;
    this.orgToken = builder.orgToken;
    this.serviceCode = builder.serviceCode;
    this.endDate = builder.endDate;
    this.startDate = builder.startDate;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Байгууллагын код.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgCode() {
    return orgCode;
  }

  /**
   * Байгууллагын нэр.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgName() {
    return orgName;
  }

  /**
   * Нууц үг.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgPassword() {
    return orgPassword;
  }

  /**
   * Токен.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgToken() {
    return orgToken;
  }

  /**
   * Сервисын нэр.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String serviceCode() {
    return serviceCode;
  }

  /**
   * Дуусах огноо YYYY-MM-DD.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String endDate() {
    return endDate;
  }

  /**
   * Эхлэх огноо YYYY-MM-DD.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String startDate() {
    return startDate;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("orgCode", orgCode)
        .add("orgName", orgName)
        .add("orgPassword", orgPassword)
        .add("orgToken", orgToken)
        .add("serviceCode", serviceCode)
        .add("endDate", endDate)
        .add("startDate", startDate)
        .build();
  }

  /**
   * Builds a {@link DeceaseListByDateParams}. Every setter accepts {@code null}, which leaves the
   * field out of the request. A builder is not thread-safe; it can be reused, and setting a field
   * again does not change the params it has already built.
   */
  public static final class Builder {
    private String orgCode;
    private String orgName;
    private String orgPassword;
    private String orgToken;
    private String serviceCode;
    private String endDate;
    private String startDate;

    private Builder() {}

    /**
     * Байгууллагын код.
     *
     * @param orgCode the value, or {@code null}
     * @return this builder
     */
    public Builder orgCode(String orgCode) {
      this.orgCode = orgCode;
      return this;
    }

    /**
     * Байгууллагын нэр.
     *
     * @param orgName the value, or {@code null}
     * @return this builder
     */
    public Builder orgName(String orgName) {
      this.orgName = orgName;
      return this;
    }

    /**
     * Нууц үг.
     *
     * @param orgPassword the value, or {@code null}
     * @return this builder
     */
    public Builder orgPassword(String orgPassword) {
      this.orgPassword = orgPassword;
      return this;
    }

    /**
     * Токен.
     *
     * @param orgToken the value, or {@code null}
     * @return this builder
     */
    public Builder orgToken(String orgToken) {
      this.orgToken = orgToken;
      return this;
    }

    /**
     * Сервисын нэр.
     *
     * @param serviceCode the value, or {@code null}
     * @return this builder
     */
    public Builder serviceCode(String serviceCode) {
      this.serviceCode = serviceCode;
      return this;
    }

    /**
     * Дуусах огноо YYYY-MM-DD.
     *
     * @param endDate the value, or {@code null}
     * @return this builder
     */
    public Builder endDate(String endDate) {
      this.endDate = endDate;
      return this;
    }

    /**
     * Эхлэх огноо YYYY-MM-DD.
     *
     * @param startDate the value, or {@code null}
     * @return this builder
     */
    public Builder startDate(String startDate) {
      this.startDate = startDate;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link DeceaseListByDateParams}
     */
    public DeceaseListByDateParams build() {
      return new DeceaseListByDateParams(this);
    }
  }
}
