// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.citizen;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS101159_GetDissolvedLegalEntityInfo}: Татан буугдсан хуулийн этгээдийн
 * лавлагааны сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param companyName Оноосон нэр
 * @param orgRegnum Хуулийн этгээдийн регистрийн дугаар
 * @param createdDate Бүртгэсэн огноо
 * @param companyTypeName the {@code companyTypeName} field
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record GetDissolvedLegalEntityInfoResponse(
    String companyName,
    String orgRegnum,
    String createdDate,
    String companyTypeName,
    Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static GetDissolvedLegalEntityInfoResponse decode(ResponseReader reader) {
    return new GetDissolvedLegalEntityInfoResponse(
        reader.get("companyName", Decoders.STRING),
        reader.get("orgRegnum", Decoders.STRING),
        reader.get("createdDate", Decoders.STRING),
        reader.get("companyTypeName", Decoders.STRING),
        reader.extras());
  }
}
