// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.citizen;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link CitizenClient#graduatedVocationalStudentInfo}, XYP operation {@code
 * WS101183_GraduatedVocationalStudentInfo}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GraduatedVocationalStudentInfoParams implements RequestParams {
  private final String regnum;
  private final String civilId;
  private final String name;

  private GraduatedVocationalStudentInfoParams(Builder builder) {
    this.regnum = builder.regnum;
    this.civilId = builder.civilId;
    this.name = builder.name;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Регистрийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String regnum() {
    return regnum;
  }

  /**
   * Иргэний ID.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String civilId() {
    return civilId;
  }

  /**
   * Нэр.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String name() {
    return name;
  }

  @Override
  public Params toParams() {
    return Params.builder().add("regnum", regnum).add("civilId", civilId).add("name", name).build();
  }

  /**
   * Builds a {@link GraduatedVocationalStudentInfoParams}. Every setter accepts {@code null}, which
   * leaves the field out of the request. A builder is not thread-safe; it can be reused, and
   * setting a field again does not change the params it has already built.
   */
  public static final class Builder {
    private String regnum;
    private String civilId;
    private String name;

    private Builder() {}

    /**
     * Регистрийн дугаар.
     *
     * @param regnum the value, or {@code null}
     * @return this builder
     */
    public Builder regnum(String regnum) {
      this.regnum = regnum;
      return this;
    }

    /**
     * Иргэний ID.
     *
     * @param civilId the value, or {@code null}
     * @return this builder
     */
    public Builder civilId(String civilId) {
      this.civilId = civilId;
      return this;
    }

    /**
     * Нэр.
     *
     * @param name the value, or {@code null}
     * @return this builder
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GraduatedVocationalStudentInfoParams}
     */
    public GraduatedVocationalStudentInfoParams build() {
      return new GraduatedVocationalStudentInfoParams(this);
    }
  }
}
