// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.citizen;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import io.github.baljinnyamday.xyp.XypDate;

/**
 * The response of {@code WS100141_passportInfoSecondTime}: Үндэсний энгийн гадаад паспорт дахин
 * авсан тухай лавлагаа.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param regnum Иргэний регистрийн дугаар
 * @param forename Ургийн овог
 * @param surname Эцэг/эхийн нэр
 * @param givenname Нэр
 * @param issuedDate Олгосон огноо
 * @param passportNum Гадаад паспортын E дугаар
 * @param invIssuedDate Өмнөх паспортын олгосон огноо
 * @param invPassportNum Өмнөх паспортын E дугаар
 * @param invCauseName Шалтгаан
 * @param registeredNum Бүртгэлийн дугаар
 * @param citizenship Иргэншил
 * @param sex Хүйс
 * @param birthDate Төрсөн огноо
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record PassportInfoSecondTimeResponse(
    Object regnum,
    String forename,
    String surname,
    String givenname,
    XypDate issuedDate,
    String passportNum,
    XypDate invIssuedDate,
    String invPassportNum,
    String invCauseName,
    String registeredNum,
    String citizenship,
    String sex,
    String birthDate,
    Extras extras) {

  static PassportInfoSecondTimeResponse decode(ResponseReader reader) {
    return new PassportInfoSecondTimeResponse(
        reader.get("regnum", Decoders.ANY),
        reader.get("forename", Decoders.STRING),
        reader.get("surname", Decoders.STRING),
        reader.get("givenname", Decoders.STRING),
        reader.get("issuedDate", Decoders.DATE),
        reader.get("passportNum", Decoders.STRING),
        reader.get("invIssuedDate", Decoders.DATE),
        reader.get("invPassportNum", Decoders.STRING),
        reader.get("invCauseName", Decoders.STRING),
        reader.get("registeredNum", Decoders.STRING),
        reader.get("citizenship", Decoders.STRING),
        reader.get("sex", Decoders.STRING),
        reader.get("birthDate", Decoders.STRING),
        reader.extras());
  }
}
