// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.citizen;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS102102_RegnumChangeInfoEnglish}: Регистрийн дугаар өөрчилсний лавлагаа-
 * Англи.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData Жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record RegnumChangeInfoEnglishResponse(List<ListData> listData, Extras extras) {

  static RegnumChangeInfoEnglishResponse decode(ResponseReader reader) {
    return new RegnumChangeInfoEnglishResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * Жагсаалт.
   *
   * @param forename Овог (англи)
   * @param surname Эцгийн нэр (англи)
   * @param givenName Өөрийн нэр (англи)
   * @param regnumOld Хуучин регистрийн дугаар
   * @param changeRegnumCauseName Регистр өөрчилсөн шалтгаан (нэр)
   * @param changeRegnumCauseCode Регистр өөрчилсөн шалтгаан (код)
   * @param regnumNew Шинэ регистрийн дугаар
   * @param nationalityName Иргэншил (нэр)
   * @param civilId Бүртгэлийн дугаар
   * @param sexName Хүйс
   */
  public record ListData(
      String forename,
      String surname,
      String givenName,
      String regnumOld,
      String changeRegnumCauseName,
      String changeRegnumCauseCode,
      String regnumNew,
      String nationalityName,
      Long civilId,
      String sexName) {

    static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("forename", Decoders.STRING),
          reader.get("surname", Decoders.STRING),
          reader.get("givenName", Decoders.STRING),
          reader.get("regnumOld", Decoders.STRING),
          reader.get("changeRegnumCauseName", Decoders.STRING),
          reader.get("changeRegnumCauseCode", Decoders.STRING),
          reader.get("regnumNew", Decoders.STRING),
          reader.get("nationalityName", Decoders.STRING),
          reader.get("civilId", Decoders.INT),
          reader.get("sexName", Decoders.STRING));
    }
  }
}
