"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100928_householdScoreCheckInfo (labor_welfare, Хөдөлмөр халамж, үйлчилгээний ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100928_householdScoreCheckInfo"


class HouseholdScoreCheckInfoResponse(XypModel):
    """WS100928_householdScoreCheckInfo: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээсэн эсэхийг шалгах"""

    regnum: str | None = Field(
        default=None, alias="regnum", description="Иргэний регистрийн дугаар"
    )
    is_member_size: int | None = Field(
        default=None,
        alias="isMemberSize",
        description="Ам бүлийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0",
    )
    is_children: int | None = Field(
        default=None,
        alias="isChildren",
        description="Хүүхдийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0",
    )
    is_property_num: int | None = Field(
        default=None,
        alias="isPropertyNum",
        description="Үл хөдлөх хөрөнгийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0",
    )
    is_car_num: int | None = Field(
        default=None,
        alias="isCarNum",
        description="тээврийн хэрэгслийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0",
    )
    is_livestock_num: int | None = Field(
        default=None,
        alias="isLivestockNum",
        description="малын тоогоо шалгуулах эсэх тийм-1, үгүй-0",
    )
    is_salary: int | None = Field(
        default=None,
        alias="isSalary",
        description="цалингийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0",
    )
    is_pre_tax: int | None = Field(
        default=None,
        alias="isPreTax",
        description="татварын мэдээллээ шалгуулах эсэх тийм-1, үгүй-0",
    )


def household_score_check_info(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> HouseholdScoreCheckInfoResponse:
    """WS100928_householdScoreCheckInfo: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээсэн эсэхийг шалгах

    Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар

    Args:
        regnum: регистрийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(HouseholdScoreCheckInfoResponse, data)


async def household_score_check_info_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> HouseholdScoreCheckInfoResponse:
    """WS100928_householdScoreCheckInfo: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээсэн эсэхийг шалгах

    Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар

    Args:
        regnum: регистрийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(HouseholdScoreCheckInfoResponse, data)
