/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * FS100107_foreignerResidencePermitInquiry (foreignService, Гадаадын иргэн харьяатын газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "FS100107_foreignerResidencePermitInquiry";

/** Input of FS100107_foreignerResidencePermitInquiry. */
export interface ForeignerResidencePermitInquiryParams {
  /** регистр */
  readonly regnum?: string;
}

/** FS100107_foreignerResidencePermitInquiry: Гадаад иргэний оршин суух зөвшөөрлийн лавлагаа */
export interface ForeignerResidencePermitInquiryResponse {
  /** Овог */
  readonly lastName: string | null;
  /** Нэр */
  readonly firstName: string | null;
  /** Иргэншил */
  readonly citizenShip: string | null;
  /** Хүйс */
  readonly gender: string | null;
  /** пасспортын дугаар */
  readonly passwordNumber: string | null;
  /** регистр */
  readonly fregistryNumber: string | null;
  /** төрсөн огноо */
  readonly birthDay: string | null;
  /** оршин суух хэлбэр */
  readonly visaCategory: string | null;
  /** байгууллага */
  readonly legalEntityName: string | null;
  /** олгосон огноо */
  readonly issuedDate: string | null;
  /** дуусах хугацаа */
  readonly expiryDate: string | null;
}

const SCHEMA: Schema = { lastName: "string", firstName: "string", citizenShip: "string", gender: "string", passwordNumber: "string", fregistryNumber: "string", birthDay: "string", visaCategory: "string", legalEntityName: "string", issuedDate: "string", expiryDate: "string" };

/**
 * FS100107_foreignerResidencePermitInquiry: Гадаад иргэний оршин суух зөвшөөрлийн лавлагаа
 *
 * Provider: Гадаадын иргэн харьяатын газар
 */
export async function foreignerResidencePermitInquiry(transport: Transport, params: ForeignerResidencePermitInquiryParams = {}, options: CallOptions = {}): Promise<XypResult<ForeignerResidencePermitInquiryResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<ForeignerResidencePermitInquiryResponse>("ForeignerResidencePermitInquiryResponse", SCHEMA, data);
}
