// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.payment;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS100804_citizenCreateInvoice}: Төрийн үйлчилгээний төлбөрийн системийн
 * нэхэмжлэх үүсгэх сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param code Амжилттай болсон эсэх код
 * @param message Тайлбар мэдээлэл
 * @param invCode Нэхэмжлэхийн код
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record CitizenCreateInvoiceResponse(
    Long code, String message, String invCode, Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static CitizenCreateInvoiceResponse decode(ResponseReader reader) {
    return new CitizenCreateInvoiceResponse(
        reader.get("code", Decoders.INT),
        reader.get("message", Decoders.STRING),
        reader.get("invCode", Decoders.STRING),
        reader.extras());
  }
}
