// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.payment;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS100863_CourtDecisionReturn}: Шүүхийн шийдвэрээр буцаалт хийх хүсэлт
 * илгээх сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param code Хүсэлтийн дугаар
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record CourtDecisionReturnResponse(String code, Extras extras) {

  static CourtDecisionReturnResponse decode(ResponseReader reader) {
    return new CourtDecisionReturnResponse(reader.get("code", Decoders.STRING), reader.extras());
  }
}
