// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.payment;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100847_ExchangeRate}: Монголбанкны албан ханш авах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param dataList жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record ExchangeRateResponse(List<DataList> dataList, Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static ExchangeRateResponse decode(ResponseReader reader) {
    return new ExchangeRateResponse(
        reader.get("dataList", Decoders.list(Decoders.object(DataList::decode))), reader.extras());
  }

  /**
   * жагсаалт.
   *
   * @param name Нэр
   * @param code код
   * @param price Ханш
   * @param date огноо
   */
  public record DataList(String name, String code, String price, String date) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static DataList decode(ResponseReader reader) {
      return new DataList(
          reader.get("name", Decoders.STRING),
          reader.get("code", Decoders.STRING),
          reader.get("price", Decoders.STRING),
          reader.get("date", Decoders.STRING));
    }
  }
}
