// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.payment;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100840_legalEntityBSLoanInfo}: Бүрэн Скор Зээлийн Мэдээллийн сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param firstname Нэр
 * @param lastname Овог
 * @param address Хаяг
 * @param regnum Регистрийн дугаар
 * @param familyname Ургийн овог
 * @param nationality Яс, үндэс
 * @param count Зээлийн тоо
 * @param inquiry Зээлийн мэдээллүүд
 * @param liveStockData Малын А данс
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record LegalEntityBSLoanInfoResponse(
    String firstname,
    String lastname,
    String address,
    String regnum,
    String familyname,
    String nationality,
    Long count,
    Object inquiry,
    List<LiveStockData> liveStockData,
    Extras extras) {

  static LegalEntityBSLoanInfoResponse decode(ResponseReader reader) {
    return new LegalEntityBSLoanInfoResponse(
        reader.get("firstname", Decoders.STRING),
        reader.get("lastname", Decoders.STRING),
        reader.get("address", Decoders.STRING),
        reader.get("regnum", Decoders.STRING),
        reader.get("familyname", Decoders.STRING),
        reader.get("nationality", Decoders.STRING),
        reader.get("count", Decoders.INT),
        reader.get("inquiry", Decoders.ANY),
        reader.get("liveStockData", Decoders.list(Decoders.object(LiveStockData::decode))),
        reader.extras());
  }

  /**
   * Малын А данс.
   *
   * @param cowAmount Үхрийн тоо
   * @param horseAmount Морины тоо
   * @param sheepAmount Хонины тоо
   * @param goatAmount Ямааны тоо
   * @param camelAmount Тэмээний тоо
   * @param totalAmount Нийт малын тоо
   * @param startyear the {@code startyear} field
   * @param address Бүртгэсэн хаяг
   */
  public record LiveStockData(
      Long cowAmount,
      Long horseAmount,
      Long sheepAmount,
      Long goatAmount,
      Long camelAmount,
      Long totalAmount,
      Long startyear,
      String address) {

    static LiveStockData decode(ResponseReader reader) {
      return new LiveStockData(
          reader.get("cowAmount", Decoders.INT),
          reader.get("horseAmount", Decoders.INT),
          reader.get("sheepAmount", Decoders.INT),
          reader.get("goatAmount", Decoders.INT),
          reader.get("camelAmount", Decoders.INT),
          reader.get("totalAmount", Decoders.INT),
          reader.get("startyear", Decoders.INT),
          reader.get("address", Decoders.STRING));
    }
  }
}
