// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.payment;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The request of {@link PaymentClient#paymentOrderInvoiceGenerator}, XYP operation {@code
 * WS100862_PaymentOrderInvoiceGenerator}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class PaymentOrderInvoiceGeneratorParams implements RequestParams {
  private final String authorityTin;
  private final String taxpayerTin;
  private final Long taxpayerEntId;
  private final String taxTypeCode;
  private final String branchCode;
  private final String subBranchCode;
  private final Long amount;
  private final String description;
  private final String phoneNumber;
  private final Long type;
  private final Long configId;
  private final String calledFrom;
  private final List<Object> requiredFeilds;

  private PaymentOrderInvoiceGeneratorParams(Builder builder) {
    this.authorityTin = builder.authorityTin;
    this.taxpayerTin = builder.taxpayerTin;
    this.taxpayerEntId = builder.taxpayerEntId;
    this.taxTypeCode = builder.taxTypeCode;
    this.branchCode = builder.branchCode;
    this.subBranchCode = builder.subBranchCode;
    this.amount = builder.amount;
    this.description = builder.description;
    this.phoneNumber = builder.phoneNumber;
    this.type = builder.type;
    this.configId = builder.configId;
    this.calledFrom = builder.calledFrom;
    this.requiredFeilds = builder.requiredFeilds;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * УТХ хүлээн авагч байгууллагын татвар төлөгчийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String authorityTin() {
    return authorityTin;
  }

  /**
   * Харилцагчийн татвар төлөгчийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String taxpayerTin() {
    return taxpayerTin;
  }

  /**
   * Returns the {@code taxpayerEntId} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long taxpayerEntId() {
    return taxpayerEntId;
  }

  /**
   * Татварын төрлийн код.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String taxTypeCode() {
    return taxTypeCode;
  }

  /**
   * Татварын албаны код.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String branchCode() {
    return branchCode;
  }

  /**
   * Татварын дэд албаны код.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String subBranchCode() {
    return subBranchCode;
  }

  /**
   * Төлбөрийн дүн.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long amount() {
    return amount;
  }

  /**
   * Тайлбар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String description() {
    return description;
  }

  /**
   * Харилцагчийн утас.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String phoneNumber() {
    return phoneNumber;
  }

  /**
   * 2-taxTypeCode заавал, 1-stateAccount заавал.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long type() {
    return type;
  }

  /**
   * Тохиргооны дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long configId() {
    return configId;
  }

  /**
   * Returns the {@code calledFrom} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String calledFrom() {
    return calledFrom;
  }

  /**
   * жагсаалт.
   *
   * @return the value, or {@code null} when it is not set
   */
  public List<Object> requiredFeilds() {
    return requiredFeilds;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("authorityTin", authorityTin)
        .add("taxpayerTin", taxpayerTin)
        .add("taxpayerEntId", taxpayerEntId)
        .add("taxTypeCode", taxTypeCode)
        .add("branchCode", branchCode)
        .add("subBranchCode", subBranchCode)
        .add("amount", amount)
        .add("description", description)
        .add("phoneNumber", phoneNumber)
        .add("type", type)
        .add("configId", configId)
        .add("calledFrom", calledFrom)
        .add("requiredFeilds", requiredFeilds)
        .build();
  }

  /**
   * Builds a {@link PaymentOrderInvoiceGeneratorParams}. Every setter accepts {@code null}, which
   * leaves the field out of the request. A builder is not thread-safe; it can be reused, and
   * setting a field again does not change the params it has already built.
   */
  public static final class Builder {
    private String authorityTin;
    private String taxpayerTin;
    private Long taxpayerEntId;
    private String taxTypeCode;
    private String branchCode;
    private String subBranchCode;
    private Long amount;
    private String description;
    private String phoneNumber;
    private Long type;
    private Long configId;
    private String calledFrom;
    private List<Object> requiredFeilds;

    private Builder() {}

    /**
     * УТХ хүлээн авагч байгууллагын татвар төлөгчийн дугаар.
     *
     * @param authorityTin the value, or {@code null}
     * @return this builder
     */
    public Builder authorityTin(String authorityTin) {
      this.authorityTin = authorityTin;
      return this;
    }

    /**
     * Харилцагчийн татвар төлөгчийн дугаар.
     *
     * @param taxpayerTin the value, or {@code null}
     * @return this builder
     */
    public Builder taxpayerTin(String taxpayerTin) {
      this.taxpayerTin = taxpayerTin;
      return this;
    }

    /**
     * Sets the {@code taxpayerEntId} field.
     *
     * @param taxpayerEntId the value, or {@code null}
     * @return this builder
     */
    public Builder taxpayerEntId(Long taxpayerEntId) {
      this.taxpayerEntId = taxpayerEntId;
      return this;
    }

    /**
     * Татварын төрлийн код.
     *
     * @param taxTypeCode the value, or {@code null}
     * @return this builder
     */
    public Builder taxTypeCode(String taxTypeCode) {
      this.taxTypeCode = taxTypeCode;
      return this;
    }

    /**
     * Татварын албаны код.
     *
     * @param branchCode the value, or {@code null}
     * @return this builder
     */
    public Builder branchCode(String branchCode) {
      this.branchCode = branchCode;
      return this;
    }

    /**
     * Татварын дэд албаны код.
     *
     * @param subBranchCode the value, or {@code null}
     * @return this builder
     */
    public Builder subBranchCode(String subBranchCode) {
      this.subBranchCode = subBranchCode;
      return this;
    }

    /**
     * Төлбөрийн дүн.
     *
     * @param amount the value, or {@code null}
     * @return this builder
     */
    public Builder amount(Long amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Тайлбар.
     *
     * @param description the value, or {@code null}
     * @return this builder
     */
    public Builder description(String description) {
      this.description = description;
      return this;
    }

    /**
     * Харилцагчийн утас.
     *
     * @param phoneNumber the value, or {@code null}
     * @return this builder
     */
    public Builder phoneNumber(String phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    /**
     * 2-taxTypeCode заавал, 1-stateAccount заавал.
     *
     * @param type the value, or {@code null}
     * @return this builder
     */
    public Builder type(Long type) {
      this.type = type;
      return this;
    }

    /**
     * Тохиргооны дугаар.
     *
     * @param configId the value, or {@code null}
     * @return this builder
     */
    public Builder configId(Long configId) {
      this.configId = configId;
      return this;
    }

    /**
     * Sets the {@code calledFrom} field.
     *
     * @param calledFrom the value, or {@code null}
     * @return this builder
     */
    public Builder calledFrom(String calledFrom) {
      this.calledFrom = calledFrom;
      return this;
    }

    /**
     * жагсаалт.
     *
     * @param requiredFeilds the values, copied (a {@code null} item is not sent), or {@code null}
     * @return this builder
     */
    public Builder requiredFeilds(List<Object> requiredFeilds) {
      this.requiredFeilds =
          requiredFeilds == null
              ? null
              : Collections.unmodifiableList(new ArrayList<>(requiredFeilds));
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link PaymentOrderInvoiceGeneratorParams}
     */
    public PaymentOrderInvoiceGeneratorParams build() {
      return new PaymentOrderInvoiceGeneratorParams(this);
    }
  }
}
