// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.payment;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100818_taxPayerInfo}: Татвар төлөгчийн Регистрийн дугаараар ТТД-ын
 * лавлагаа авах.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listTins Татвар төлөгчийн жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record TaxPayerInfoResponse(List<ListTins> listTins, Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static TaxPayerInfoResponse decode(ResponseReader reader) {
    return new TaxPayerInfoResponse(
        reader.get("listTins", Decoders.list(Decoders.object(ListTins::decode))), reader.extras());
  }

  /**
   * Татвар төлөгчийн жагсаалт.
   *
   * @param tin Татвар төлөгчийн дугаар
   * @param name Татвар төлөгчийн нэр
   */
  public record ListTins(String tin, String name) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static ListTins decode(ResponseReader reader) {
      return new ListTins(reader.get("tin", Decoders.STRING), reader.get("name", Decoders.STRING));
    }
  }
}
