/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * The `privateService` group: 6 services served from private-service-1.5.0.
 * Each service lives in its own module under `operations/privateService`.
 */

import { type CheckKindergartenEnrollmentPS100104Params, checkKindergartenEnrollment } from "../operations/privateService/checkKindergartenEnrollment.js";
import { type ChildrenInfoByParentCivilIdPS100102Params, childrenInfoByParentCivilId } from "../operations/privateService/childrenInfoByParentCivilId.js";
import { type IDCardInfoEmParams, iDCardInfoEm } from "../operations/privateService/iDCardInfoEm.js";
import { type KindergartenDescriptionPS100101Params, kindergartenDescription } from "../operations/privateService/kindergartenDescription.js";
import { type ResultKindergartenEnrollmentParams, resultKindergartenEnrollment } from "../operations/privateService/resultKindergartenEnrollment.js";
import { type SendKindergartenEnrollmentPS100103Params, sendKindergartenEnrollment } from "../operations/privateService/sendKindergartenEnrollment.js";
import type { CallOptions, Transport } from "../transport.js";

export type PrivateServiceService = ReturnType<typeof createPrivateServiceService>;

export function createPrivateServiceService(transport: Transport) {
  return {
    /**
     * PS100101_kindergartenDescription: сургуулийн өмнөх боловсролын сургалтын байгууллагад суралцаж байгаа тодорхойлолтийн мэдээлэл дуудах
     *
     * Provider: Боловсролын мэдээллийн технологийн Төв
     */
    kindergartenDescription: (params: KindergartenDescriptionPS100101Params = {}, options: CallOptions = {}) => kindergartenDescription(transport, params, options),
    /**
     * PS100102_childrenInfoByParentCivilId: Эцэг эхийн бүртгэлээр хүүхдийн мэдээлэл дуудах
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     */
    childrenInfoByParentCivilId: (params: ChildrenInfoByParentCivilIdPS100102Params = {}, options: CallOptions = {}) => childrenInfoByParentCivilId(transport, params, options),
    /**
     * PS100103_sendKindergartenEnrollment: СӨБ Элсэлтийн бүртгэл илгээх
     *
     * Provider: Боловсролын мэдээллийн технологийн Төв
     */
    sendKindergartenEnrollment: (params: SendKindergartenEnrollmentPS100103Params = {}, options: CallOptions = {}) => sendKindergartenEnrollment(transport, params, options),
    /**
     * PS100104_checkKindergartenEnrollment: СӨБ Элсэлтийн бүртгэл шалгах
     *
     * Provider: Боловсролын мэдээллийн технологийн Төв
     */
    checkKindergartenEnrollment: (params: CheckKindergartenEnrollmentPS100104Params = {}, options: CallOptions = {}) => checkKindergartenEnrollment(transport, params, options),
    /**
     * PS100110_resultKindergartenEnrollment: Нийслэлийн цэцэрлэгийн хуваарилалт
     *
     * Provider: Боловсролын мэдээллийн технологийн Төв
     */
    resultKindergartenEnrollment: (params: ResultKindergartenEnrollmentParams = {}, options: CallOptions = {}) => resultKindergartenEnrollment(transport, params, options),
    /**
     * PS100111_IDCardInfoEm: Иргэний үнэмлэхний мэдээлэл дамжуулах сервис
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     */
    iDCardInfoEm: (params: IDCardInfoEmParams = {}, options: CallOptions = {}) => iDCardInfoEm(transport, params, options),
  } as const;
}
