<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Statistic;

/**
 * Мэдээллийн жагсаалт
 *
 * `listData` in the response of WS200102_citizenPastureInfo.
 */
final readonly class CitizenPastureInfoListData
{
    /**
     * @param int|null $livestockTypeCode Малын төрөл код
     * @param string|null $livestockTypeName Малын төрөл нэр
     * @param int|null $total Бүгд мал
     * @param int|null $newbornSires Хээлтүүлэгч
     * @param int|null $newbornSiresNew Хээлтүүлэгч шинээр тавьсан
     * @param int|null $newbornThisYearMale Энэ жилийн төл мал эр
     * @param int|null $newbornThisYearFemale Энэ жилийн төл мал эм
     * @param int|null $newbornLastYearMale Өнгөрсөн жилийн төл мал эр
     * @param int|null $newbornLastYearFemale Өнгөрсөн жилийн төл мал эм
     * @param int|null $twoYearsOldMale 2 настай эр
     * @param int|null $twoYearsOldFemale 2 настай эм
     * @param int|null $threeYearsOldMale 3 настай эр
     * @param int|null $threeYearsOldFemale 3 настай эм
     * @param int|null $fourYearsOldMale 4 настай эр
     * @param int|null $fourYearsOldFemale 4 настай эм
     * @param int|null $fiveAndAboveYearsOldMale 5 ба түүнээс дээш настай эр
     * @param int|null $fiveAndAboveYearsOldFemale 5 ба түүнээс дээш настай эм
     * @param int|null $totalLastYear Оны эхэнд тоологдсон малын тоо
     * @param int|null $purchased Нэмэгдсэн: Худалдаж авсан
     * @param int|null $transferredIn Нэмэгдсэн: Шилжиж ирсэн
     * @param int|null $found Нэмэгдсэн: Алдсан, хулгайлагдсан, олдохгүй байсан малыг олсон
     * @param int|null $newborn Нэмэгдсэн: Бэлэн тоологдсон төл
     * @param int|null $sold Хасагдсан: Зах зээлд худалдаж, борлуулсан
     * @param int|null $transferredOut Хасагдсан: Шилжүүлсэн
     * @param int|null $lost Хасагдсан: Алдсан, хулгайлагдсан, олдохгүй байгаа
     * @param int|null $soldForSlaughter Хасагдсан: Хүнсэнд хэрэглэсэн
     * @param int|null $lossesAdultAnimals Хасагдсан: Зүй бусаар хорогдсон
     * @param int|null $naturalDisaster Хасагдсан: Үүнээс - Аюулт үзэгдлээр
     * @param int|null $disease Хасагдсан: Үүнээс - Өвчнөөр
     * @param int|null $attackedByWildAnimals Хасагдсан: Үүнээс - Зэрлэг амьтанд бариулсан
     * @param int|null $other Хасагдсан: Үүнээс- Бусад
     */
    public function __construct(
        public ?int $livestockTypeCode = null,
        public ?string $livestockTypeName = null,
        public ?int $total = null,
        public ?int $newbornSires = null,
        public ?int $newbornSiresNew = null,
        public ?int $newbornThisYearMale = null,
        public ?int $newbornThisYearFemale = null,
        public ?int $newbornLastYearMale = null,
        public ?int $newbornLastYearFemale = null,
        public ?int $twoYearsOldMale = null,
        public ?int $twoYearsOldFemale = null,
        public ?int $threeYearsOldMale = null,
        public ?int $threeYearsOldFemale = null,
        public ?int $fourYearsOldMale = null,
        public ?int $fourYearsOldFemale = null,
        public ?int $fiveAndAboveYearsOldMale = null,
        public ?int $fiveAndAboveYearsOldFemale = null,
        public ?int $totalLastYear = null,
        public ?int $purchased = null,
        public ?int $transferredIn = null,
        public ?int $found = null,
        public ?int $newborn = null,
        public ?int $sold = null,
        public ?int $transferredOut = null,
        public ?int $lost = null,
        public ?int $soldForSlaughter = null,
        public ?int $lossesAdultAnimals = null,
        public ?int $naturalDisaster = null,
        public ?int $disease = null,
        public ?int $attackedByWildAnimals = null,
        public ?int $other = null,
    ) {}
}
