<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Statistic;

/**
 * Input of WS200114_citizenStatisticInfo: Иргэний мэдээлэл.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class CitizenStatisticInfoParams
{
    /**
     * @param string|null $regnum регистрийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
