<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Statistic;

/**
 * Input of WS200126_umnsHouseholdInfo: ӨМНС малын тоо мэдээлэл авах сервис.
 *
 * Provider: Үндэсний статистикийн хороо
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class UmnsHouseholdInfoParams
{
    /**
     * @param string|null $regnum Регистрийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
