<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Health;

/**
 * Input of WS300126_eHospitalCheckPatientExists: EHospital Тухайн эмнэлэгт хэрэглэгч бүртгэлтэй эсэх.
 *
 * Provider: Эрүүл мэндийн даатгалын ерөнхий газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class EHospitalCheckPatientExistsParams
{
    /**
     * @param string|null $regnum регистрийн дугаар
     * @param int|null $hospitalId эмнэлгийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
        public ?int $hospitalId = null,
    ) {}
}
