<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Health;

use Xyp\Attribute\Bytes;
use Xyp\Extras;

/**
 * Response of WS300130_eHospitalGetAnalysisResult: EHospital шинжилгээний хариу дуудах сервис.
 *
 * Provider: Эрүүл мэндийн даатгалын ерөнхий газар
 */
final readonly class EHospitalGetAnalysisResultResponse
{
    /**
     * @param string|null $analysisResult шинжилгээний хариу
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        #[Bytes]
        public ?string $analysisResult = null,
        public Extras $xyp = new Extras(),
    ) {}
}
