<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Health;

/**
 * Жагсаалт
 *
 * `data` in the response of WS300154_GetDataByFormSummary.
 */
final readonly class GetDataByFormSummaryData
{
    /**
     * @param string|null $hospitalName Эмнэлгийн нэр
     * @param string|null $indate Огноо
     * @param string|null $serviceNo Тусламж, үйлчилгээний дугаар
     * @param string|null $pregnanWeek Жирэмсний 7 хоног /недель/
     */
    public function __construct(
        public ?string $hospitalName = null,
        public ?string $indate = null,
        public ?string $serviceNo = null,
        public ?string $pregnanWeek = null,
    ) {}
}
