<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Health;

/**
 * Input of WS300150_GetHospitalListInfo: Эмнэлгийн жагсаалт татах сервис.
 *
 * Provider: Эрүүл мэндийн яам
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class GetHospitalListInfoParams
{
    /**
     * @param int|null $operationId Үйл ажиллагааны дугаар
     * @param bool|null $status Төлөв
     */
    public function __construct(
        public ?int $operationId = null,
        public ?bool $status = null,
    ) {}
}
