<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Health;

use Xyp\Attribute\ListOf;

/**
 * Жагсаалт
 *
 * `data` in the response of WS300150_GetHospitalListInfo.
 */
final readonly class GetHospitalListInfoData
{
    /**
     * @param int|null $hospitalTypeId Төрөл дугаар
     * @param string|null $officeCode Аймаг, хот дугаар
     * @param string|null $subOfficeCode Сум, дүүрэг дугаар
     * @param list<mixed> $operationList Үйл ажиллагааны чиглэлийн мэдээлэл
     * @param int|null $id Эмнэлгийн системийн дугаар
     * @param string|null $hospitalName Нэр
     * @param string|null $hospitalType Төрөл
     * @param string|null $hospitalRegnum Регистр
     * @param string|null $hospitalPhone Утасны дугаар
     * @param string|null $hospitalPersonPhone Холбоо барих хүний дугаар
     * @param string|null $hospitalEmail Имэйл хаяг
     * @param string|null $hospitalSocial Сошиал хаяг
     * @param string|null $hospitalAddress Хаяг
     * @param float|null $hospitalLatitude Өргөрөг
     * @param float|null $hospitalLongitude Уртраг
     * @param string|null $hospitalTimetable Цагийн хуваарь
     * @param string|null $hospitalTimetableStr Ажиллах өдрийн хуваарь
     * @param int|null $hospitalCapacity Багтаамж
     * @param string|null $hospitalIntroduction Танилцуулга
     * @param string|null $officeName Аймаг, хот
     * @param string|null $subOfficeName Сум, дүүрэг
     * @param int|null $hasInsurance Даатгалтай эсэх 1-Тийм, 0-Үгүй
     * @param int|null $hasBranch Салбартай эсэх 1-Тийм, 0-Үгүй
     * @param string|null $inspectionRate
     * @param list<mixed> $branchList Салбарын мэдээлэл
     */
    public function __construct(
        public ?int $hospitalTypeId = null,
        public ?string $officeCode = null,
        public ?string $subOfficeCode = null,
        #[ListOf('any')]
        public array $operationList = [],
        public ?int $id = null,
        public ?string $hospitalName = null,
        public ?string $hospitalType = null,
        public ?string $hospitalRegnum = null,
        public ?string $hospitalPhone = null,
        public ?string $hospitalPersonPhone = null,
        public ?string $hospitalEmail = null,
        public ?string $hospitalSocial = null,
        public ?string $hospitalAddress = null,
        public ?float $hospitalLatitude = null,
        public ?float $hospitalLongitude = null,
        public ?string $hospitalTimetable = null,
        public ?string $hospitalTimetableStr = null,
        public ?int $hospitalCapacity = null,
        public ?string $hospitalIntroduction = null,
        public ?string $officeName = null,
        public ?string $subOfficeName = null,
        public ?int $hasInsurance = null,
        public ?int $hasBranch = null,
        public ?string $inspectionRate = null,
        #[ListOf('any')]
        public array $branchList = [],
    ) {}
}
