<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Health;

/**
 * Input of WS300152_GetHealthInsurancePremiumList: Эрүүл мэндийн даатгалын шимтгэл төлөгдсөн болон төлөгдөөгүй саруудыг ялгаж буцаах сервис.
 *
 * Provider: Эрүүл мэндийн даатгалын ерөнхий газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class GetHealthInsurancePremiumListParams
{
    /**
     * @param string|null $regnum Регистр
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
