// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

/**
 * The 6 XYP services of the {@code private_service} group, served from {@code
 * private-service-1.5.0}.
 *
 * <p>Call them through {@link io.github.baljinnyamday.xyp.privateservice.PrivateServiceClient},
 * which {@code XypClient.privateService()} returns.
 */
package io.github.baljinnyamday.xyp.privateservice;
