<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * Input of GS10029_citizenNoMarriageInfoData: Гэрлэсний бүртгэлгүй лавлагаа ангил хэл дээр.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class CitizenNoMarriageInfoDataParams
{
    /**
     * @param string|null $regnum иргэний регистрийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
