<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * хаягийн жагсаалт
 *
 * `addressList` in the response of GS10026_citizenIDCardInfoEng.
 */
final readonly class CitizenIDCardInfoEngAddressList
{
    /**
     * @param string|null $arrivedDate огноо
     * @param string|null $cityName аймаг нэр
     * @param string|null $districtName дүүрэг нэр
     * @param string|null $bagName баг нэр
     * @param string|null $addressRegionName хэсэг
     * @param string|null $addressStreetName гудамж
     * @param string|null $addressTownName хотхон
     * @param string|null $addressApartmentName байр
     * @param string|null $addressDetail хаягийн дэлгэрэнгүй
     */
    public function __construct(
        public ?string $arrivedDate = null,
        public ?string $cityName = null,
        public ?string $districtName = null,
        public ?string $bagName = null,
        public ?string $addressRegionName = null,
        public ?string $addressStreetName = null,
        public ?string $addressTownName = null,
        public ?string $addressApartmentName = null,
        public ?string $addressDetail = null,
    ) {}
}
