<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of GS10088_EnergyQualificationService: Эрчим хүчний салбарын мэргэшлийн зэрэг эзэмшигчдийн мэдээлэл лавлах.
 *
 * Provider: Эрчим хүчний яам
 */
final readonly class EnergyQualificationServiceResponse
{
    /**
     * @param string|null $lastName Эцэг/эхийн нэр
     * @param string|null $firstName Өөрийн нэр
     * @param list<EnergyQualificationServiceListData> $listData Жагсаалт
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $lastName = null,
        public ?string $firstName = null,
        #[ListOf(EnergyQualificationServiceListData::class)]
        public array $listData = [],
        public Extras $xyp = new Extras(),
    ) {}
}
