<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * Input of GS10061_GetFeedbackDimensionTags: Өргөдөл, гомдлын tag мэдээлэл.
 *
 * Provider: Засгийн газрын Хэрэг эрхлэх газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class GetFeedbackDimensionTagsParams
{
    /**
     * @param int|null $tagId
     */
    public function __construct(
        public ?int $tagId = null,
    ) {}
}
