<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * жагсаалт
 *
 * `list` in the response of GS10050_GetSoumDistrictListByZipcode.
 */
final readonly class GetSoumDistrictListByZipcodeList
{
    /**
     * @param int|null $zipCode Аймгийн зипкод
     * @param string|null $name Аймгийн нэр
     */
    public function __construct(
        public ?int $zipCode = null,
        public ?string $name = null,
    ) {}
}
