<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * жагсаалт
 *
 * `listData` in the response of GS10053_GetTreeRegister.
 */
final readonly class GetTreeRegisterListData
{
    /**
     * @param string|null $regnum регистрийн дугаар
     * @param string|null $phoneNumber Утасны дугаар
     * @param string|null $type
     * @param float|null $locationLon
     * @param float|null $locationLat
     * @param bool|null $isConfirmed
     * @param string|null $registeredNumber
     * @param string|null $createDate
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $phoneNumber = null,
        public ?string $type = null,
        public ?float $locationLon = null,
        public ?float $locationLat = null,
        public ?bool $isConfirmed = null,
        public ?string $registeredNumber = null,
        public ?string $createDate = null,
    ) {}
}
