<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * Input of GS10071_LawyerInfoService: Өмгөөлөгчийн дэлгэрэнгүй мэдээлэл дуудах сервис.
 *
 * Provider: Монголын өмгөөлөгчдийн холбоо
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class LawyerInfoServiceParams
{
    /**
     * @param string|null $regnum Регистр
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
