<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\GovernmentService;

/**
 * Input of GS10086_RiskRegistrationService: Эрсдэл бүртгэх нэгдсэн үйлдэл.
 *
 * Provider: И-Монголиа академи
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class RiskRegistrationServiceParams
{
    /**
     * @param string|null $ctpid
     * @param string|null $sttpid
     * @param string|null $desc эрсдэлийн тайлбар
     * @param string|null $tpid
     * @param string|null $envpid
     * @param string|null $systempid
     * @param string|null $orgregnum
     * @param string|null $orgname
     * @param string|null $imgurl
     * @param string|null $videourl
     * @param float|null $lt
     * @param float|null $ln
     * @param string|null $civilid
     */
    public function __construct(
        public ?string $ctpid = null,
        public ?string $sttpid = null,
        public ?string $desc = null,
        public ?string $tpid = null,
        public ?string $envpid = null,
        public ?string $systempid = null,
        public ?string $orgregnum = null,
        public ?string $orgname = null,
        public ?string $imgurl = null,
        public ?string $videourl = null,
        public ?float $lt = null,
        public ?float $ln = null,
        public ?string $civilid = null,
    ) {}
}
