// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.insurance;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The request of {@link InsuranceClient#checkMotherTimeAllInfo}, XYP operation {@code
 * WS100517_checkMotherTimeAllInfo}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class CheckMotherTimeAllInfoParams implements RequestParams {
  private final List<Object> listRequestData;

  private CheckMotherTimeAllInfoParams(Builder builder) {
    this.listRequestData = builder.listRequestData;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Регистрийн дугаарын жагсаалт.
   *
   * @return the value, or {@code null} when it is not set
   */
  public List<Object> listRequestData() {
    return listRequestData;
  }

  @Override
  public Params toParams() {
    return Params.builder().add("listRequestData", listRequestData).build();
  }

  /**
   * Builds a {@link CheckMotherTimeAllInfoParams}. Every setter accepts {@code null}, which leaves
   * the field out of the request. A builder is not thread-safe; it can be reused, and setting a
   * field again does not change the params it has already built.
   */
  public static final class Builder {
    private List<Object> listRequestData;

    private Builder() {}

    /**
     * Регистрийн дугаарын жагсаалт.
     *
     * @param listRequestData the values, copied (a {@code null} item is not sent), or {@code null}
     * @return this builder
     */
    public Builder listRequestData(List<Object> listRequestData) {
      this.listRequestData =
          listRequestData == null
              ? null
              : Collections.unmodifiableList(new ArrayList<>(listRequestData));
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link CheckMotherTimeAllInfoParams}
     */
    public CheckMotherTimeAllInfoParams build() {
      return new CheckMotherTimeAllInfoParams(this);
    }
  }
}
