// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.insurance;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link InsuranceClient#getBankAccount}, XYP operation {@code
 * WS100593_GetBankAccount}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GetBankAccountParams implements RequestParams {
  private final String invoiceNumber;

  private GetBankAccountParams(Builder builder) {
    this.invoiceNumber = builder.invoiceNumber;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Нэхэмжлэхийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String invoiceNumber() {
    return invoiceNumber;
  }

  @Override
  public Params toParams() {
    return Params.builder().add("invoiceNumber", invoiceNumber).build();
  }

  /**
   * Builds a {@link GetBankAccountParams}. Every setter accepts {@code null}, which leaves the
   * field out of the request. A builder is not thread-safe; it can be reused, and setting a field
   * again does not change the params it has already built.
   */
  public static final class Builder {
    private String invoiceNumber;

    private Builder() {}

    /**
     * Нэхэмжлэхийн дугаар.
     *
     * @param invoiceNumber the value, or {@code null}
     * @return this builder
     */
    public Builder invoiceNumber(String invoiceNumber) {
      this.invoiceNumber = invoiceNumber;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GetBankAccountParams}
     */
    public GetBankAccountParams build() {
      return new GetBankAccountParams(this);
    }
  }
}
