// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.insurance;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100581_insuranceOrgContributionInfo}: Нийгмийн даатгалын шимтгэл төлөгч
 * аж ахуйн нэгж, байгууллага, түүний салбар нэгжүүдийн мэдээлэл.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param orgRegnum Байгууллагын регистрийн дугаар
 * @param orgId Байгууллагын НД дугаар дугаар
 * @param orgName Байгууллагын нэр
 * @param aimagName Аймаг, нийслэл нэр
 * @param aimagId Аймаг, нийтслэл код
 * @param sumId Сум, дүүрэг код
 * @param sumName Сум, дүүрэг нэр
 * @param bagId Баг, хорооны код
 * @param bagName Баг, хорооны нэр
 * @param orgAddress Байгууллагын хаяг
 * @param orgPhone Байгууллагын утас
 * @param orgMail Байгууллагын и-мэйл хаяг
 * @param orgEZClassID ЭЗҮАС ангиалал код
 * @param orgEZClassName ЭЗҮАС ангиалал нэр
 * @param orgUmchID Өмчийн хэлбэр код
 * @param orgUmch Өмчийн хэлбэр нэр
 * @param orgHariutslagaID Хариуцлагын хэлбэр код
 * @param orgHariutslaga Хариуцлагын хэлбэр нэр
 * @param info the {@code info} field
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record InsuranceOrgContributionInfoResponse(
    String orgRegnum,
    String orgId,
    String orgName,
    String aimagName,
    String aimagId,
    String sumId,
    String sumName,
    String bagId,
    String bagName,
    String orgAddress,
    String orgPhone,
    String orgMail,
    String orgEZClassID,
    String orgEZClassName,
    String orgUmchID,
    String orgUmch,
    String orgHariutslagaID,
    String orgHariutslaga,
    List<Info> info,
    Extras extras) {

  static InsuranceOrgContributionInfoResponse decode(ResponseReader reader) {
    return new InsuranceOrgContributionInfoResponse(
        reader.get("orgRegnum", Decoders.STRING),
        reader.get("orgId", Decoders.STRING),
        reader.get("orgName", Decoders.STRING),
        reader.get("aimagName", Decoders.STRING),
        reader.get("aimagId", Decoders.STRING),
        reader.get("sumId", Decoders.STRING),
        reader.get("sumName", Decoders.STRING),
        reader.get("bagId", Decoders.STRING),
        reader.get("bagName", Decoders.STRING),
        reader.get("orgAddress", Decoders.STRING),
        reader.get("orgPhone", Decoders.STRING),
        reader.get("orgMail", Decoders.STRING),
        reader.get("orgEZClassID", Decoders.STRING),
        reader.get("orgEZClassName", Decoders.STRING),
        reader.get("orgUmchID", Decoders.STRING),
        reader.get("orgUmch", Decoders.STRING),
        reader.get("orgHariutslagaID", Decoders.STRING),
        reader.get("orgHariutslaga", Decoders.STRING),
        reader.get("info", Decoders.list(Decoders.object(Info::decode))),
        reader.extras());
  }

  /**
   * An element of the {@code info} list in the response of {@code
   * WS100581_insuranceOrgContributionInfo}.
   *
   * @param benCount Даатгуулагчдын тоо нийт
   * @param womanCount Даатгуулагчдын тоо этэгтэй
   * @param gadaad Гадаад даатгуулагчдын тоо этэгтэй
   * @param bClass Даатгуулагчдын төрөл
   * @param calSum Хөдөлмөрийн хөлс, түүнтэй адилтгах орлого бүгд
   * @param mainCal Үндсэн ба нэмэгдэл цалин
   * @param awardCal Шагналт цалин
   * @param otherAddCal Бусад нэмэгдэл цалин
   * @param unaaCal Хоол, унааны хөлс
   * @param tuleeCal Түлээ нүүрсний үнийн хөнгөлөлт
   * @param otherCal Бусад
   * @param ndSum Нийгмийн даатгалын санд ногдуулсан НДШ
   * @param ndOrgSum Нийгмийн даатгалын санд ажил олгогчоод ногдуулсан НДШ
   * @param ndBenSum Нийгмийн даатгалын санд даатгуулагчаас ногдуулсан НДШ
   * @param emdSum Нийгмийн даатгалын санд ногдуулсан ЭМД шимтгэл
   * @param emdOrgSum Нийгмийн даатгалын санд ажил олгогчоод ногдуулсан ЭМД шимтгэл
   * @param emdBenSum Нийгмийн даатгалын санд даатгуулагчаас ногдуулсан ЭМД шимтгэл
   */
  public record Info(
      Long benCount,
      Long womanCount,
      Long gadaad,
      String bClass,
      String calSum,
      String mainCal,
      String awardCal,
      String otherAddCal,
      String unaaCal,
      String tuleeCal,
      String otherCal,
      String ndSum,
      String ndOrgSum,
      String ndBenSum,
      String emdSum,
      String emdOrgSum,
      String emdBenSum) {

    static Info decode(ResponseReader reader) {
      return new Info(
          reader.get("benCount", Decoders.INT),
          reader.get("womanCount", Decoders.INT),
          reader.get("gadaad", Decoders.INT),
          reader.get("bClass", Decoders.STRING),
          reader.get("calSum", Decoders.STRING),
          reader.get("mainCal", Decoders.STRING),
          reader.get("awardCal", Decoders.STRING),
          reader.get("otherAddCal", Decoders.STRING),
          reader.get("unaaCal", Decoders.STRING),
          reader.get("tuleeCal", Decoders.STRING),
          reader.get("otherCal", Decoders.STRING),
          reader.get("ndSum", Decoders.STRING),
          reader.get("ndOrgSum", Decoders.STRING),
          reader.get("ndBenSum", Decoders.STRING),
          reader.get("emdSum", Decoders.STRING),
          reader.get("emdOrgSum", Decoders.STRING),
          reader.get("emdBenSum", Decoders.STRING));
    }
  }
}
