// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.insurance;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100560_refundHalfAccountList}: Даатгуулагчийн 50%-н буцаалт авах
 * бүртгэлтэй дансны дугаар.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData мэдээллийн жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record RefundHalfAccountListResponse(List<ListData> listData, Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static RefundHalfAccountListResponse decode(ResponseReader reader) {
    return new RefundHalfAccountListResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * мэдээллийн жагсаалт.
   *
   * @param id Бүртгэлийн дугаар
   * @param bankCode Банкны код
   * @param bankAccount Банк данс
   * @param bankName Банк нэр
   * @param lastname Овог
   * @param firstname Нэр
   * @param regnum Регистр
   * @param registeredDate Бүртгүүлсэн огноо
   */
  public record ListData(
      String id,
      String bankCode,
      String bankAccount,
      String bankName,
      String lastname,
      String firstname,
      String regnum,
      String registeredDate) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("id", Decoders.STRING),
          reader.get("bankCode", Decoders.STRING),
          reader.get("bankAccount", Decoders.STRING),
          reader.get("bankName", Decoders.STRING),
          reader.get("lastname", Decoders.STRING),
          reader.get("firstname", Decoders.STRING),
          reader.get("regnum", Decoders.STRING),
          reader.get("registeredDate", Decoders.STRING));
    }
  }
}
