// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package insurance

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// GetInsuranceProductsParams is the input of WS100594_GetInsuranceProducts. Every field is
// optional; a zero value is left out of the request.
type GetInsuranceProductsParams struct {
}

// GetInsuranceProductsList is a nested object in the response of WS100594_GetInsuranceProducts.
type GetInsuranceProductsList struct {
	// Id
	ProductId *int64 `xyp:"productId"`
	// Нэр
	ProductName string `xyp:"productName"`
}

// GetInsuranceProductsResponse is the response of WS100594_GetInsuranceProducts: НД-ийн бүтээгдэхүүний жагсаалт авах.
type GetInsuranceProductsResponse struct {
	List []GetInsuranceProductsList `xyp:"list"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// GetInsuranceProducts calls WS100594_GetInsuranceProducts: НД-ийн бүтээгдэхүүний жагсаалт авах
//
// Provider: Нийгмийн даатгалын ерөнхий газар
func (s *Service) GetInsuranceProducts(ctx context.Context, params GetInsuranceProductsParams, opts ...xyp.CallOption) (*GetInsuranceProductsResponse, error) {
	var out GetInsuranceProductsResponse
	extras, err := s.client.Invoke(ctx, "WS100594_GetInsuranceProducts", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
