// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package insurance

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// OrgInfoForStatisticParams is the input of WS100558_orgInfoForStatistic. Every field is
// optional; a zero value is left out of the request.
type OrgInfoForStatisticParams struct {
	// байгууллагын рд
	OrgRegnum string `xyp:"orgRegnum"`
}

// OrgInfoForStatisticListData: мэдээллийн жагсаалт
type OrgInfoForStatisticListData struct {
	// Аж ахуйн нэгж байгууллагын нийгмийн даатгалын дугаар
	OrgInsuranceID string `xyp:"orgInsuranceID"`
	// Аж ахуйн нэгж байгууллагын регистрийн дугаар
	OrgID string `xyp:"orgID"`
	// Аж ахуйн нэгж байгууллагын нэр
	OrgName string `xyp:"orgName"`
	// Аймаг, дүүргийн нэр
	AimagName string `xyp:"aimagName"`
	// Сум, хороо код
	SoumID string `xyp:"soumID"`
	// Сум, хороо
	SoumName string `xyp:"soumName"`
	// Баг, хороолол
	OrgHoroo string `xyp:"orgHoroo"`
	// Гудамж
	OrgGudamj string `xyp:"orgGudamj"`
	// Байшин
	OrgBaishin string `xyp:"orgBaishin"`
	// Хаалга
	OrgHaalga string `xyp:"orgHaalga"`
	// Аж ахуйн нэгж байгууллагын ЭЗҮАС ангилал
	EzClass string `xyp:"ezClass"`
	// Даатгуулагчдын тоо
	BenCount string `xyp:"benCount"`
	// Эмэгтэй даатгуулагчдын тоо
	EmCount string `xyp:"emCount"`
	// Гадаад даатгуулагчдын тоо
	GadaadCount string `xyp:"gadaadCount"`
	// Даатгуулагчдын цалингийн дүн
	BenCalin string `xyp:"benCalin"`
	// Эмэгтэй даатгуулагчдын цалингийн дүн
	EmCalin string `xyp:"emCalin"`
	// Гадаад даатгуулагчдын цалингийн дүн
	GadaadCalin string `xyp:"gadaadCalin"`
	// Нийт төлөх шимтгэлийн дүн
	Fee string `xyp:"fee"`
	// Ажил олгогчоос төлөх шимтгэлийн дүн
	OrgFee string `xyp:"orgFee"`
	// Эрүүл мэндийн даатгалын санд төлөх нийт шимтгэл
	EmdFee string `xyp:"emdFee"`
	// Ажил олгогчоос ЭМД санд төлөх шимтгэл
	OrgEmd string `xyp:"orgEmd"`
}

// OrgInfoForStatisticResponse is the response of WS100558_orgInfoForStatistic: Аж ахуйн нэгж байгууллагын мэдээлэл.
type OrgInfoForStatisticResponse struct {
	// мэдээллийн жагсаалт
	ListData []OrgInfoForStatisticListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// OrgInfoForStatistic calls WS100558_orgInfoForStatistic: Аж ахуйн нэгж байгууллагын мэдээлэл
//
// Provider: Нийгмийн даатгалын ерөнхий газар
func (s *Service) OrgInfoForStatistic(ctx context.Context, params OrgInfoForStatisticParams, opts ...xyp.CallOption) (*OrgInfoForStatisticResponse, error) {
	var out OrgInfoForStatisticResponse
	extras, err := s.client.Invoke(ctx, "WS100558_orgInfoForStatistic", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
