<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Transport;

use Xyp\Extras;

/**
 * Response of WS100495_ECLicenseCreator: EC лиценз үүсгэх сервис.
 *
 * Provider: Нийтийн тээврийн бодлогын газар
 */
final readonly class ECLicenseCreatorResponse
{
    /**
     * @param string|null $pdf pdf
     * @param int|null $licenceId licenceId
     * @param string|null $message Хариу мессеж
     * @param string|null $season Улирлын нэр
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $pdf = null,
        public ?int $licenceId = null,
        public ?string $message = null,
        public ?string $season = null,
        public Extras $xyp = new Extras(),
    ) {}
}
