<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Transport;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of WS100499_ProductList: Бүтээгдэхүүний жагсаалт авах сервис.
 *
 * Provider: Нийтийн тээврийн бодлогын газар
 */
final readonly class ProductListResponse
{
    /**
     * @param list<ProductListListData> $listData жагсаалт
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        #[ListOf(ProductListListData::class)]
        public array $listData = [],
        public Extras $xyp = new Extras(),
    ) {}
}
