<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Transport;

/**
 * Input of WS101403_VehicleCertificateEnglishInfo: Тээврийн хэрэгслийн цахим гэрчилгээний мэдээлэл авах англи сервис.
 *
 * Provider: Авто тээврийн үндэсний төв
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class VehicleCertificateEnglishInfoParams
{
    /**
     * @param string|null $plateNumber Улсын дугаар
     * @param string|null $cabinNumber Арлын дугаар
     */
    public function __construct(
        public ?string $plateNumber = null,
        public ?string $cabinNumber = null,
    ) {}
}
