/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS300190_CitizenServicePackageNumberInquiryService (health, Эрүүл мэндийн даатгалын ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS300190_CitizenServicePackageNumberInquiryService";

/** Input of WS300190_CitizenServicePackageNumberInquiryService. */
export interface CitizenServicePackageNumberInquiryServiceParams {
  /** Иргэний РД */
  readonly regnum?: string;
}

/** Жагсаалт */
export interface CitizenServicePackageNumberInquiryServiceListData {
  /** Иргэний төлөх дүн */
  readonly totalAmountCitizen: number | null;
  /** ЭМД-с хөнгөлөх дүн */
  readonly totolAmountInsurance: number | null;
  /** Багцын дугаар */
  readonly packageId: string | null;
  /** Тусламж үйлчилгээний жил */
  readonly year: number | null;
  /** Тусламж үйлчилгээний сар */
  readonly month: number | null;
}

/** WS300190_CitizenServicePackageNumberInquiryService: Иргэний авсан тусламж үйлчилгээний багцын дугаар лавлах сервис */
export interface CitizenServicePackageNumberInquiryServiceResponse {
  /** Жагсаалт */
  readonly listData: readonly CitizenServicePackageNumberInquiryServiceListData[] | null;
}

const SCHEMA: Schema = { listData: { list: { object: { totalAmountCitizen: "float", totolAmountInsurance: "float", packageId: "string", year: "int", month: "int" } } } };

/**
 * WS300190_CitizenServicePackageNumberInquiryService: Иргэний авсан тусламж үйлчилгээний багцын дугаар лавлах сервис
 *
 * Provider: Эрүүл мэндийн даатгалын ерөнхий газар
 */
export async function citizenServicePackageNumberInquiryService(transport: Transport, params: CitizenServicePackageNumberInquiryServiceParams = {}, options: CallOptions = {}): Promise<XypResult<CitizenServicePackageNumberInquiryServiceResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<CitizenServicePackageNumberInquiryServiceResponse>("CitizenServicePackageNumberInquiryServiceResponse", SCHEMA, data);
}
