/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS300144_CitizenImageDiagnosisAndAnalysisInfo (health, Эрүүл мэндийн яам)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS300144_CitizenImageDiagnosisAndAnalysisInfo";

/** Input of WS300144_CitizenImageDiagnosisAndAnalysisInfo. */
export interface CitizenImageDiagnosisAndAnalysisInfoParams {
  /** Шинжилгээ хийгдсэн жил */
  readonly year?: number;
  /** Иргэний регистрийн дугаар */
  readonly regnum?: string;
  /** Шинжилгээ хийгдсэн сар */
  readonly month?: number;
  /** 1 бол Дүрс оношилгоо, 2 бол Шинжилгээ , 3 бол */
  readonly type?: number;
}

/** Мэдээлэл */
export interface CitizenImageDiagnosisAndAnalysisInfoData {
  /** Тусламж, үйлчилгээний нэр */
  readonly serviceName: string | null;
  /** Тусламж, үйлчилгээний дугаар */
  readonly serviceId: string | null;
  /** Эмнэлгийн нэр */
  readonly hospitalName: string | null;
  /** Огноо */
  readonly date: string | null;
  /** Төрлийн дугаар */
  readonly type: number | null;
  /** Төрлийн нэр */
  readonly typeName: string | null;
  /** Холбоос */
  readonly link: string | null;
  /** Төлөв */
  readonly status: string | null;
  readonly docuid: string | null;
}

/** WS300144_CitizenImageDiagnosisAndAnalysisInfo: Иргэний дүрс оношилгоо болон шинжилгээний мэдээлэл лавлах сервис */
export interface CitizenImageDiagnosisAndAnalysisInfoResponse {
  /** Мэдээлэл */
  readonly data: readonly CitizenImageDiagnosisAndAnalysisInfoData[] | null;
}

const SCHEMA: Schema = { data: { list: { object: { serviceName: "string", serviceId: "string", hospitalName: "string", date: "string", type: "int", typeName: "string", link: "string", status: "string", docuid: "string" } } } };

/**
 * WS300144_CitizenImageDiagnosisAndAnalysisInfo: Иргэний дүрс оношилгоо болон шинжилгээний мэдээлэл лавлах сервис
 *
 * Provider: Эрүүл мэндийн яам
 */
export async function citizenImageDiagnosisAndAnalysisInfo(transport: Transport, params: CitizenImageDiagnosisAndAnalysisInfoParams = {}, options: CallOptions = {}): Promise<XypResult<CitizenImageDiagnosisAndAnalysisInfoResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      year: params.year,
      regnum: params.regnum,
      month: params.month,
      type: params.type,
    },
    options,
  );
  return decodeResponse<CitizenImageDiagnosisAndAnalysisInfoResponse>("CitizenImageDiagnosisAndAnalysisInfoResponse", SCHEMA, data);
}
