/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS300103_eHealthGetAnalysisResult (health, Эрүүл мэндийн яам)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS300103_eHealthGetAnalysisResult";

/** Input of WS300103_eHealthGetAnalysisResult. */
export interface EHealthGetAnalysisResultParams {
  /** регистрийн дугаар */
  readonly regnum?: string;
  /** эмнэлгийн дугаар */
  readonly hospitalId?: number;
  /** шинжилгээ өгсөн огноо */
  readonly analysisDate?: Date | string;
}

/** WS300103_eHealthGetAnalysisResult: EHealth шинжилгээний хариу дуудах сервис */
export interface EHealthGetAnalysisResultResponse {
  /** шинжилгээний хариу */
  readonly analysisResult: Uint8Array | null;
}

const SCHEMA: Schema = { analysisResult: "bytes" };

/**
 * WS300103_eHealthGetAnalysisResult: EHealth шинжилгээний хариу дуудах сервис
 *
 * Provider: Эрүүл мэндийн яам
 */
export async function eHealthGetAnalysisResult(transport: Transport, params: EHealthGetAnalysisResultParams = {}, options: CallOptions = {}): Promise<XypResult<EHealthGetAnalysisResultResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
      hospitalId: params.hospitalId,
      analysisDate: params.analysisDate,
    },
    options,
  );
  return decodeResponse<EHealthGetAnalysisResultResponse>("EHealthGetAnalysisResultResponse", SCHEMA, data);
}
