/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS300137_eHospitalTimeOrderCancel (health, Эрүүл мэндийн даатгалын ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS300137_eHospitalTimeOrderCancel";

/** Input of WS300137_eHospitalTimeOrderCancel. */
export interface EHospitalTimeOrderCancelParams {
  /** Эмнэлгийн дугаар */
  readonly hospitalId?: number;
  /** Баталгаажуулах код */
  readonly verifyCode?: string;
}

/** WS300137_eHospitalTimeOrderCancel: EHospital Цаг захиалгын бүртгэл цуцлах */
export interface EHospitalTimeOrderCancelResponse {
  /** хүсэлтийн хариу код */
  readonly checkCode: number | null;
}

const SCHEMA: Schema = { checkCode: "int" };

/**
 * WS300137_eHospitalTimeOrderCancel: EHospital Цаг захиалгын бүртгэл цуцлах
 *
 * Provider: Эрүүл мэндийн даатгалын ерөнхий газар
 */
export async function eHospitalTimeOrderCancel(transport: Transport, params: EHospitalTimeOrderCancelParams = {}, options: CallOptions = {}): Promise<XypResult<EHospitalTimeOrderCancelResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      hospitalId: params.hospitalId,
      verifyCode: params.verifyCode,
    },
    options,
  );
  return decodeResponse<EHospitalTimeOrderCancelResponse>("EHospitalTimeOrderCancelResponse", SCHEMA, data);
}
