/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS300121_getForm13AList (health, Эрүүл мэндийн даатгалын ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS300121_getForm13AList";

/** Input of WS300121_getForm13AList. */
export interface GetForm13AListParams {
  /** регистр */
  readonly regnum?: string;
}

/** мэдээллийн жагсаалт */
export interface GetForm13AListListData {
  /** Илгээсэн эрүүл мэндийн байгууллага */
  readonly hospitalName: string | null;
  /** Цахим маягтын илгээх дугаар */
  readonly requestNo: string | null;
  /** Илгээх шалтгаан тайлбар */
  readonly sentReasonStr: string | null;
  /** Цахим маягтын төлвийн тайлбар */
  readonly statusStr: string | null;
  /** Цахим маягтын хүчинтэй хугацаа */
  readonly expireDate: string | null;
}

/** WS300121_getForm13AList: Иргэнийг шатлал хооронд шилжүүлэх цахим маягтын жагсаалт авах сервис */
export interface GetForm13AListResponse {
  /** мэдээллийн жагсаалт */
  readonly listData: readonly GetForm13AListListData[] | null;
}

const SCHEMA: Schema = { listData: { list: { object: { hospitalName: "string", requestNo: "string", sentReasonStr: "string", statusStr: "string", expireDate: "string" } } } };

/**
 * WS300121_getForm13AList: Иргэнийг шатлал хооронд шилжүүлэх цахим маягтын жагсаалт авах сервис
 *
 * Provider: Эрүүл мэндийн даатгалын ерөнхий газар
 */
export async function getForm13AList(transport: Transport, params: GetForm13AListParams = {}, options: CallOptions = {}): Promise<XypResult<GetForm13AListResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<GetForm13AListResponse>("GetForm13AListResponse", SCHEMA, data);
}
