/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS300188_PreventiveScreeningInfo (health, Эрүүл мэндийн хөгжлийн төв)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS300188_PreventiveScreeningInfo";

/** Input of WS300188_PreventiveScreeningInfo. */
export interface PreventiveScreeningInfoParams {
  /** Иргэний регистрийн дугаар */
  readonly regnum?: string;
}

/** Лицензийн жагсаалт */
export interface PreventiveScreeningInfoListdata {
  /** Дугаар */
  readonly bookNumber: string | null;
  /** Регистрийн дугаар */
  readonly regnum: string | null;
  /** Овог */
  readonly lastName: string | null;
  /** Нэр */
  readonly firstName: string | null;
  /** Байгууллагын нэр */
  readonly orgName: string | null;
  /** Эрхэлдэг ажил */
  readonly occupation: string | null;
  /** Ажилд орсон өдөр */
  readonly employmentDate: string | null;
  /** Ерөнхий хариу */
  readonly finalTestResult: string | null;
  /** Ерөнхий тэмдэглэл */
  readonly finalNote: string | null;
  /** Баталгаажуулсан эмнэлэг */
  readonly hospitalName: string | null;
  /** Баталгаажуулсан эмчийн нэр */
  readonly approvedDoctorName: string | null;
  /** Баталгаажуулсан огноо */
  readonly approvedDate: string | null;
  readonly createdBy: number | null;
  readonly createdByName: string | null;
  /** Лицензийн жагсаалт */
  readonly results: readonly unknown[] | null;
}

/** WS300188_PreventiveScreeningInfo: УРЬДЧИЛАН СЭРГИЙЛЭХ ҮЗЛЭГ, ШИНЖИЛГЭЭНИЙ МЭДЭЭЛЭЛ ДУУДАХ СЕРВИС */
export interface PreventiveScreeningInfoResponse {
  /** Лицензийн жагсаалт */
  readonly listdata: readonly PreventiveScreeningInfoListdata[] | null;
}

const SCHEMA: Schema = {
  listdata: {
    list: {
      object: {
        bookNumber: "string",
        regnum: "string",
        lastName: "string",
        firstName: "string",
        orgName: "string",
        occupation: "string",
        employmentDate: "string",
        finalTestResult: "string",
        finalNote: "string",
        hospitalName: "string",
        approvedDoctorName: "string",
        approvedDate: "string",
        createdBy: "int",
        createdByName: "string",
        results: { list: "any" },
      },
    },
  },
};

/**
 * WS300188_PreventiveScreeningInfo: УРЬДЧИЛАН СЭРГИЙЛЭХ ҮЗЛЭГ, ШИНЖИЛГЭЭНИЙ МЭДЭЭЛЭЛ ДУУДАХ СЕРВИС
 *
 * Provider: Эрүүл мэндийн хөгжлийн төв
 */
export async function preventiveScreeningInfo(transport: Transport, params: PreventiveScreeningInfoParams = {}, options: CallOptions = {}): Promise<XypResult<PreventiveScreeningInfoResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<PreventiveScreeningInfoResponse>("PreventiveScreeningInfoResponse", SCHEMA, data);
}
