// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package property

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// GetPropertyInfoByNationalPropertyNumberEngParams is the input of WS100252_getPropertyInfoByNationalPropertyNumberEng. Every field is
// optional; a zero value is left out of the request.
type GetPropertyInfoByNationalPropertyNumberEngParams struct {
	PropertyNationalRegnum string `xyp:"propertyNationalRegnum"`
}

// GetPropertyInfoByNationalPropertyNumberEngData: жагсаалт
type GetPropertyInfoByNationalPropertyNumberEngData struct {
	RegistDe             string `xyp:"registDe"`
	PrprtyServiceId      string `xyp:"prprtyServiceId"`
	PrprtyNationRegistNo string `xyp:"prprtyNationRegistNo"`
}

// GetPropertyInfoByNationalPropertyNumberEngResponse is the response of WS100252_getPropertyInfoByNationalPropertyNumberEng: Иргэний эд хөрөнгийн англи лавлагааг эд хөрөнгийн дугаараар дуудах сервис.
type GetPropertyInfoByNationalPropertyNumberEngResponse struct {
	// жагсаалт
	Data []GetPropertyInfoByNationalPropertyNumberEngData `xyp:"data"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// GetPropertyInfoByNationalPropertyNumberEng calls WS100252_getPropertyInfoByNationalPropertyNumberEng: Иргэний эд хөрөнгийн англи лавлагааг эд хөрөнгийн дугаараар дуудах сервис
//
// Provider: Улсын бүртгэлийн ерөнхий газар
func (s *Service) GetPropertyInfoByNationalPropertyNumberEng(ctx context.Context, params GetPropertyInfoByNationalPropertyNumberEngParams, opts ...xyp.CallOption) (*GetPropertyInfoByNationalPropertyNumberEngResponse, error) {
	var out GetPropertyInfoByNationalPropertyNumberEngResponse
	extras, err := s.client.Invoke(ctx, "WS100252_getPropertyInfoByNationalPropertyNumberEng", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
