// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package property

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// GetPropertyInfoParams is the input of WS100201_getPropertyInfo. Every field is
// optional; a zero value is left out of the request.
type GetPropertyInfoParams struct {
	Regnum         string `xyp:"regnum"`
	PropertyNumber string `xyp:"propertyNumber"`
}

// GetPropertyInfoOwnerList is a nested object in the response of WS100201_getPropertyInfo.
type GetPropertyInfoOwnerList struct {
	// Ургийн овог
	ForeName string `xyp:"foreName"`
	// Овог
	LastName string `xyp:"lastName"`
	// Нэр
	Firstname string `xyp:"firstname"`
	// Регистрийн дугаар
	Regnum string `xyp:"regnum"`
	// Харьяалал
	Address string `xyp:"address"`
}

// GetPropertyInfoPrprtyHistory is a nested object in the response of WS100201_getPropertyInfo.
type GetPropertyInfoPrprtyHistory struct {
	// Үйлчилгээний нэр
	ServiceName string `xyp:"serviceName"`
	// үйлчилгээний огноо
	RegisterDate string `xyp:"registerDate"`
	// Өмчлөгчийн нэр
	OwnerName string `xyp:"ownerName"`
	// Өмчлөгчийн төлөв
	RegisteredStatus string `xyp:"registeredStatus"`
	// үүрэг ноогдуулсан гэрээнд оролцогч тал
	PersonNmCorpNn2 string `xyp:"personNmCorpNn2"`
	// гэрээниЙ үнэ
	ContractPrize string `xyp:"contractPrize"`
	// зургийн тоо
	ImgCnt string `xyp:"imgCnt"`
}

// GetPropertyInfoResponse is the response of WS100201_getPropertyInfo: Үл хөдлөх хөрөнгийн мэдээлэл дамжуулах сервис.
type GetPropertyInfoResponse struct {
	PrprtyType string `xyp:"prprtyType"`
	// Үл хөдлөхийн дугаар
	PrprtyNatNum string `xyp:"prprtyNatNum"`
	// Кадастрын дугаар
	CadastNum string `xyp:"cadastNum"`
	// Хаяг
	FullAddress string `xyp:"fullAddress"`
	// Хэмжээ
	PrprtySize string `xyp:"prprtySize"`
	// Үнэ
	PrprtyValue string `xyp:"prprtyValue"`
	// зориулалт
	PrprtyUsage   string                         `xyp:"prprtyUsage"`
	OwnerList     []GetPropertyInfoOwnerList     `xyp:"ownerList"`
	PrprtyHistory []GetPropertyInfoPrprtyHistory `xyp:"prprtyHistory"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// GetPropertyInfo calls WS100201_getPropertyInfo: Үл хөдлөх хөрөнгийн мэдээлэл дамжуулах сервис
//
// Provider: Улсын бүртгэлийн ерөнхий газар
func (s *Service) GetPropertyInfo(ctx context.Context, params GetPropertyInfoParams, opts ...xyp.CallOption) (*GetPropertyInfoResponse, error) {
	var out GetPropertyInfoResponse
	extras, err := s.client.Invoke(ctx, "WS100201_getPropertyInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
