// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package property

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// UmnsPropertyInfoParams is the input of WS100248_umnsPropertyInfo. Every field is
// optional; a zero value is left out of the request.
type UmnsPropertyInfoParams struct {
	// мэдээллийн жагсаалт
	Regnum string `xyp:"regnum"`
}

// UmnsPropertyInfoListData: мэдээллийн жагсаалт
type UmnsPropertyInfoListData struct {
	// иргэний тоо
	CitizenCount string `xyp:"citizenCount"`
	// Талбайн хэмжээ дундаж
	AverageSize string `xyp:"averageSize"`
	// регистрийн дугаар
	Regnum string `xyp:"regnum"`
	// үл хөдлөхийн дугаар
	PropertyId string `xyp:"propertyId"`
	// байршил
	LocationId string `xyp:"locationId"`
	// хэмжээ
	PropertySize string `xyp:"propertySize"`
	// төрөл
	TypeId string `xyp:"typeId"`
}

// UmnsPropertyInfoResponse is the response of WS100248_umnsPropertyInfo: ӨМНС үл хөдлөх хөрөнгийн мэдээлэл.
type UmnsPropertyInfoResponse struct {
	// мэдээллийн жагсаалт
	ListData []UmnsPropertyInfoListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// UmnsPropertyInfo calls WS100248_umnsPropertyInfo: ӨМНС үл хөдлөх хөрөнгийн мэдээлэл
//
// Provider: Улсын бүртгэлийн ерөнхий газар
func (s *Service) UmnsPropertyInfo(ctx context.Context, params UmnsPropertyInfoParams, opts ...xyp.CallOption) (*UmnsPropertyInfoResponse, error) {
	var out UmnsPropertyInfoResponse
	extras, err := s.client.Invoke(ctx, "WS100248_umnsPropertyInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
