// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package statistic

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// ChangeNameInfoParams is the input of WS200116_changeNameInfo. Every field is
// optional; a zero value is left out of the request.
type ChangeNameInfoParams struct {
	// огноо
	Date xyp.Date `xyp:"date"`
}

// ChangeNameInfoListData: мэдээллийн жагсаалт
type ChangeNameInfoListData struct {
	// Регистр
	Regnum string `xyp:"regnum"`
	// Хуучин ургийн овог
	Surname string `xyp:"surname"`
	// Хуучин овог
	Lastname string `xyp:"lastname"`
	// Хуучин нэр
	Firstname string `xyp:"firstname"`
	// Шинэ ургийн овог
	NewSurname string `xyp:"newSurname"`
	// Шинэ овог
	NewLastname string `xyp:"newLastname"`
	// Шинэ нэр
	NewFirstname string `xyp:"newFirstname"`
	// Нэр сольсон он сар өдөр цаг минут секунд
	Date xyp.Date `xyp:"date"`
}

// ChangeNameInfoResponse is the response of WS200116_changeNameInfo: Нэр сольсон мэдээлэл.
type ChangeNameInfoResponse struct {
	// мэдээллийн жагсаалт
	ListData []ChangeNameInfoListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// ChangeNameInfo calls WS200116_changeNameInfo: Нэр сольсон мэдээлэл
//
// Provider: Улсын бүртгэлийн ерөнхий газар
func (s *Service) ChangeNameInfo(ctx context.Context, params ChangeNameInfoParams, opts ...xyp.CallOption) (*ChangeNameInfoResponse, error) {
	var out ChangeNameInfoResponse
	extras, err := s.client.Invoke(ctx, "WS200116_changeNameInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
