// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package statistic

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// LivestockTaxSurveyServiceParams is the input of WS200110_livestockTaxSurveyService. Every field is
// optional; a zero value is left out of the request.
type LivestockTaxSurveyServiceParams struct {
	// Иргэний регистр
	Regnum string `xyp:"regnum"`
	// Төсвийн жил
	Year *int64 `xyp:"year"`
	// Баг/хорооны код
	BagCode *int64 `xyp:"bagCode"`
	// Санхүүжүүлэх чиг үүргийн код
	CategoryCode string `xyp:"categoryCode"`
	// Төсөл арга хэмжээний нэр
	Description string `xyp:"description"`
	// {Санал-3-PK} /Хэрэв мэдээлэл засахаар бол энэ баганад PK онооно/
	Code *int64 `xyp:"code"`
}

// LivestockTaxSurveyServiceResponse is the response of WS200110_livestockTaxSurveyService: Малын хөлийн татварын төсөл хөтөлбөрийн санал өгөх сервис..
type LivestockTaxSurveyServiceResponse struct {
	// Амжилттай бол “Success” Амжилтгүй бол “Алдааны мессеж”;
	Result string `xyp:"result"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// LivestockTaxSurveyService calls WS200110_livestockTaxSurveyService: Малын хөлийн татварын төсөл хөтөлбөрийн санал өгөх сервис.
//
// Provider: Сангийн яам
func (s *Service) LivestockTaxSurveyService(ctx context.Context, params LivestockTaxSurveyServiceParams, opts ...xyp.CallOption) (*LivestockTaxSurveyServiceResponse, error) {
	var out LivestockTaxSurveyServiceResponse
	extras, err := s.client.Invoke(ctx, "WS200110_livestockTaxSurveyService", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
