"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100582_enterprisesOrgContributionInfo (insurance, Нийгмийн даатгалын ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100582_enterprisesOrgContributionInfo"


class EnterprisesOrgContributionInfoInfo(XypModel):
    report_year: str | None = Field(default=None, alias="reportYear", description="Тайлангийн он")
    report_month: str | None = Field(
        default=None, alias="reportMonth", description="Тайлангийн сар"
    )
    gender_count: str | None = Field(
        default=None, alias="genderCount", description="Даатгуулагчдын тоо нийт"
    )
    gender: str | None = Field(
        default=None, alias="gender", description="Даатгуулагчдын тоо этэгтэй"
    )
    age: int | None = Field(default=None, alias="age", description="нас")
    gadaad: str | None = Field(default=None, alias="gadaad")
    b_class: str | None = Field(default=None, alias="bClass", description="Даатгуулагчдын төрөл")
    b_class_name: str | None = Field(
        default=None, alias="bClassName", description="Даатгуулагчдын төрөл"
    )
    occ_id: str | None = Field(
        default=None, alias="occID", description="Гадаад даатгуулагчдын тоо этэгтэй"
    )
    occ_name: str | None = Field(
        default=None, alias="occName", description="Ажил мэргэжлийн ангилал нэр"
    )
    cal_sum: str | None = Field(
        default=None, alias="calSum", description="Хөдөлмөрийн хөлс, түүнтэй адилтгах орлого бүгд"
    )
    main_cal: str | None = Field(
        default=None, alias="mainCal", description="Үндсэн ба нэмэгдэл цалин"
    )
    award_cal: str | None = Field(default=None, alias="awardCal", description="Шагналт цалин")
    other_add_cal: str | None = Field(
        default=None, alias="otherAddCal", description="Бусад нэмэгдэл цалин"
    )
    unaa_cal: str | None = Field(default=None, alias="unaaCal")
    other_cal: str | None = Field(default=None, alias="otherCal", description="Бусад")
    nd_sum: str | None = Field(
        default=None, alias="ndSum", description="Нийгмийн даатгалын санд ногдуулсан НДШ"
    )
    emd_sum: str | None = Field(
        default=None, alias="emdSum", description="Нийгмийн даатгалын санд ногдуулсан ЭМД шимтгэл"
    )


class EnterprisesOrgContributionInfoResponse(XypModel):
    """WS100582_enterprisesOrgContributionInfo: Аж ахуйн нэгж, байгууллага, ажиллагчдын цалин, шимтгэл"""

    aimag_name: str | None = Field(
        default=None, alias="aimagName", description="Аймаг, нийслэл нэр"
    )
    aimag_id: str | None = Field(default=None, alias="aimagId", description="Аймаг, нийтслэл код")
    org_address: str | None = Field(
        default=None, alias="orgAddress", description="Байгууллагын хаяг"
    )
    org_phone: str | None = Field(default=None, alias="orgPhone", description="Байгууллагын утас")
    org_mail: str | None = Field(
        default=None, alias="orgMail", description="Байгууллагын и-мэйл хаяг"
    )
    org_ez_class_id: str | None = Field(
        default=None, alias="orgEZClassID", description="ЭЗҮАС ангиалал код"
    )
    org_ez_class_name: str | None = Field(
        default=None, alias="orgEZClassName", description="ЭЗҮАС ангиалал нэр"
    )
    org_umch_id: str | None = Field(
        default=None, alias="orgUmchID", description="Өмчийн хэлбэр код"
    )
    org_umch: str | None = Field(default=None, alias="orgUmch", description="Өмчийн хэлбэр нэр")
    org_hariutslaga_id: str | None = Field(
        default=None, alias="orgHariutslagaID", description="Хариуцлагын хэлбэр код"
    )
    org_hariutslaga: str | None = Field(
        default=None, alias="orgHariutslaga", description="Хариуцлагын хэлбэр нэр"
    )
    info: list[EnterprisesOrgContributionInfoInfo] | None = Field(default=None, alias="info")


def enterprises_org_contribution_info(
    self: SyncService,
    *,
    org_regnum: str | None = None,
    org_id: str | None = None,
    org_name: str | None = None,
    report_year: str | None = None,
    report_month: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EnterprisesOrgContributionInfoResponse:
    """WS100582_enterprisesOrgContributionInfo: Аж ахуйн нэгж, байгууллага, ажиллагчдын цалин, шимтгэл

    Provider: Нийгмийн даатгалын ерөнхий газар

    Args:
        org_regnum: Байгууллагын регистр
        org_id: Байгууллагын НД бүртгэлийн дугаар
        org_name: Байгууллагын нэр
        report_year: Тайлангийн он
        report_month: Тайлангийн сар
        start_date: Эхлэх огноо
        end_date: Дуусах огноо
    """
    data = self._transport.call(
        _OPERATION,
        {
            "orgRegnum": org_regnum,
            "orgId": org_id,
            "OrgName": org_name,
            "reportYear": report_year,
            "reportMonth": report_month,
            "startDate": start_date,
            "endDate": end_date,
        },
        auth,
        operator,
    )
    return parse_model(EnterprisesOrgContributionInfoResponse, data)


async def enterprises_org_contribution_info_async(
    self: AsyncService,
    *,
    org_regnum: str | None = None,
    org_id: str | None = None,
    org_name: str | None = None,
    report_year: str | None = None,
    report_month: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EnterprisesOrgContributionInfoResponse:
    """WS100582_enterprisesOrgContributionInfo: Аж ахуйн нэгж, байгууллага, ажиллагчдын цалин, шимтгэл

    Provider: Нийгмийн даатгалын ерөнхий газар

    Args:
        org_regnum: Байгууллагын регистр
        org_id: Байгууллагын НД бүртгэлийн дугаар
        org_name: Байгууллагын нэр
        report_year: Тайлангийн он
        report_month: Тайлангийн сар
        start_date: Эхлэх огноо
        end_date: Дуусах огноо
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "orgRegnum": org_regnum,
            "orgId": org_id,
            "OrgName": org_name,
            "reportYear": report_year,
            "reportMonth": report_month,
            "startDate": start_date,
            "endDate": end_date,
        },
        auth,
        operator,
    )
    return parse_model(EnterprisesOrgContributionInfoResponse, data)
