"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100565_getCitizenSalaryInfoEng (insurance, Нийгмийн даатгалын ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100565_getCitizenSalaryInfoEng"


class GetCitizenSalaryInfoEngDetailDataList(XypModel):
    dom_name: str | None = Field(default=None, alias="domName")
    is_payed: str | None = Field(default=None, alias="isPayed")
    month: int | None = Field(default=None, alias="month")
    occcode: str | None = Field(default=None, alias="occcode")
    org_name: str | None = Field(default=None, alias="orgName")
    orgndid: str | None = Field(default=None, alias="orgndid")
    org_reg_id: str | None = Field(default=None, alias="orgRegId")
    salary: float | None = Field(default=None, alias="salary")
    shim: float | None = Field(default=None, alias="shim")
    year: int | None = Field(default=None, alias="year")


class GetCitizenSalaryInfoEngResponse(XypModel):
    """WS100565_getCitizenSalaryInfoEng: Иргэний нийгмийн даатгалын мэдээлэл ангил хэл дээр дамжуулах сервис"""

    detail_data_list: list[GetCitizenSalaryInfoEngDetailDataList] | None = Field(
        default=None, alias="detailDataList"
    )
    firstname: str | None = Field(default=None, alias="firstname", description="Нэр")
    lastname: str | None = Field(default=None, alias="lastname", description="Овог")
    regnum: str | None = Field(
        default=None, alias="regnum", description="Иргэний регистрийн дугаар"
    )


def get_citizen_salary_info_eng(
    self: SyncService,
    *,
    regnum: str | None = None,
    start_year: int | None = None,
    end_year: int | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetCitizenSalaryInfoEngResponse:
    """WS100565_getCitizenSalaryInfoEng: Иргэний нийгмийн даатгалын мэдээлэл ангил хэл дээр дамжуулах сервис

    Provider: Нийгмийн даатгалын ерөнхий газар

    Args:
        regnum: Регистрийн дугаар
        start_year: Эхлэх огноо
        end_year: Дуусах огноо
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "startYear": start_year,
            "endYear": end_year,
        },
        auth,
        operator,
    )
    return parse_model(GetCitizenSalaryInfoEngResponse, data)


async def get_citizen_salary_info_eng_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    start_year: int | None = None,
    end_year: int | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetCitizenSalaryInfoEngResponse:
    """WS100565_getCitizenSalaryInfoEng: Иргэний нийгмийн даатгалын мэдээлэл ангил хэл дээр дамжуулах сервис

    Provider: Нийгмийн даатгалын ерөнхий газар

    Args:
        regnum: Регистрийн дугаар
        start_year: Эхлэх огноо
        end_year: Дуусах огноо
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "startYear": start_year,
            "endYear": end_year,
        },
        auth,
        operator,
    )
    return parse_model(GetCitizenSalaryInfoEngResponse, data)
