"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100556_getHealthInsuranceFee (insurance, Нийгмийн даатгалын ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypDate, XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100556_getHealthInsuranceFee"


class GetHealthInsuranceFeeListData(XypModel):
    """мэдээллийн жагсаалт"""

    aimag_code: str | None = Field(
        default=None, alias="aimagCode", description="Аймаг, дүүргийн код"
    )
    aimag_name: str | None = Field(
        default=None, alias="aimagName", description="Аймаг, дүүргийн нэр"
    )
    ben_class: str | None = Field(
        default=None, alias="benClass", description="Даатгуулагчийн төрөл код"
    )
    ben_class_name: str | None = Field(
        default=None, alias="benClassName", description="Даатгуулагчийн төрөл нэр"
    )
    start_date: XypDate | None = Field(default=None, alias="startDate", description="Эхлэх огноо")
    end_date: XypDate | None = Field(default=None, alias="endDate", description="Дуусах огноо")
    firstname: str | None = Field(default=None, alias="firstname", description="Нэр")
    lastname: str | None = Field(default=None, alias="lastname", description="Овог")
    meta: int | None = Field(default=None, alias="meta", description="Төрөл")
    regnum: str | None = Field(default=None, alias="regnum", description="Регистр")
    reg_date: XypDate | None = Field(default=None, alias="regDate", description="Бүртгэсэн огноо")


class GetHealthInsuranceFeeResponse(XypModel):
    """WS100556_getHealthInsuranceFee: Эрүүл мэндийн даатгал шалгах"""

    list_data: list[GetHealthInsuranceFeeListData] | None = Field(
        default=None, alias="listData", description="мэдээллийн жагсаалт"
    )


def get_health_insurance_fee(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetHealthInsuranceFeeResponse:
    """WS100556_getHealthInsuranceFee: Эрүүл мэндийн даатгал шалгах

    Provider: Нийгмийн даатгалын ерөнхий газар

    Args:
        regnum: регистр
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetHealthInsuranceFeeResponse, data)


async def get_health_insurance_fee_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetHealthInsuranceFeeResponse:
    """WS100556_getHealthInsuranceFee: Эрүүл мэндийн даатгал шалгах

    Provider: Нийгмийн даатгалын ерөнхий газар

    Args:
        regnum: регистр
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetHealthInsuranceFeeResponse, data)
