"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100547_pregnancyChildbirthEdit (insurance, Хөдөлмөр халамж, үйлчилгээний ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100547_pregnancyChildbirthEdit"


class PregnancyChildbirthEditResponse(XypModel):
    """WS100547_pregnancyChildbirthEdit: Жирэмсэн амаржсаны эмнэлгийн хуудас мэдээлэлд засвар хийх"""

    result: int | None = Field(default=None, alias="result", description="0 – success, 1 – error")
    result_msg: str | None = Field(default=None, alias="resultMsg", description="тайлбар")


def pregnancy_childbirth_edit(
    self: SyncService,
    *,
    medical_certnumber: str | None = None,
    company_id: int | None = None,
    lastname: str | None = None,
    firsthname: str | None = None,
    regnum: str | None = None,
    address: str | None = None,
    aimag_code: str | None = None,
    org_id: str | None = None,
    medical_cert_type_id: int | None = None,
    medical_cert_type_name: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    phone: str | None = None,
    created_date: str | None = None,
    updated_date: str | None = None,
    hospital_id: str | None = None,
    hospital_name: str | None = None,
    general_doctor_id: str | None = None,
    general_doctor_name: str | None = None,
    confirm_doctor_id: str | None = None,
    confirm_doctor_name: str | None = None,
    is_twins: bool | None = None,
    ehk_decision_number: str | None = None,
    pregnancy_period: str | None = None,
    history_number: str | None = None,
    counter_name: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> PregnancyChildbirthEditResponse:
    """WS100547_pregnancyChildbirthEdit: Жирэмсэн амаржсаны эмнэлгийн хуудас мэдээлэлд засвар хийх

    Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар

    Args:
        medical_certnumber: Эмнэлгийн хуудасны дугаар
        company_id: Эмнэлгийн хуудас бичих програм код
        lastname: Иргэний Эцэг /эх/-ийн нэр
        firsthname: Иргэний Нэр
        regnum: Иргэний регистрийн дугаар
        address: Иргэний хаяг
        aimag_code: Аж ахуйн нэгж байгууллагын Аймаг, дүүргийн код
        org_id: Аж ахуйн нэгж байгууллагын код
        medical_cert_type_id: Эмнэлгийн хуудасны төрлийн код
        medical_cert_type_name: Эмнэлгийн хуудасны төрлийн нэр
        start_date: Эхлэх огноо "yyyy-MM-dd"
        end_date: Дуусах огноо "yyyy-MM-dd"
        phone: утасны дугаар
        created_date: Эмнэлгийн хуудасны бичсэн огноо "yyyy-MM-dd"
        updated_date: Эмнэлгийн хуудасны зассан огноо "yyyy-MM-dd"
        hospital_id: Эмнэлгийн хуудас олгосон эмнэлгийн код
        hospital_name: Эмнэлгийн хуудас олгосон эмнэлгийн нэр
        general_doctor_id: Ерөнхий эмчийн код
        general_doctor_name: Ерөнхий эмчийн нэр
        confirm_doctor_id: Эмчлэгч эмчийн код
        confirm_doctor_name: Эмчлэгч эмчийн нэр
        is_twins: Ихэр хүүхэд мөн эсэх
        ehk_decision_number: Эмнэлэг хяналтын комисийн шийдвэрийн дугаар.
        pregnancy_period: Жирэмсний долоо хоног
        history_number: Өвчний түүхийн дугаар
        counter_name: Хэрэв гадаад улсад төрсөн бол улсын нэр
    """
    data = self._transport.call(
        _OPERATION,
        {
            "medicalCertnumber": medical_certnumber,
            "companyId": company_id,
            "lastname": lastname,
            "firsthname": firsthname,
            "regnum": regnum,
            "address": address,
            "aimagCode": aimag_code,
            "orgId": org_id,
            "medicalCertTypeId": medical_cert_type_id,
            "medicalCertTypeName": medical_cert_type_name,
            "startDate": start_date,
            "endDate": end_date,
            "phone": phone,
            "createdDate": created_date,
            "updatedDate": updated_date,
            "hospitalId": hospital_id,
            "hospitalName": hospital_name,
            "generalDoctorId": general_doctor_id,
            "generalDoctorName": general_doctor_name,
            "confirmDoctorId": confirm_doctor_id,
            "confirmDoctorName": confirm_doctor_name,
            "isTwins": is_twins,
            "ehkDecisionNumber": ehk_decision_number,
            "pregnancyPeriod": pregnancy_period,
            "historyNumber": history_number,
            "counterName": counter_name,
        },
        auth,
        operator,
    )
    return parse_model(PregnancyChildbirthEditResponse, data)


async def pregnancy_childbirth_edit_async(
    self: AsyncService,
    *,
    medical_certnumber: str | None = None,
    company_id: int | None = None,
    lastname: str | None = None,
    firsthname: str | None = None,
    regnum: str | None = None,
    address: str | None = None,
    aimag_code: str | None = None,
    org_id: str | None = None,
    medical_cert_type_id: int | None = None,
    medical_cert_type_name: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    phone: str | None = None,
    created_date: str | None = None,
    updated_date: str | None = None,
    hospital_id: str | None = None,
    hospital_name: str | None = None,
    general_doctor_id: str | None = None,
    general_doctor_name: str | None = None,
    confirm_doctor_id: str | None = None,
    confirm_doctor_name: str | None = None,
    is_twins: bool | None = None,
    ehk_decision_number: str | None = None,
    pregnancy_period: str | None = None,
    history_number: str | None = None,
    counter_name: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> PregnancyChildbirthEditResponse:
    """WS100547_pregnancyChildbirthEdit: Жирэмсэн амаржсаны эмнэлгийн хуудас мэдээлэлд засвар хийх

    Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар

    Args:
        medical_certnumber: Эмнэлгийн хуудасны дугаар
        company_id: Эмнэлгийн хуудас бичих програм код
        lastname: Иргэний Эцэг /эх/-ийн нэр
        firsthname: Иргэний Нэр
        regnum: Иргэний регистрийн дугаар
        address: Иргэний хаяг
        aimag_code: Аж ахуйн нэгж байгууллагын Аймаг, дүүргийн код
        org_id: Аж ахуйн нэгж байгууллагын код
        medical_cert_type_id: Эмнэлгийн хуудасны төрлийн код
        medical_cert_type_name: Эмнэлгийн хуудасны төрлийн нэр
        start_date: Эхлэх огноо "yyyy-MM-dd"
        end_date: Дуусах огноо "yyyy-MM-dd"
        phone: утасны дугаар
        created_date: Эмнэлгийн хуудасны бичсэн огноо "yyyy-MM-dd"
        updated_date: Эмнэлгийн хуудасны зассан огноо "yyyy-MM-dd"
        hospital_id: Эмнэлгийн хуудас олгосон эмнэлгийн код
        hospital_name: Эмнэлгийн хуудас олгосон эмнэлгийн нэр
        general_doctor_id: Ерөнхий эмчийн код
        general_doctor_name: Ерөнхий эмчийн нэр
        confirm_doctor_id: Эмчлэгч эмчийн код
        confirm_doctor_name: Эмчлэгч эмчийн нэр
        is_twins: Ихэр хүүхэд мөн эсэх
        ehk_decision_number: Эмнэлэг хяналтын комисийн шийдвэрийн дугаар.
        pregnancy_period: Жирэмсний долоо хоног
        history_number: Өвчний түүхийн дугаар
        counter_name: Хэрэв гадаад улсад төрсөн бол улсын нэр
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "medicalCertnumber": medical_certnumber,
            "companyId": company_id,
            "lastname": lastname,
            "firsthname": firsthname,
            "regnum": regnum,
            "address": address,
            "aimagCode": aimag_code,
            "orgId": org_id,
            "medicalCertTypeId": medical_cert_type_id,
            "medicalCertTypeName": medical_cert_type_name,
            "startDate": start_date,
            "endDate": end_date,
            "phone": phone,
            "createdDate": created_date,
            "updatedDate": updated_date,
            "hospitalId": hospital_id,
            "hospitalName": hospital_name,
            "generalDoctorId": general_doctor_id,
            "generalDoctorName": general_doctor_name,
            "confirmDoctorId": confirm_doctor_id,
            "confirmDoctorName": confirm_doctor_name,
            "isTwins": is_twins,
            "ehkDecisionNumber": ehk_decision_number,
            "pregnancyPeriod": pregnancy_period,
            "historyNumber": history_number,
            "counterName": counter_name,
        },
        auth,
        operator,
    )
    return parse_model(PregnancyChildbirthEditResponse, data)
