// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.statistic;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS200127_citizenLivestockList}: Иргэний Мал, тэжээвэр амьтдын тооллогын
 * мэдээлэл дуудах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData мэдээллийн жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record CitizenLivestockListResponse(List<ListData> listData, Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static CitizenLivestockListResponse decode(ResponseReader reader) {
    return new CitizenLivestockListResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * мэдээллийн жагсаалт.
   *
   * @param livestockTypeName Малын төрөл нэр
   * @param total Бүгд мал
   * @param newbornSires Хээлтүүлэгч
   * @param newbornSiresNew Хээлтүүлэгч шинээр тавьсан
   * @param newbornThisYearMale Энэ жилийн төл мал эр
   * @param newbornThisYearFemale Энэ жилийн төл мал эм
   * @param newbornLastYearMale Өнгөрсөн жилийн төл мал эр
   * @param newbornLastYearFemale Өнгөрсөн жилийн төл мал эм
   * @param twoYearsOldMale 2 настай эр
   * @param twoYearsOldFemale 2 настай эм
   * @param threeYearsOldMale 3 настай эр
   * @param threeYearsOldFemale 3 настай эм
   * @param fourYearsOldMale 4 настай эр
   * @param fourYearsOldFemale 4 настай эм
   * @param fiveAndAboveYearsOldMale 5 ба түүнээс дээш настай эр
   * @param fiveAndAboveYearsOldFemale 5 ба түүнээс дээш настай эм
   * @param totalLastYear Оны эхэнд тоологдсон малын тоо
   * @param purchased Нэмэгдсэн: Худалдаж авсан
   * @param transferredIn Нэмэгдсэн: Шилжиж ирсэн
   * @param found Нэмэгдсэн: Алдсан, хулгайлагдсан, олдохгүй байсан малыг олсон
   * @param newborn Нэмэгдсэн: Бэлэн тоологдсон төл
   * @param sold Хасагдсан: Зах зээлд худалдаж, борлуулсан
   * @param transferredOut Хасагдсан: Шилжүүлсэн
   * @param lost Хасагдсан: Алдсан, хулгайлагдсан, олдохгүй байгаа
   * @param soldForSlaughter Хасагдсан: Хүнсэнд хэрэглэсэн
   * @param lossesAdultAnimals Хасагдсан: Зүй бусаар хорогдсон
   * @param naturalDisaster Хасагдсан: Үүнээс - Аюулт үзэгдлээр
   * @param dicease Хасагдсан: Үүнээс - Өвчнөөр
   * @param attackedByWildAnimals Хасагдсан: Үүнээс - Зэрлэг амьтанд бариулсан
   * @param other Хасагдсан: Үүнээс- Бусад
   */
  public record ListData(
      Object livestockTypeName,
      Object total,
      Object newbornSires,
      Object newbornSiresNew,
      Object newbornThisYearMale,
      Object newbornThisYearFemale,
      Object newbornLastYearMale,
      Object newbornLastYearFemale,
      Object twoYearsOldMale,
      Object twoYearsOldFemale,
      Object threeYearsOldMale,
      Object threeYearsOldFemale,
      Object fourYearsOldMale,
      Object fourYearsOldFemale,
      Object fiveAndAboveYearsOldMale,
      Object fiveAndAboveYearsOldFemale,
      Object totalLastYear,
      Object purchased,
      Object transferredIn,
      Object found,
      Object newborn,
      Object sold,
      Object transferredOut,
      Object lost,
      Object soldForSlaughter,
      Object lossesAdultAnimals,
      Object naturalDisaster,
      Object dicease,
      Object attackedByWildAnimals,
      Object other) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("livestockTypeName", Decoders.ANY),
          reader.get("total", Decoders.ANY),
          reader.get("newbornSires", Decoders.ANY),
          reader.get("newbornSiresNew", Decoders.ANY),
          reader.get("newbornThisYearMale", Decoders.ANY),
          reader.get("newbornThisYearFemale", Decoders.ANY),
          reader.get("newbornLastYearMale", Decoders.ANY),
          reader.get("newbornLastYearFemale", Decoders.ANY),
          reader.get("twoYearsOldMale", Decoders.ANY),
          reader.get("twoYearsOldFemale", Decoders.ANY),
          reader.get("threeYearsOldMale", Decoders.ANY),
          reader.get("threeYearsOldFemale", Decoders.ANY),
          reader.get("fourYearsOldMale", Decoders.ANY),
          reader.get("fourYearsOldFemale", Decoders.ANY),
          reader.get("fiveAndAboveYearsOldMale", Decoders.ANY),
          reader.get("fiveAndAboveYearsOldFemale", Decoders.ANY),
          reader.get("totalLastYear", Decoders.ANY),
          reader.get("purchased", Decoders.ANY),
          reader.get("transferredIn", Decoders.ANY),
          reader.get("found", Decoders.ANY),
          reader.get("newborn", Decoders.ANY),
          reader.get("sold", Decoders.ANY),
          reader.get("transferredOut", Decoders.ANY),
          reader.get("lost", Decoders.ANY),
          reader.get("soldForSlaughter", Decoders.ANY),
          reader.get("lossesAdultAnimals", Decoders.ANY),
          reader.get("naturalDisaster", Decoders.ANY),
          reader.get("dicease", Decoders.ANY),
          reader.get("attackedByWildAnimals", Decoders.ANY),
          reader.get("other", Decoders.ANY));
    }
  }
}
