// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.statistic;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import io.github.baljinnyamday.xyp.XypDate;

/**
 * The response of {@code WS200114_citizenStatisticInfo}: Иргэний мэдээлэл.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param regnum Регистр
 * @param surname Ургийн овог
 * @param lastname Овог
 * @param firstname Нэр
 * @param gender Хүйс
 * @param birthdate Төрсөн огноо
 * @param originName Үндэстэн
 * @param maritalStatusName Гэрлэлт
 * @param nationalityName Үндэс, угсаа
 * @param educationName Боловсрол
 * @param careerTypeName Мэргэжил
 * @param professionName Ажил эрхлэлт
 * @param cityName Аймаг, нийслэл
 * @param districtName Сум, дүүрэг
 * @param khorooName Баг, хороо
 * @param regionName Хотхон
 * @param townName Хороолол
 * @param streetName Гудамж
 * @param apartmentName Байр
 * @param detail Тоот
 * @param civilStatusName Төлөв
 * @param photo зураг
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record CitizenStatisticInfoResponse(
    String regnum,
    String surname,
    String lastname,
    String firstname,
    String gender,
    XypDate birthdate,
    String originName,
    String maritalStatusName,
    String nationalityName,
    String educationName,
    String careerTypeName,
    String professionName,
    String cityName,
    String districtName,
    String khorooName,
    String regionName,
    String townName,
    String streetName,
    String apartmentName,
    String detail,
    String civilStatusName,
    byte[] photo,
    Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static CitizenStatisticInfoResponse decode(ResponseReader reader) {
    return new CitizenStatisticInfoResponse(
        reader.get("regnum", Decoders.STRING),
        reader.get("surname", Decoders.STRING),
        reader.get("lastname", Decoders.STRING),
        reader.get("firstname", Decoders.STRING),
        reader.get("gender", Decoders.STRING),
        reader.get("birthdate", Decoders.DATE),
        reader.get("originName", Decoders.STRING),
        reader.get("maritalStatusName", Decoders.STRING),
        reader.get("nationalityName", Decoders.STRING),
        reader.get("educationName", Decoders.STRING),
        reader.get("careerTypeName", Decoders.STRING),
        reader.get("professionName", Decoders.STRING),
        reader.get("cityName", Decoders.STRING),
        reader.get("districtName", Decoders.STRING),
        reader.get("khorooName", Decoders.STRING),
        reader.get("regionName", Decoders.STRING),
        reader.get("townName", Decoders.STRING),
        reader.get("streetName", Decoders.STRING),
        reader.get("apartmentName", Decoders.STRING),
        reader.get("detail", Decoders.STRING),
        reader.get("civilStatusName", Decoders.STRING),
        reader.get("photo", Decoders.BYTES),
        reader.extras());
  }
}
