// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.statistic;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS200118_legalEntityLivestockInfo}: Хуулийн этгээдийн эзэмшлийн малын тоо
 * мэдээлэл авах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param cityName аймгийн нэр
 * @param year жил
 * @param districtName сумын нэр
 * @param bagName багийн нэр
 * @param legalEntityRegnum хуулийн этгээдийн регистрийн дугаар
 * @param legalEntityName хуулийн этгээдийн нэр
 * @param camelCount тэмээний тоо
 * @param horseCount морины тоо
 * @param cowCount үхрийн тоо
 * @param sheepCount хонины тоо
 * @param goatCount ямааны тоо
 * @param totalCount нийт малын тоо
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record LegalEntityLivestockInfoResponse(
    String cityName,
    Long year,
    String districtName,
    String bagName,
    String legalEntityRegnum,
    String legalEntityName,
    Long camelCount,
    Long horseCount,
    Long cowCount,
    Long sheepCount,
    Long goatCount,
    Long totalCount,
    Extras extras) {

  static LegalEntityLivestockInfoResponse decode(ResponseReader reader) {
    return new LegalEntityLivestockInfoResponse(
        reader.get("cityName", Decoders.STRING),
        reader.get("year", Decoders.INT),
        reader.get("districtName", Decoders.STRING),
        reader.get("bagName", Decoders.STRING),
        reader.get("legalEntityRegnum", Decoders.STRING),
        reader.get("legalEntityName", Decoders.STRING),
        reader.get("camelCount", Decoders.INT),
        reader.get("horseCount", Decoders.INT),
        reader.get("cowCount", Decoders.INT),
        reader.get("sheepCount", Decoders.INT),
        reader.get("goatCount", Decoders.INT),
        reader.get("totalCount", Decoders.INT),
        reader.extras());
  }
}
