// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package laborwelfare

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// HouseholdScoreCheckInfoParams is the input of WS100928_householdScoreCheckInfo. Every field is
// optional; a zero value is left out of the request.
type HouseholdScoreCheckInfoParams struct {
	// регистрийн дугаар
	Regnum string `xyp:"regnum"`
}

// HouseholdScoreCheckInfoResponse is the response of WS100928_householdScoreCheckInfo: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээсэн эсэхийг шалгах.
type HouseholdScoreCheckInfoResponse struct {
	// Иргэний регистрийн дугаар
	Regnum string `xyp:"regnum"`
	// Ам бүлийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0
	IsMemberSize *int64 `xyp:"isMemberSize"`
	// Хүүхдийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0
	IsChildren *int64 `xyp:"isChildren"`
	// Үл хөдлөх хөрөнгийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0
	IsPropertyNum *int64 `xyp:"isPropertyNum"`
	// тээврийн хэрэгслийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0
	IsCarNum *int64 `xyp:"isCarNum"`
	// малын тоогоо шалгуулах эсэх тийм-1, үгүй-0
	IsLivestockNum *int64 `xyp:"isLivestockNum"`
	// цалингийн мэдээллээ шалгуулах эсэх тийм-1, үгүй-0
	IsSalary *int64 `xyp:"isSalary"`
	// татварын мэдээллээ шалгуулах эсэх тийм-1, үгүй-0
	IsPreTax *int64 `xyp:"isPreTax"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// HouseholdScoreCheckInfo calls WS100928_householdScoreCheckInfo: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээсэн эсэхийг шалгах
//
// Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
func (s *Service) HouseholdScoreCheckInfo(ctx context.Context, params HouseholdScoreCheckInfoParams, opts ...xyp.CallOption) (*HouseholdScoreCheckInfoResponse, error) {
	var out HouseholdScoreCheckInfoResponse
	extras, err := s.client.Invoke(ctx, "WS100928_householdScoreCheckInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
