<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Education;

/**
 * Input of WS400119_ForeignHigherEducationServiceOne: Гадаад улсад дээд боловсрол эзэмшсэн дэлгэрэнгүй мэдээлэл externalEducationId-гаар дуудах сервис.
 *
 * Provider: Боловсролын мэдээллийн технологийн Төв
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class ForeignHigherEducationServiceOneParams
{
    /**
     * @param string|null $externalEducationId Тухайн бичлэгийн давтагдахгүй дугаар
     */
    public function __construct(
        public ?string $externalEducationId = null,
    ) {}
}
