<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Education;

/**
 * Input of WS400104_sendKindergartenEnrollment: СӨБ Элсэлтийн бүртгэл илгээх.
 *
 * Provider: Боловсролын мэдээллийн технологийн Төв
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class SendKindergartenEnrollmentParams
{
    /**
     * @param int|null $civilId Хүүхдийн Бүртгэлийн дугаар
     * @param string|null $regnum Хүүхдийн Регистрийн дугаар
     * @param int|null $personId Хүний ID
     * @param string|null $lastName Эцэг/эх/-ийн нэр
     * @param string|null $firstName Нэр
     * @param \DateTimeInterface|string|null $birthDate Төрсөн огноо
     * @param int|null $addressId Хаягийн ID
     * @param string|null $cityCode Аймаг хотын код
     * @param string|null $cityName Аймаг хотын нэр
     * @param string|null $districtCode Сум, дүүргийн код
     * @param string|null $districtName Сум, дүүргийн нэр
     * @param string|null $khorooCode Баг, хорооны код
     * @param string|null $khorooName Баг, хорооны нэр
     * @param string|null $addressTypeCode Хаягийн төрлийн код
     * @param string|null $addressTypeName Хаягийн төрлийн нэр
     * @param int|null $addressRegionId Хорооллын ID
     * @param string|null $addressRegionName Хорооллын нэр
     * @param int|null $addressTownId Хотхоны ID
     * @param string|null $addressTownName Хотхоны нэр
     * @param int|null $addressApartmentId Байрны ID
     * @param string|null $addressApartmentName Байрны нэр
     * @param int|null $addressStreetId Гудамжны ID
     * @param string|null $addressStreetName Гудамжны нэр
     * @param string|null $addressDetail Хаягийн тоотын мэдээлэл
     * @param string|null $fullAddress Дэлгэрэнгүй хаяг
     * @param string|null $ubLocationFlag Нийслэлийн хаяг эсэх
     * @param \DateTimeInterface|string|null $arrivedDate Шилжилт хөдөлгөөний огноо
     * @param int|null $contactCivilId Эцэг, эхийн бүртгэлийн дугаар
     * @param string|null $contactRegnum Эцэг, эхийн регистрийн дугаар
     * @param int|null $contactPersonId Эцэг, эхийн хүний ID
     * @param string|null $contactGuardianType FATHER - Эцэг, MOTHER - Эх,RELATIVES - Төрөл садан, NURSING_HOME - Асрамжийн газарын хүмүүжүүлэгч, DORMITORY - Дотуур байрны хүмүүжүүлэгч, LEFT_WITHOUT_CARE - Асрамжлах хүнгүй, OTHER - Бусад
     * @param string|null $contactPhone Эцэг, эх, хүсэлт гаргагчийн утасны дугаар
     * @param string|null $requestStatus HOME - Гэртээ, OTHER - Бусад, ABROAD - Хилийн чанадад, CONTINUE - Хуучин цэцэрлэгтээ, CHANGE_ADDR - Хаягаа шилжүүлнэ, CHANGE_ORG - Цэцэрлэг солих
     * @param int|null $institutionId Боловсролын байгууллагын ID
     * @param string|null $institutionName Боловсролын байгууллагын нэр
     * @param string|null $recruiterFlag Е Mongolia орсон бол N Элсэлтийн комисс орсон бол Y
     * @param int|null $recruiterId Е Mongolia орсон бол хүний бүртгэлийн дугаар Элсэлтийн комисс орсон бол Хэрэглэгийн Дугаар
     */
    public function __construct(
        public ?int $civilId = null,
        public ?string $regnum = null,
        public ?int $personId = null,
        public ?string $lastName = null,
        public ?string $firstName = null,
        public \DateTimeInterface|string|null $birthDate = null,
        public ?int $addressId = null,
        public ?string $cityCode = null,
        public ?string $cityName = null,
        public ?string $districtCode = null,
        public ?string $districtName = null,
        public ?string $khorooCode = null,
        public ?string $khorooName = null,
        public ?string $addressTypeCode = null,
        public ?string $addressTypeName = null,
        public ?int $addressRegionId = null,
        public ?string $addressRegionName = null,
        public ?int $addressTownId = null,
        public ?string $addressTownName = null,
        public ?int $addressApartmentId = null,
        public ?string $addressApartmentName = null,
        public ?int $addressStreetId = null,
        public ?string $addressStreetName = null,
        public ?string $addressDetail = null,
        public ?string $fullAddress = null,
        public ?string $ubLocationFlag = null,
        public \DateTimeInterface|string|null $arrivedDate = null,
        public ?int $contactCivilId = null,
        public ?string $contactRegnum = null,
        public ?int $contactPersonId = null,
        public ?string $contactGuardianType = null,
        public ?string $contactPhone = null,
        public ?string $requestStatus = null,
        public ?int $institutionId = null,
        public ?string $institutionName = null,
        public ?string $recruiterFlag = null,
        public ?int $recruiterId = null,
    ) {}
}
