<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Education;

/**
 * Input of WS400101_ueeReferenceService: БОЛОВСРОЛЫН ҮНЭЛГЭЭНИЙ ТӨВ ЭЛСЭЛТИЙН ЕРӨНХИЙ ШАЛГАЛТЫН ЛАВЛАГАА.
 *
 * Provider: Боловсрол шинжлэх ухааны яам
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class UeeReferenceServiceParams
{
    /**
     * @param string|null $regnum регистрийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
