/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS100842_orgenzationLoanInfoTitan (payment, Титан си ар эй зээлийн мэдээллийн сан)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS100842_orgenzationLoanInfoTitan";

/** Input of WS100842_orgenzationLoanInfoTitan. */
export interface OrgenzationLoanInfoTitanParams {
  /** байгууллагын регистр */
  readonly legalEntityNumber?: string;
}

/** Жагсаалт */
export interface OrgenzationLoanInfoTitanMain {
  /** Үндсэн зээлдэгч Нийт зээлийн тоо */
  readonly total: number | null;
  /** Үндсэн зээлдэгч Хэвийн зээлийн тоо */
  readonly normal: number | null;
  /** Үндсэн зээлдэгч Анхаарал хандуулах зээлийн тоо */
  readonly attention: number | null;
  /** Үндсэн зээлдэгч Чанаргүй зээлийн тоо */
  readonly notQuality: number | null;
}

export interface OrgenzationLoanInfoTitanRell {
  /** Үндсэн зээлдэгч Нийт зээлийн тоо */
  readonly total: number | null;
  /** Үндсэн зээлдэгч Хэвийн зээлийн тоо */
  readonly normal: number | null;
  /** Үндсэн зээлдэгч Анхаарал хандуулах зээлийн тоо */
  readonly attention: number | null;
  /** Үндсэн зээлдэгч Чанаргүй зээлийн тоо */
  readonly notQuality: number | null;
}

/** WS100842_orgenzationLoanInfoTitan: Монгол улсын байгууллагын зээлийн мэдээллийг авах сервис */
export interface OrgenzationLoanInfoTitanResponse {
  /** Жагсаалт */
  readonly main: readonly OrgenzationLoanInfoTitanMain[] | null;
  readonly rell: readonly OrgenzationLoanInfoTitanRell[] | null;
  /** Өр төлбөртэй эсэх, 0-төлбөргүй, 1-төлбөртэй */
  readonly is_liabilities: number | null;
}

const SCHEMA: Schema = { main: { list: { object: { total: "int", normal: "int", attention: "int", notQuality: "int" } } }, rell: { list: { object: { total: "int", normal: "int", attention: "int", notQuality: "int" } } }, is_liabilities: "int" };

/**
 * WS100842_orgenzationLoanInfoTitan: Монгол улсын байгууллагын зээлийн мэдээллийг авах сервис
 *
 * Provider: Титан си ар эй зээлийн мэдээллийн сан
 */
export async function orgenzationLoanInfoTitan(transport: Transport, params: OrgenzationLoanInfoTitanParams = {}, options: CallOptions = {}): Promise<XypResult<OrgenzationLoanInfoTitanResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      legalEntityNumber: params.legalEntityNumber,
    },
    options,
  );
  return decodeResponse<OrgenzationLoanInfoTitanResponse>("OrgenzationLoanInfoTitanResponse", SCHEMA, data);
}
