<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\LegalEntity;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of WS100343_CopyOfTheLegalEntityCert: Хуулийн итгээдийн гэрчилгээ хуулбар.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class CopyOfTheLegalEntityCertResponse
{
    /**
     * @param list<mixed> $list
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        #[ListOf('any')]
        public array $list = [],
        public Extras $xyp = new Extras(),
    ) {}
}
