<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\LegalEntity;

/**
 * Захирлын мэдээлэл
 *
 * `generalR` in the response of WS100301_getLegalEntityInfo.
 */
final readonly class GetLegalEntityInfoGeneralR
{
    /**
     * @param string|null $registeredNumber Бүртгэлийн дугаар
     */
    public function __construct(
        public ?string $registeredNumber = null,
    ) {}
}
