<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\LegalEntity;

/**
 * Input of WS100340_getTradeServiceLicenseCitizen: Иргэний худалдаа, үйлчилгээ эрхлэх бүртгэл шалгах сервис.
 *
 * Provider: Нийслэлийн засаг даргын тамгын газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class GetTradeServiceLicenseCitizenParams
{
    /**
     * @param string|null $regnum регистрийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
