<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\LegalEntity;

use Xyp\Extras;

/**
 * Response of WS100330_liquidationInfoService: Татан буугдсан хуулийн этгээдийн мэдээлэл.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class LiquidationInfoServiceResponse
{
    /**
     * @param string|null $companyRegnum Хуулийн этгээдийн регистрийн дугаар
     * @param string|null $companyName Оноосон нэр
     * @param string|null $decisionDate Татан буугдсан тухай шийдвэрийн огноо
     * @param string|null $decisionNumber Татан буугдсан тухай шийдвэрийн дугаар
     * @param string|null $newspaperName Хэвлэл мэдээллийн хэрэгслээр зарлуулсан сонингийн нэр
     * @param string|null $newspaperNumber Хэвлэл мэдээллийн хэрэгслээр зарлуулсан сонингийн дугаар
     * @param string|null $newspaperPrintedDate Хэвлэл мэдээллийн хэрэгслээр зарлуулсан сонингийн огноо
     * @param string|null $createdUserName Бүртгэсэн ажилтан
     * @param string|null $createdDate Бүртгэсэн огноо
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $companyRegnum = null,
        public ?string $companyName = null,
        public ?string $decisionDate = null,
        public ?string $decisionNumber = null,
        public ?string $newspaperName = null,
        public ?string $newspaperNumber = null,
        public ?string $newspaperPrintedDate = null,
        public ?string $createdUserName = null,
        public ?string $createdDate = null,
        public Extras $xyp = new Extras(),
    ) {}
}
