// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.foreignservice;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link ForeignServiceClient#getBorderCrossingInfo}, XYP operation {@code
 * FS100111_getBorderCrossingInfo}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GetBorderCrossingInfoParams implements RequestParams {
  private final String fregistryNumber;
  private final String firstName;
  private final String lastName;
  private final String birthDate;
  private final String citizenShip;
  private final String gender;
  private final String direction;
  private final String crossedDate;
  private final String portCode;
  private final String approvalNumber;
  private final String passportNumber;
  private final Boolean back;
  private final String travelNumber;
  private final String travelPurpose;

  private GetBorderCrossingInfoParams(Builder builder) {
    this.fregistryNumber = builder.fregistryNumber;
    this.firstName = builder.firstName;
    this.lastName = builder.lastName;
    this.birthDate = builder.birthDate;
    this.citizenShip = builder.citizenShip;
    this.gender = builder.gender;
    this.direction = builder.direction;
    this.crossedDate = builder.crossedDate;
    this.portCode = builder.portCode;
    this.approvalNumber = builder.approvalNumber;
    this.passportNumber = builder.passportNumber;
    this.back = builder.back;
    this.travelNumber = builder.travelNumber;
    this.travelPurpose = builder.travelPurpose;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Фрегистр.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String fregistryNumber() {
    return fregistryNumber;
  }

  /**
   * Нэр.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String firstName() {
    return firstName;
  }

  /**
   * Овог.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String lastName() {
    return lastName;
  }

  /**
   * Төрсөн огноо.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String birthDate() {
    return birthDate;
  }

  /**
   * Иргэншил.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String citizenShip() {
    return citizenShip;
  }

  /**
   * Хүйс.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String gender() {
    return gender;
  }

  /**
   * Хил нэвтэрсэн чиглэл.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String direction() {
    return direction;
  }

  /**
   * Хил нэвтэрсэн огноо.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String crossedDate() {
    return crossedDate;
  }

  /**
   * Боомтын код.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String portCode() {
    return portCode;
  }

  /**
   * Зөвшөөрлийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String approvalNumber() {
    return approvalNumber;
  }

  /**
   * Паспортын дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String passportNumber() {
    return passportNumber;
  }

  /**
   * Буцсан эсэх.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Boolean back() {
    return back;
  }

  /**
   * Аялалын дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String travelNumber() {
    return travelNumber;
  }

  /**
   * Аялалын зорилго.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String travelPurpose() {
    return travelPurpose;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("fregistryNumber", fregistryNumber)
        .add("firstName", firstName)
        .add("lastName", lastName)
        .add("birthDate", birthDate)
        .add("citizenShip", citizenShip)
        .add("gender", gender)
        .add("direction", direction)
        .add("crossedDate", crossedDate)
        .add("portCode", portCode)
        .add("approvalNumber", approvalNumber)
        .add("passportNumber", passportNumber)
        .add("back", back)
        .add("travelNumber", travelNumber)
        .add("travelPurpose", travelPurpose)
        .build();
  }

  /**
   * Builds a {@link GetBorderCrossingInfoParams}. Every setter accepts {@code null}, which leaves
   * the field out of the request. A builder is not thread-safe; it can be reused, and setting a
   * field again does not change the params it has already built.
   */
  public static final class Builder {
    private String fregistryNumber;
    private String firstName;
    private String lastName;
    private String birthDate;
    private String citizenShip;
    private String gender;
    private String direction;
    private String crossedDate;
    private String portCode;
    private String approvalNumber;
    private String passportNumber;
    private Boolean back;
    private String travelNumber;
    private String travelPurpose;

    private Builder() {}

    /**
     * Фрегистр.
     *
     * @param fregistryNumber the value, or {@code null}
     * @return this builder
     */
    public Builder fregistryNumber(String fregistryNumber) {
      this.fregistryNumber = fregistryNumber;
      return this;
    }

    /**
     * Нэр.
     *
     * @param firstName the value, or {@code null}
     * @return this builder
     */
    public Builder firstName(String firstName) {
      this.firstName = firstName;
      return this;
    }

    /**
     * Овог.
     *
     * @param lastName the value, or {@code null}
     * @return this builder
     */
    public Builder lastName(String lastName) {
      this.lastName = lastName;
      return this;
    }

    /**
     * Төрсөн огноо.
     *
     * @param birthDate the value, or {@code null}
     * @return this builder
     */
    public Builder birthDate(String birthDate) {
      this.birthDate = birthDate;
      return this;
    }

    /**
     * Иргэншил.
     *
     * @param citizenShip the value, or {@code null}
     * @return this builder
     */
    public Builder citizenShip(String citizenShip) {
      this.citizenShip = citizenShip;
      return this;
    }

    /**
     * Хүйс.
     *
     * @param gender the value, or {@code null}
     * @return this builder
     */
    public Builder gender(String gender) {
      this.gender = gender;
      return this;
    }

    /**
     * Хил нэвтэрсэн чиглэл.
     *
     * @param direction the value, or {@code null}
     * @return this builder
     */
    public Builder direction(String direction) {
      this.direction = direction;
      return this;
    }

    /**
     * Хил нэвтэрсэн огноо.
     *
     * @param crossedDate the value, or {@code null}
     * @return this builder
     */
    public Builder crossedDate(String crossedDate) {
      this.crossedDate = crossedDate;
      return this;
    }

    /**
     * Боомтын код.
     *
     * @param portCode the value, or {@code null}
     * @return this builder
     */
    public Builder portCode(String portCode) {
      this.portCode = portCode;
      return this;
    }

    /**
     * Зөвшөөрлийн дугаар.
     *
     * @param approvalNumber the value, or {@code null}
     * @return this builder
     */
    public Builder approvalNumber(String approvalNumber) {
      this.approvalNumber = approvalNumber;
      return this;
    }

    /**
     * Паспортын дугаар.
     *
     * @param passportNumber the value, or {@code null}
     * @return this builder
     */
    public Builder passportNumber(String passportNumber) {
      this.passportNumber = passportNumber;
      return this;
    }

    /**
     * Буцсан эсэх.
     *
     * @param back the value, or {@code null}
     * @return this builder
     */
    public Builder back(Boolean back) {
      this.back = back;
      return this;
    }

    /**
     * Аялалын дугаар.
     *
     * @param travelNumber the value, or {@code null}
     * @return this builder
     */
    public Builder travelNumber(String travelNumber) {
      this.travelNumber = travelNumber;
      return this;
    }

    /**
     * Аялалын зорилго.
     *
     * @param travelPurpose the value, or {@code null}
     * @return this builder
     */
    public Builder travelPurpose(String travelPurpose) {
      this.travelPurpose = travelPurpose;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GetBorderCrossingInfoParams}
     */
    public GetBorderCrossingInfoParams build() {
      return new GetBorderCrossingInfoParams(this);
    }
  }
}
