<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\ForeignService;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of FS100112_newExecutiveManagementRegistrationVerification: Гадаадын иргэн харьяат Гүйцэтгэх удирдлага шинээр бүртгэгдсэн тухай лавлагааны сервис.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class NewExecutiveManagementRegistrationVerificationResponse
{
    /**
     * @param list<NewExecutiveManagementRegistrationVerificationList> $list Жагсаалт
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        #[ListOf(NewExecutiveManagementRegistrationVerificationList::class)]
        public array $list = [],
        public Extras $xyp = new Extras(),
    ) {}
}
