/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS100541_healthInsuranceInfo (insurance, Нийгмийн даатгалын ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS100541_healthInsuranceInfo";

/** Input of WS100541_healthInsuranceInfo. */
export interface HealthInsuranceInfoParams {
  /** Регистрийн дугаар */
  readonly regnum?: string;
  /** Эхний огноо */
  readonly startDate?: Date | string;
  /** Сүүлийн огноо */
  readonly endDate?: Date | string;
}

/** мэдээллийн жагсаалт */
export interface HealthInsuranceInfoListData {
  /** Аймаг, дүүргийн нэр */
  readonly province: string | null;
  /** Эхлэх огноо */
  readonly startDate: Date | string | null;
  /** Дуусах огноо */
  readonly endDate: Date | string | null;
  /** Даатгуулагчийн төрөл */
  readonly benClass: string | null;
  /** ЭМД-д даатгуулсан хэлбэр */
  readonly feeType: string | null;
  /** Бүртгэсэн огноо */
  readonly regDate: Date | string | null;
}

/** WS100541_healthInsuranceInfo: Эрүүл мэндийн даатгалд хамрагдсан мэдээлэл */
export interface HealthInsuranceInfoResponse {
  /** мэдээллийн жагсаалт */
  readonly listData: readonly HealthInsuranceInfoListData[] | null;
}

const SCHEMA: Schema = { listData: { list: { object: { province: "string", startDate: "date", endDate: "date", benClass: "string", feeType: "string", regDate: "date" } } } };

/**
 * WS100541_healthInsuranceInfo: Эрүүл мэндийн даатгалд хамрагдсан мэдээлэл
 *
 * Provider: Нийгмийн даатгалын ерөнхий газар
 */
export async function healthInsuranceInfo(transport: Transport, params: HealthInsuranceInfoParams = {}, options: CallOptions = {}): Promise<XypResult<HealthInsuranceInfoResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
      startDate: params.startDate,
      endDate: params.endDate,
    },
    options,
  );
  return decodeResponse<HealthInsuranceInfoResponse>("HealthInsuranceInfoResponse", SCHEMA, data);
}
