/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS100559_refundHalfBankList (insurance, Нийгмийн даатгалын ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS100559_refundHalfBankList";

/** Input of WS100559_refundHalfBankList. */
export interface RefundHalfBankListParams {
  /** Регистрийн дугаар */
  readonly regnum?: string;
}

/** WS100559_refundHalfBankList: 50%-н буцаалт. Банкны жагсаалт */
export interface RefundHalfBankListResponse {
  /** мэдээллийн жагсаалт */
  readonly listData: readonly unknown[] | null;
}

const SCHEMA: Schema = { listData: { list: "any" } };

/**
 * WS100559_refundHalfBankList: 50%-н буцаалт. Банкны жагсаалт
 *
 * Provider: Нийгмийн даатгалын ерөнхий газар
 */
export async function refundHalfBankList(transport: Transport, params: RefundHalfBankListParams = {}, options: CallOptions = {}): Promise<XypResult<RefundHalfBankListResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<RefundHalfBankListResponse>("RefundHalfBankListResponse", SCHEMA, data);
}
