/** GENERATED by xyp-generator from spec/services.json. Do not edit. */

export type * as citizen from "./citizen.js";
export type * as education from "./education.js";
export type * as foreignService from "./foreignService.js";
export type * as governmentService from "./governmentService.js";
export type * as health from "./health.js";
export type * as insurance from "./insurance.js";
export type * as laborWelfare from "./laborWelfare.js";
export type * as legalEntity from "./legalEntity.js";
export type * as meta from "./meta.js";
export type * as payment from "./payment.js";
export type * as pki from "./pki.js";
export type * as privateService from "./privateService.js";
export type * as property from "./property.js";
export type * as statistic from "./statistic.js";
export type * as tax from "./tax.js";
export type * as transport from "./transport.js";
