<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Meta;

/**
 * Input of WS100013_authServiceCheckByOtp: Иргэний зөвшөөрлийг шалгах сервис.
 *
 * Provider: E-Mongolia
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class AuthServiceCheckByOtpParams
{
    /**
     * @param string|null $regnum регистрийн дугаар
     * @param string|null $otp нэг удаагийн нууц үг
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $otp = null,
    ) {}
}
