// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package transport

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// GetVehicleInspectionDataByPlateNoParams is the input of WS100432_getVehicleInspectionDataByPlateNo. Every field is
// optional; a zero value is left out of the request.
type GetVehicleInspectionDataByPlateNoParams struct {
	// тээврийн хэрэгслийн улсын дугаар
	PlateNo string `xyp:"plateNo"`
}

// GetVehicleInspectionDataByPlateNoListData: мэдээлийн жагсаалт
type GetVehicleInspectionDataByPlateNoListData struct {
	// тээврийн хэрэгслийн улсын дугаар
	PlateNo string `xyp:"plateNo"`
	// шалгалтын огноо
	InspectionDate string `xyp:"inspectionDate"`
	// дуусах огноо
	ExpireDate string `xyp:"expireDate"`
	// хяналтын үзлэгийн дүгнэлтийн хуудас
	ReportUrl string `xyp:"reportUrl"`
}

// GetVehicleInspectionDataByPlateNoResponse is the response of WS100432_getVehicleInspectionDataByPlateNo: Техникийн хяналтын мэдээллийг тээврийн хэрэгслийн улсын дугаараар шалгах.
type GetVehicleInspectionDataByPlateNoResponse struct {
	// мэдээлийн жагсаалт
	ListData []GetVehicleInspectionDataByPlateNoListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// GetVehicleInspectionDataByPlateNo calls WS100432_getVehicleInspectionDataByPlateNo: Техникийн хяналтын мэдээллийг тээврийн хэрэгслийн улсын дугаараар шалгах
//
// Provider: Авто тээврийн үндэсний төв
func (s *Service) GetVehicleInspectionDataByPlateNo(ctx context.Context, params GetVehicleInspectionDataByPlateNoParams, opts ...xyp.CallOption) (*GetVehicleInspectionDataByPlateNoResponse, error) {
	var out GetVehicleInspectionDataByPlateNoResponse
	extras, err := s.client.Invoke(ctx, "WS100432_getVehicleInspectionDataByPlateNo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
