// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.governmentservice;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link GovernmentServiceClient#getElectoralStationInfo}, XYP operation {@code
 * GS10042_getElectoralStationInfo}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GetElectoralStationInfoParams implements RequestParams {
  private final String orgCode;
  private final String orgName;
  private final String orgPassword;
  private final String orgToken;
  private final String roundNum;
  private final String electionDate;

  private GetElectoralStationInfoParams(Builder builder) {
    this.orgCode = builder.orgCode;
    this.orgName = builder.orgName;
    this.orgPassword = builder.orgPassword;
    this.orgToken = builder.orgToken;
    this.roundNum = builder.roundNum;
    this.electionDate = builder.electionDate;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the {@code orgCode} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgCode() {
    return orgCode;
  }

  /**
   * Returns the {@code orgName} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgName() {
    return orgName;
  }

  /**
   * Returns the {@code orgPassword} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgPassword() {
    return orgPassword;
  }

  /**
   * Returns the {@code orgToken} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String orgToken() {
    return orgToken;
  }

  /**
   * Returns the {@code roundNum} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String roundNum() {
    return roundNum;
  }

  /**
   * Returns the {@code electionDate} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String electionDate() {
    return electionDate;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("orgCode", orgCode)
        .add("orgName", orgName)
        .add("orgPassword", orgPassword)
        .add("orgToken", orgToken)
        .add("roundNum", roundNum)
        .add("electionDate", electionDate)
        .build();
  }

  /**
   * Builds a {@link GetElectoralStationInfoParams}. Every setter accepts {@code null}, which leaves
   * the field out of the request. A builder is not thread-safe; it can be reused, and setting a
   * field again does not change the params it has already built.
   */
  public static final class Builder {
    private String orgCode;
    private String orgName;
    private String orgPassword;
    private String orgToken;
    private String roundNum;
    private String electionDate;

    private Builder() {}

    /**
     * Sets the {@code orgCode} field.
     *
     * @param orgCode the value, or {@code null}
     * @return this builder
     */
    public Builder orgCode(String orgCode) {
      this.orgCode = orgCode;
      return this;
    }

    /**
     * Sets the {@code orgName} field.
     *
     * @param orgName the value, or {@code null}
     * @return this builder
     */
    public Builder orgName(String orgName) {
      this.orgName = orgName;
      return this;
    }

    /**
     * Sets the {@code orgPassword} field.
     *
     * @param orgPassword the value, or {@code null}
     * @return this builder
     */
    public Builder orgPassword(String orgPassword) {
      this.orgPassword = orgPassword;
      return this;
    }

    /**
     * Sets the {@code orgToken} field.
     *
     * @param orgToken the value, or {@code null}
     * @return this builder
     */
    public Builder orgToken(String orgToken) {
      this.orgToken = orgToken;
      return this;
    }

    /**
     * Sets the {@code roundNum} field.
     *
     * @param roundNum the value, or {@code null}
     * @return this builder
     */
    public Builder roundNum(String roundNum) {
      this.roundNum = roundNum;
      return this;
    }

    /**
     * Sets the {@code electionDate} field.
     *
     * @param electionDate the value, or {@code null}
     * @return this builder
     */
    public Builder electionDate(String electionDate) {
      this.electionDate = electionDate;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GetElectoralStationInfoParams}
     */
    public GetElectoralStationInfoParams build() {
      return new GetElectoralStationInfoParams(this);
    }
  }
}
