// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.governmentservice;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import io.github.baljinnyamday.xyp.XypDate;

/**
 * The response of {@code GS10020_nonAdultCitizenInfo}: Насанд хүрээгүй иргэний мэдээлэл авах.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param momCivilId эхийн иргэний бүртгэлийн дугаар
 * @param momRegnum эхийн регистрийн дугаар
 * @param momLastname эхийн овог
 * @param momFirstName эхийн нэр
 * @param momAimagCityCode эхийн аймаг/ нийслэлийн дугаар
 * @param momAimagCityName эхийн аймаг /нийслэлийн нэр
 * @param momSoumDistrictCode эхийн сум/дүүргийн код
 * @param momSoumDistrictName эхийн сум/дүүргийн нэр
 * @param momFullAddress эхийн дэлгэрэнгүй хаяг
 * @param birthweek төрөх үеийн хугацаа
 * @param birthPlaceCode төрсөн газрын дугаар
 * @param birthPlaceName төрсөн газрын нэр
 * @param birthTypeName төрөлтийн төрөл
 * @param birthDate төрсөн өдөр
 * @param birthTime төрсөн цаг
 * @param isAlive амьд эсэх
 * @param isTwin ихэр эсэх код
 * @param isTwinName ихэр эсэх
 * @param sexCode хүйсийн дугаар
 * @param sexName хүйсийн нэр
 * @param birthWeight хүүхдийн жин
 * @param birthHeight хүүхдийн өндөр
 * @param birthTCircle толгойн бүслүүр
 * @param birthNCircle мөрний бүслүүр
 * @param birthAimagCityCode төрсөн аймаг/ нийслэлийн дугаар
 * @param birthSoumDistrictCode төрсөн сум/дүүргийн дугаар
 * @param childRegisterNum хүүхдийн регистр
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record NonAdultCitizenInfoResponse(
    Long momCivilId,
    String momRegnum,
    String momLastname,
    String momFirstName,
    String momAimagCityCode,
    String momAimagCityName,
    String momSoumDistrictCode,
    String momSoumDistrictName,
    String momFullAddress,
    String birthweek,
    String birthPlaceCode,
    String birthPlaceName,
    String birthTypeName,
    XypDate birthDate,
    String birthTime,
    Long isAlive,
    String isTwin,
    String isTwinName,
    String sexCode,
    String sexName,
    String birthWeight,
    String birthHeight,
    String birthTCircle,
    String birthNCircle,
    String birthAimagCityCode,
    String birthSoumDistrictCode,
    String childRegisterNum,
    Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static NonAdultCitizenInfoResponse decode(ResponseReader reader) {
    return new NonAdultCitizenInfoResponse(
        reader.get("momCivilId", Decoders.INT),
        reader.get("momRegnum", Decoders.STRING),
        reader.get("momLastname", Decoders.STRING),
        reader.get("momFirstName", Decoders.STRING),
        reader.get("momAimagCityCode", Decoders.STRING),
        reader.get("momAimagCityName", Decoders.STRING),
        reader.get("momSoumDistrictCode", Decoders.STRING),
        reader.get("momSoumDistrictName", Decoders.STRING),
        reader.get("momFullAddress", Decoders.STRING),
        reader.get("birthweek", Decoders.STRING),
        reader.get("birthPlaceCode", Decoders.STRING),
        reader.get("birthPlaceName", Decoders.STRING),
        reader.get("birthTypeName", Decoders.STRING),
        reader.get("birthDate", Decoders.DATE),
        reader.get("birthTime", Decoders.STRING),
        reader.get("isAlive", Decoders.INT),
        reader.get("isTwin", Decoders.STRING),
        reader.get("isTwinName", Decoders.STRING),
        reader.get("sexCode", Decoders.STRING),
        reader.get("sexName", Decoders.STRING),
        reader.get("birthWeight", Decoders.STRING),
        reader.get("birthHeight", Decoders.STRING),
        reader.get("birthTCircle", Decoders.STRING),
        reader.get("birthNCircle", Decoders.STRING),
        reader.get("birthAimagCityCode", Decoders.STRING),
        reader.get("birthSoumDistrictCode", Decoders.STRING),
        reader.get("childRegisterNum", Decoders.STRING),
        reader.extras());
  }
}
