// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.governmentservice;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code GS10085_RiskReferenceService}: Эрсдлийн лавлах сан.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param envs Эрсдлийн орчин
 * @param types Эрсдлийн төрөл
 * @param ctypes Эрсдэл бүртгэгч (хувь хүн, байгууллага)
 * @param status Эрсдлийн төлөв
 * @param risks risks - Эрсдлийн жагсаалт харах
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record RiskReferenceServiceResponse(
    List<Envs> envs,
    List<Types> types,
    List<Ctypes> ctypes,
    List<Status> status,
    List<Risks> risks,
    Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static RiskReferenceServiceResponse decode(ResponseReader reader) {
    return new RiskReferenceServiceResponse(
        reader.get("envs", Decoders.list(Decoders.object(Envs::decode))),
        reader.get("types", Decoders.list(Decoders.object(Types::decode))),
        reader.get("ctypes", Decoders.list(Decoders.object(Ctypes::decode))),
        reader.get("status", Decoders.list(Decoders.object(Status::decode))),
        reader.get("risks", Decoders.list(Decoders.object(Risks::decode))),
        reader.extras());
  }

  /**
   * Эрсдлийн орчин.
   *
   * @param publicId the {@code publicId} field
   * @param id the {@code id} field
   * @param title the {@code title} field
   */
  public record Envs(String publicId, String id, String title) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static Envs decode(ResponseReader reader) {
      return new Envs(
          reader.get("publicId", Decoders.STRING),
          reader.get("id", Decoders.STRING),
          reader.get("title", Decoders.STRING));
    }
  }

  /**
   * Эрсдлийн төрөл.
   *
   * @param id the {@code id} field
   * @param publicId the {@code publicId} field
   * @param title the {@code title} field
   */
  public record Types(String id, String publicId, String title) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static Types decode(ResponseReader reader) {
      return new Types(
          reader.get("id", Decoders.STRING),
          reader.get("publicId", Decoders.STRING),
          reader.get("title", Decoders.STRING));
    }
  }

  /**
   * Эрсдэл бүртгэгч (хувь хүн, байгууллага).
   *
   * @param id the {@code id} field
   * @param publicId the {@code publicId} field
   * @param title the {@code title} field
   */
  public record Ctypes(String id, String publicId, String title) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static Ctypes decode(ResponseReader reader) {
      return new Ctypes(
          reader.get("id", Decoders.STRING),
          reader.get("publicId", Decoders.STRING),
          reader.get("title", Decoders.STRING));
    }
  }

  /**
   * Эрсдлийн төлөв.
   *
   * @param id the {@code id} field
   * @param publicId the {@code publicId} field
   * @param title the {@code title} field
   * @param desc the {@code desc} field
   */
  public record Status(String id, String publicId, String title, String desc) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static Status decode(ResponseReader reader) {
      return new Status(
          reader.get("id", Decoders.STRING),
          reader.get("publicId", Decoders.STRING),
          reader.get("title", Decoders.STRING),
          reader.get("desc", Decoders.STRING));
    }
  }

  /**
   * risks - Эрсдлийн жагсаалт харах.
   *
   * @param id the {@code id} field
   * @param publicId the {@code publicId} field
   * @param ctpid the {@code ctpid} field
   * @param sttpid the {@code sttpid} field
   * @param desc the {@code desc} field
   * @param lt the {@code lt} field
   * @param ln the {@code ln} field
   * @param civilid the {@code civilid} field
   * @param ctypes the {@code ctypes} field
   * @param status the {@code status} field
   * @param types the {@code types} field
   * @param systems the {@code systems} field
   */
  public record Risks(
      String id,
      String publicId,
      String ctpid,
      String sttpid,
      String desc,
      String lt,
      String ln,
      String civilid,
      Object ctypes,
      Object status,
      Object types,
      Object systems) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static Risks decode(ResponseReader reader) {
      return new Risks(
          reader.get("id", Decoders.STRING),
          reader.get("publicId", Decoders.STRING),
          reader.get("ctpid", Decoders.STRING),
          reader.get("sttpid", Decoders.STRING),
          reader.get("desc", Decoders.STRING),
          reader.get("lt", Decoders.STRING),
          reader.get("ln", Decoders.STRING),
          reader.get("civilid", Decoders.STRING),
          reader.get("ctypes", Decoders.ANY),
          reader.get("status", Decoders.ANY),
          reader.get("types", Decoders.ANY),
          reader.get("systems", Decoders.ANY));
    }
  }
}
