// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.governmentservice;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code GS10086_RiskRegistrationService}: Эрсдэл бүртгэх нэгдсэн үйлдэл.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param risk the {@code risk} field
 * @param rschlog the {@code rschlog} field
 * @param org the {@code org} field
 * @param orgCreated the {@code orgCreated} field
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record RiskRegistrationServiceResponse(
    Object risk, Object rschlog, Object org, Boolean orgCreated, Extras extras) {

  static RiskRegistrationServiceResponse decode(ResponseReader reader) {
    return new RiskRegistrationServiceResponse(
        reader.get("risk", Decoders.ANY),
        reader.get("rschlog", Decoders.ANY),
        reader.get("org", Decoders.ANY),
        reader.get("orgCreated", Decoders.BOOL),
        reader.extras());
  }
}
