<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Payment;

use Xyp\Attribute\ListOf;
use Xyp\Date;

/**
 * `partnerLoanListData` in the response of WS100841_citizenLoanInfoTitan.
 */
final readonly class CitizenLoanInfoTitanPartnerLoanListData
{
    /**
     * @param mixed $customerName Зээлдэгчийн нэр
     * @param mixed $regnum Зээлдэгчийн регистер
     * @param mixed $loanType Үүргийн төрөл /Зээл, Зээлийн шугам, Авлага Үнэт цаас гэх мэт/
     * @param string|null $dutyType Санхүүгийн үүргийн төрөл
     * @param mixed $currencyCode Валют
     * @param mixed $advamount Олгосон дүн
     * @param mixed $interestinprec Хүү
     * @param Date|null $startedDate Олгосон огноо
     * @param Date|null $expDate Төлөгдөх огноо
     * @param Date|null $paidDate Төлөгдсөн огноо
     * @param mixed $balance Үлдэгдэл
     * @param mixed $loanClass Ангилал /Хэвийн, Хэвийн бус, Хугацаа хэтэрсэн гэх мэт/
     * @param list<string> $submrtName Барьцаа хөрөнгийн бүлгийн нэр
     * @param list<string> $stateRegisterNo Гэрчилгээний УБ-ын дугаар
     * @param mixed $orgName Олгосон байгууллага
     * @param mixed $description Тайлбар
     * @param string|null $morg олгосон байгууллагын дугаар
     * @param string|null $mvalue давтагдашгүй дугаар
     * @param float|null $rate rate
     */
    public function __construct(
        public mixed $customerName = null,
        public mixed $regnum = null,
        public mixed $loanType = null,
        public ?string $dutyType = null,
        public mixed $currencyCode = null,
        public mixed $advamount = null,
        public mixed $interestinprec = null,
        public ?Date $startedDate = null,
        public ?Date $expDate = null,
        public ?Date $paidDate = null,
        public mixed $balance = null,
        public mixed $loanClass = null,
        #[ListOf('string')]
        public array $submrtName = [],
        #[ListOf('string')]
        public array $stateRegisterNo = [],
        public mixed $orgName = null,
        public mixed $description = null,
        public ?string $morg = null,
        public ?string $mvalue = null,
        public ?float $rate = null,
    ) {}
}
