<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Tax;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of WS100624_getOrganizationInfo: Байгууллагын тодорхойлолт.
 *
 * Provider: Татварын ерөнхий газар
 */
final readonly class GetOrganizationInfoResponse
{
    /**
     * @param string|null $companyRegnum Байгууллагын регистрийн дугаар
     * @param string|null $usage Зориулалт
     * @param string|null $forUsage Хаана зориулж
     * @param string|null $year Тодорхойлолт хамаарах он
     * @param string|null $callNumber Тодорхойлолтын баркод
     * @param string|null $callDate Үүсгэсэн огноо
     * @param string|null $endDate Хүчинтэй хугацаа
     * @param mixed $tpInfo Татвар төлөгчийн ерөнхий мэдээлэл
     * @param list<mixed> $listReturn Татварын тайлан тушаалт
     * @param mixed $ebarimt Цахим төлбөрийн баримтын системд холбогдсон байдал
     * @param list<mixed> $listPayment Татвар төлөлт
     * @param list<mixed> $listDebt Татварын үлдэгдэл
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $companyRegnum = null,
        public ?string $usage = null,
        public ?string $forUsage = null,
        public ?string $year = null,
        public ?string $callNumber = null,
        public ?string $callDate = null,
        public ?string $endDate = null,
        public mixed $tpInfo = null,
        #[ListOf('any')]
        public array $listReturn = [],
        public mixed $ebarimt = null,
        #[ListOf('any')]
        public array $listPayment = [],
        #[ListOf('any')]
        public array $listDebt = [],
        public Extras $xyp = new Extras(),
    ) {}
}
