// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.health;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The request of {@link HealthClient#citizenQuestionnaireSubmitService}, XYP operation {@code
 * WS300192_CitizenQuestionnaireSubmitService}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class CitizenQuestionnaireSubmitServiceParams implements RequestParams {
  private final String regnum;
  private final Long rcad;
  private final Long phoneNo;
  private final String feedBack;
  private final List<Object> answers;

  private CitizenQuestionnaireSubmitServiceParams(Builder builder) {
    this.regnum = builder.regnum;
    this.rcad = builder.rcad;
    this.phoneNo = builder.phoneNo;
    this.feedBack = builder.feedBack;
    this.answers = builder.answers;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Иргэний РД.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String regnum() {
    return regnum;
  }

  /**
   * Тусламж үйлчилгээний бүртгэлийн ID.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long rcad() {
    return rcad;
  }

  /**
   * Иргэний утасны дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long phoneNo() {
    return phoneNo;
  }

  /**
   * Санал, сэтгэгдэл.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String feedBack() {
    return feedBack;
  }

  /**
   * Хариулт.
   *
   * @return the value, or {@code null} when it is not set
   */
  public List<Object> answers() {
    return answers;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("regnum", regnum)
        .add("rcad", rcad)
        .add("phoneNo", phoneNo)
        .add("feedBack", feedBack)
        .add("answers", answers)
        .build();
  }

  /**
   * Builds a {@link CitizenQuestionnaireSubmitServiceParams}. Every setter accepts {@code null},
   * which leaves the field out of the request. A builder is not thread-safe; it can be reused, and
   * setting a field again does not change the params it has already built.
   */
  public static final class Builder {
    private String regnum;
    private Long rcad;
    private Long phoneNo;
    private String feedBack;
    private List<Object> answers;

    private Builder() {}

    /**
     * Иргэний РД.
     *
     * @param regnum the value, or {@code null}
     * @return this builder
     */
    public Builder regnum(String regnum) {
      this.regnum = regnum;
      return this;
    }

    /**
     * Тусламж үйлчилгээний бүртгэлийн ID.
     *
     * @param rcad the value, or {@code null}
     * @return this builder
     */
    public Builder rcad(Long rcad) {
      this.rcad = rcad;
      return this;
    }

    /**
     * Иргэний утасны дугаар.
     *
     * @param phoneNo the value, or {@code null}
     * @return this builder
     */
    public Builder phoneNo(Long phoneNo) {
      this.phoneNo = phoneNo;
      return this;
    }

    /**
     * Санал, сэтгэгдэл.
     *
     * @param feedBack the value, or {@code null}
     * @return this builder
     */
    public Builder feedBack(String feedBack) {
      this.feedBack = feedBack;
      return this;
    }

    /**
     * Хариулт.
     *
     * @param answers the values, copied (a {@code null} item is not sent), or {@code null}
     * @return this builder
     */
    public Builder answers(List<Object> answers) {
      this.answers =
          answers == null ? null : Collections.unmodifiableList(new ArrayList<>(answers));
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link CitizenQuestionnaireSubmitServiceParams}
     */
    public CitizenQuestionnaireSubmitServiceParams build() {
      return new CitizenQuestionnaireSubmitServiceParams(this);
    }
  }
}
