// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.health;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS300124_eHospitalFindAddress}: Хаягийн жагсаалт дуудах.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData the {@code listData} field
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record EHospitalFindAddressResponse(List<ListData> listData, Extras extras) {

  static EHospitalFindAddressResponse decode(ResponseReader reader) {
    return new EHospitalFindAddressResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * An element of the {@code listData} list in the response of {@code
   * WS300124_eHospitalFindAddress}.
   *
   * @param addressId the {@code addressId} field
   * @param addressName the {@code addressName} field
   * @param sumDuureg the {@code sumDuureg} field
   */
  public record ListData(Long addressId, String addressName, List<Object> sumDuureg) {

    static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("addressId", Decoders.INT),
          reader.get("addressName", Decoders.STRING),
          reader.get("sumDuureg", Decoders.list(Decoders.ANY)));
    }
  }
}
