// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.health;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;

/**
 * The request of {@link HealthClient#getChildBook}, XYP operation {@code WS300173_GetChildBook}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GetChildBookParams implements RequestParams {
  private final Long checkUpId;
  private final String bookNumber;
  private final String childRegnum;

  private GetChildBookParams(Builder builder) {
    this.checkUpId = builder.checkUpId;
    this.bookNumber = builder.bookNumber;
    this.childRegnum = builder.childRegnum;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the {@code checkUpId} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public Long checkUpId() {
    return checkUpId;
  }

  /**
   * Returns the {@code bookNumber} field.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String bookNumber() {
    return bookNumber;
  }

  /**
   * Хүүхдийн регистр.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String childRegnum() {
    return childRegnum;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("checkUpId", checkUpId)
        .add("bookNumber", bookNumber)
        .add("childRegnum", childRegnum)
        .build();
  }

  /**
   * Builds a {@link GetChildBookParams}. Every setter accepts {@code null}, which leaves the field
   * out of the request. A builder is not thread-safe; it can be reused, and setting a field again
   * does not change the params it has already built.
   */
  public static final class Builder {
    private Long checkUpId;
    private String bookNumber;
    private String childRegnum;

    private Builder() {}

    /**
     * Sets the {@code checkUpId} field.
     *
     * @param checkUpId the value, or {@code null}
     * @return this builder
     */
    public Builder checkUpId(Long checkUpId) {
      this.checkUpId = checkUpId;
      return this;
    }

    /**
     * Sets the {@code bookNumber} field.
     *
     * @param bookNumber the value, or {@code null}
     * @return this builder
     */
    public Builder bookNumber(String bookNumber) {
      this.bookNumber = bookNumber;
      return this;
    }

    /**
     * Хүүхдийн регистр.
     *
     * @param childRegnum the value, or {@code null}
     * @return this builder
     */
    public Builder childRegnum(String childRegnum) {
      this.childRegnum = childRegnum;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GetChildBookParams}
     */
    public GetChildBookParams build() {
      return new GetChildBookParams(this);
    }
  }
}
