// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.health;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS300119_medicineImportInsert}: эм, эмнэлгийн хэрэгсэл хилээр нэвтрүүлэх
 * зөвшөөрлийн мэдээллийг оруулах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param message хариу
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record MedicineImportInsertResponse(String message, Extras extras) {

  static MedicineImportInsertResponse decode(ResponseReader reader) {
    return new MedicineImportInsertResponse(
        reader.get("message", Decoders.STRING), reader.extras());
  }
}
