"""GENERATED by xyp-generator from spec/services.json. Do not edit.

Response models of the `citizen` group, re-exported for type annotations:

    from xyp.models.citizen import ActiveVocationalStudentInfoList
"""

from xyp.operations.citizen.active_vocational_student_info import (
    ActiveVocationalStudentInfoList,
    ActiveVocationalStudentInfoResponse,
)
from xyp.operations.citizen.address_apartment_info import (
    AddressApartmentInfoResponse,
)
from xyp.operations.citizen.address_street_info import (
    AddressStreetInfoResponse,
)
from xyp.operations.citizen.address_type_info import (
    AddressTypeInfoListData,
    AddressTypeInfoResponse,
)
from xyp.operations.citizen.affiliation_registration_info import (
    AffiliationRegistrationInfoListdata,
    AffiliationRegistrationInfoResponse,
)
from xyp.operations.citizen.aimag_city_info import (
    AimagCityInfoListData,
    AimagCityInfoResponse,
)
from xyp.operations.citizen.authorize_citizen import (
    AuthorizeCitizenResponse,
)
from xyp.operations.citizen.bag_khoroo_info import (
    BagKhorooInfoListData,
    BagKhorooInfoResponse,
)
from xyp.operations.citizen.border_ban import (
    BorderBanListData,
    BorderBanResponse,
)
from xyp.operations.citizen.check_citizen_address_info import (
    CheckCitizenAddressInfoResponse,
)
from xyp.operations.citizen.check_citizen_info import (
    CheckCitizenInfoResponse,
)
from xyp.operations.citizen.check_citizen_non_passport import (
    CheckCitizenNonPassportResponse,
)
from xyp.operations.citizen.check_citizen_regnum import (
    CheckCitizenRegnumResponse,
)
from xyp.operations.citizen.check_id_card_service import (
    CheckIdCardServiceResponse,
)
from xyp.operations.citizen.check_twin_info import (
    CheckTwinInfoListData,
    CheckTwinInfoResponse,
)
from xyp.operations.citizen.children_rank_statistic_info import (
    ChildrenRankStatisticInfoListData,
    ChildrenRankStatisticInfoResponse,
)
from xyp.operations.citizen.citizen_address_list_english import (
    CitizenAddressListEnglishListData,
    CitizenAddressListEnglishResponse,
)
from xyp.operations.citizen.citizen_birth_info import (
    CitizenBirthInfoListData,
    CitizenBirthInfoResponse,
)
from xyp.operations.citizen.citizen_birth_info_ws101123 import (
    CitizenBirthInfoWS101123Response,
)
from xyp.operations.citizen.citizen_denationalization_info import (
    CitizenDenationalizationInfoListData,
    CitizenDenationalizationInfoResponse,
)
from xyp.operations.citizen.citizen_doing_criminal_liabilityl_info import (
    CitizenDoingCriminalLiabilitylInfoResponse,
)
from xyp.operations.citizen.citizen_doing_criminal_liabilty_eng_info import (
    CitizenDoingCriminalLiabiltyEngInfoResponse,
)
from xyp.operations.citizen.citizen_graduate_school_description import (
    CitizenGraduateSchoolDescriptionResponse,
)
from xyp.operations.citizen.citizen_graduate_school_info import (
    CitizenGraduateSchoolInfoResponse,
)
from xyp.operations.citizen.citizen_graduate_school_list import (
    CitizenGraduateSchoolListListData,
    CitizenGraduateSchoolListResponse,
)
from xyp.operations.citizen.citizen_high_school_description import (
    CitizenHighSchoolDescriptionResponse,
)
from xyp.operations.citizen.citizen_kindergarten_description import (
    CitizenKindergartenDescriptionResponse,
)
from xyp.operations.citizen.citizen_look_up_address import (
    CitizenLookUpAddressListData,
    CitizenLookUpAddressResponse,
)
from xyp.operations.citizen.citizen_look_up_info import (
    CitizenLookUpInfoListData,
    CitizenLookUpInfoResponse,
)
from xyp.operations.citizen.citizen_new_diploma_info import (
    CitizenNewDiplomaInfoData,
    CitizenNewDiplomaInfoResponse,
)
from xyp.operations.citizen.citizen_was_criminal_liabilityl_info import (
    CitizenWasCriminalLiabilitylInfoListData,
    CitizenWasCriminalLiabilitylInfoResponse,
)
from xyp.operations.citizen.civil_info_at_burtgelmn import (
    CivilInfoAtBurtgelmnResponse,
)
from xyp.operations.citizen.civil_service_employee_info import (
    CivilServiceEmployeeInfoResponse,
)
from xyp.operations.citizen.conformity_certificate_detail_service import (
    ConformityCertificateDetailServiceResponse,
)
from xyp.operations.citizen.conformity_certificate_list import (
    ConformityCertificateListApplicationListData,
    ConformityCertificateListResponse,
)
from xyp.operations.citizen.current_passport_info import (
    CurrentPassportInfoResponse,
)
from xyp.operations.citizen.decease_list_by_date import (
    DeceaseListByDateListData,
    DeceaseListByDateResponse,
)
from xyp.operations.citizen.entity_affil_by_regnum_service import (
    EntityAffilByRegnumServiceListData,
    EntityAffilByRegnumServiceResponse,
)
from xyp.operations.citizen.extend_term_of_granted_name import (
    ExtendTermOfGrantedNameList,
    ExtendTermOfGrantedNameResponse,
)
from xyp.operations.citizen.extend_term_of_granted_name_update import (
    ExtendTermOfGrantedNameUpdateResponse,
)
from xyp.operations.citizen.first_time_passport_info import (
    FirstTimePassportInfoResponse,
)
from xyp.operations.citizen.foreign_passport_unregistered_info_english import (
    ForeignPassportUnregisteredInfoEnglishListData,
    ForeignPassportUnregisteredInfoEnglishResponse,
)
from xyp.operations.citizen.get_children_info import (
    GetChildrenInfoListData,
    GetChildrenInfoResponse,
)
from xyp.operations.citizen.get_citizen_address_info import (
    GetCitizenAddressInfoResponse,
)
from xyp.operations.citizen.get_citizen_before_address_info import (
    GetCitizenBeforeAddressInfoResponse,
)
from xyp.operations.citizen.get_citizen_below_subsistence_level_info import (
    GetCitizenBelowSubsistenceLevelInfoList,
    GetCitizenBelowSubsistenceLevelInfoResponse,
)
from xyp.operations.citizen.get_citizen_birth_info import (
    GetCitizenBirthInfoResponse,
)
from xyp.operations.citizen.get_citizen_change_name_info import (
    GetCitizenChangeNameInfoResponse,
)
from xyp.operations.citizen.get_citizen_change_regnum_info import (
    GetCitizenChangeRegnumInfoResponse,
)
from xyp.operations.citizen.get_citizen_decease_info import (
    GetCitizenDeceaseInfoResponse,
)
from xyp.operations.citizen.get_citizen_foul_info import (
    GetCitizenFoulInfoResponse,
)
from xyp.operations.citizen.get_citizen_health_insurance_info import (
    GetCitizenHealthInsuranceInfoListData,
    GetCitizenHealthInsuranceInfoResponse,
)
from xyp.operations.citizen.get_citizen_id_card_info import (
    GetCitizenIdCardInfoListAddress,
    GetCitizenIdCardInfoResponse,
)
from xyp.operations.citizen.get_citizen_marriage_divorce_info import (
    GetCitizenMarriageDivorceInfoResponse,
)
from xyp.operations.citizen.get_citizen_marriage_info import (
    GetCitizenMarriageInfoResponse,
)
from xyp.operations.citizen.get_citizen_no_marriage_info import (
    GetCitizenNoMarriageInfoResponse,
)
from xyp.operations.citizen.get_citizen_non_id_card_info import (
    GetCitizenNonIdCardInfoResponse,
)
from xyp.operations.citizen.get_citizen_non_payment_info import (
    GetCitizenNonPaymentInfoResponse,
)
from xyp.operations.citizen.get_citizen_regnum_info import (
    GetCitizenRegnumInfoResponse,
)
from xyp.operations.citizen.get_dictionary_name_info import (
    GetDictionaryNameInfoResponse,
)
from xyp.operations.citizen.get_dissolved_legal_entity_info import (
    GetDissolvedLegalEntityInfoResponse,
)
from xyp.operations.citizen.get_election_location import (
    GetElectionLocationResponse,
)
from xyp.operations.citizen.get_id_card_photo import (
    GetIdCardPhotoListData,
    GetIdCardPhotoResponse,
)
from xyp.operations.citizen.get_marriage_restore_info import (
    GetMarriageRestoreInfoResponse,
)
from xyp.operations.citizen.get_organization_where_citizen_works_info import (
    GetOrganizationWhereCitizenWorksInfoResponse,
)
from xyp.operations.citizen.get_passport_civil_info import (
    GetPassportCivilInfoListData,
    GetPassportCivilInfoResponse,
)
from xyp.operations.citizen.get_passport_issued_place import (
    GetPassportIssuedPlaceListData,
    GetPassportIssuedPlaceResponse,
)
from xyp.operations.citizen.get_stamp_reference import (
    GetStampReferenceResponse,
)
from xyp.operations.citizen.get_topic_scope import (
    GetTopicScopeList,
    GetTopicScopeResponse,
)
from xyp.operations.citizen.get_topics import (
    GetTopicsList,
    GetTopicsResponse,
)
from xyp.operations.citizen.graduated_vocational_student_info import (
    GraduatedVocationalStudentInfoList,
    GraduatedVocationalStudentInfoResponse,
)
from xyp.operations.citizen.internal_troops_description import (
    InternalTroopsDescriptionResponse,
)
from xyp.operations.citizen.legal_entity_name_validity_service import (
    LegalEntityNameValidityServiceNameList,
    LegalEntityNameValidityServiceResponse,
)
from xyp.operations.citizen.list_of_civil_titles import (
    ListOfCivilTitlesList,
    ListOfCivilTitlesResponse,
)
from xyp.operations.citizen.passport_info import (
    PassportInfoListData,
    PassportInfoResponse,
)
from xyp.operations.citizen.passport_info_second_time import (
    PassportInfoSecondTimeResponse,
)
from xyp.operations.citizen.passport_invalid_info import (
    PassportInvalidInfoListData,
    PassportInvalidInfoResponse,
)
from xyp.operations.citizen.passport_validity_checker import (
    PassportValidityCheckerList,
    PassportValidityCheckerResponse,
)
from xyp.operations.citizen.police_weapon_movement_transfer_service import (
    PoliceWeaponMovementTransferServiceListData,
    PoliceWeaponMovementTransferServiceResponse,
)
from xyp.operations.citizen.regnum_change_info_english import (
    RegnumChangeInfoEnglishListData,
    RegnumChangeInfoEnglishResponse,
)
from xyp.operations.citizen.regnum_info_english import (
    RegnumInfoEnglishListData,
    RegnumInfoEnglishResponse,
)
from xyp.operations.citizen.soum_district_info import (
    SoumDistrictInfoListData,
    SoumDistrictInfoResponse,
)
from xyp.operations.citizen.svc_marriage_restores import (
    SvcMarriageRestoresResponse,
)

__all__ = [
    "ActiveVocationalStudentInfoList",
    "ActiveVocationalStudentInfoResponse",
    "AddressApartmentInfoResponse",
    "AddressStreetInfoResponse",
    "AddressTypeInfoListData",
    "AddressTypeInfoResponse",
    "AffiliationRegistrationInfoListdata",
    "AffiliationRegistrationInfoResponse",
    "AimagCityInfoListData",
    "AimagCityInfoResponse",
    "AuthorizeCitizenResponse",
    "BagKhorooInfoListData",
    "BagKhorooInfoResponse",
    "BorderBanListData",
    "BorderBanResponse",
    "CheckCitizenAddressInfoResponse",
    "CheckCitizenInfoResponse",
    "CheckCitizenNonPassportResponse",
    "CheckCitizenRegnumResponse",
    "CheckIdCardServiceResponse",
    "CheckTwinInfoListData",
    "CheckTwinInfoResponse",
    "ChildrenRankStatisticInfoListData",
    "ChildrenRankStatisticInfoResponse",
    "CitizenAddressListEnglishListData",
    "CitizenAddressListEnglishResponse",
    "CitizenBirthInfoListData",
    "CitizenBirthInfoResponse",
    "CitizenBirthInfoWS101123Response",
    "CitizenDenationalizationInfoListData",
    "CitizenDenationalizationInfoResponse",
    "CitizenDoingCriminalLiabilitylInfoResponse",
    "CitizenDoingCriminalLiabiltyEngInfoResponse",
    "CitizenGraduateSchoolDescriptionResponse",
    "CitizenGraduateSchoolInfoResponse",
    "CitizenGraduateSchoolListListData",
    "CitizenGraduateSchoolListResponse",
    "CitizenHighSchoolDescriptionResponse",
    "CitizenKindergartenDescriptionResponse",
    "CitizenLookUpAddressListData",
    "CitizenLookUpAddressResponse",
    "CitizenLookUpInfoListData",
    "CitizenLookUpInfoResponse",
    "CitizenNewDiplomaInfoData",
    "CitizenNewDiplomaInfoResponse",
    "CitizenWasCriminalLiabilitylInfoListData",
    "CitizenWasCriminalLiabilitylInfoResponse",
    "CivilInfoAtBurtgelmnResponse",
    "CivilServiceEmployeeInfoResponse",
    "ConformityCertificateDetailServiceResponse",
    "ConformityCertificateListApplicationListData",
    "ConformityCertificateListResponse",
    "CurrentPassportInfoResponse",
    "DeceaseListByDateListData",
    "DeceaseListByDateResponse",
    "EntityAffilByRegnumServiceListData",
    "EntityAffilByRegnumServiceResponse",
    "ExtendTermOfGrantedNameList",
    "ExtendTermOfGrantedNameResponse",
    "ExtendTermOfGrantedNameUpdateResponse",
    "FirstTimePassportInfoResponse",
    "ForeignPassportUnregisteredInfoEnglishListData",
    "ForeignPassportUnregisteredInfoEnglishResponse",
    "GetChildrenInfoListData",
    "GetChildrenInfoResponse",
    "GetCitizenAddressInfoResponse",
    "GetCitizenBeforeAddressInfoResponse",
    "GetCitizenBelowSubsistenceLevelInfoList",
    "GetCitizenBelowSubsistenceLevelInfoResponse",
    "GetCitizenBirthInfoResponse",
    "GetCitizenChangeNameInfoResponse",
    "GetCitizenChangeRegnumInfoResponse",
    "GetCitizenDeceaseInfoResponse",
    "GetCitizenFoulInfoResponse",
    "GetCitizenHealthInsuranceInfoListData",
    "GetCitizenHealthInsuranceInfoResponse",
    "GetCitizenIdCardInfoListAddress",
    "GetCitizenIdCardInfoResponse",
    "GetCitizenMarriageDivorceInfoResponse",
    "GetCitizenMarriageInfoResponse",
    "GetCitizenNoMarriageInfoResponse",
    "GetCitizenNonIdCardInfoResponse",
    "GetCitizenNonPaymentInfoResponse",
    "GetCitizenRegnumInfoResponse",
    "GetDictionaryNameInfoResponse",
    "GetDissolvedLegalEntityInfoResponse",
    "GetElectionLocationResponse",
    "GetIdCardPhotoListData",
    "GetIdCardPhotoResponse",
    "GetMarriageRestoreInfoResponse",
    "GetOrganizationWhereCitizenWorksInfoResponse",
    "GetPassportCivilInfoListData",
    "GetPassportCivilInfoResponse",
    "GetPassportIssuedPlaceListData",
    "GetPassportIssuedPlaceResponse",
    "GetStampReferenceResponse",
    "GetTopicScopeList",
    "GetTopicScopeResponse",
    "GetTopicsList",
    "GetTopicsResponse",
    "GraduatedVocationalStudentInfoList",
    "GraduatedVocationalStudentInfoResponse",
    "InternalTroopsDescriptionResponse",
    "LegalEntityNameValidityServiceNameList",
    "LegalEntityNameValidityServiceResponse",
    "ListOfCivilTitlesList",
    "ListOfCivilTitlesResponse",
    "PassportInfoListData",
    "PassportInfoResponse",
    "PassportInfoSecondTimeResponse",
    "PassportInvalidInfoListData",
    "PassportInvalidInfoResponse",
    "PassportValidityCheckerList",
    "PassportValidityCheckerResponse",
    "PoliceWeaponMovementTransferServiceListData",
    "PoliceWeaponMovementTransferServiceResponse",
    "RegnumChangeInfoEnglishListData",
    "RegnumChangeInfoEnglishResponse",
    "RegnumInfoEnglishListData",
    "RegnumInfoEnglishResponse",
    "SoumDistrictInfoListData",
    "SoumDistrictInfoResponse",
    "SvcMarriageRestoresResponse",
]
