"""GENERATED by xyp-generator from spec/services.json. Do not edit.

Response models of the `private_service` group, re-exported for type annotations:

    from xyp.models.private_service import CheckKindergartenEnrollmentResponse
"""

from xyp.operations.private_service.check_kindergarten_enrollment import (
    CheckKindergartenEnrollmentResponse,
)
from xyp.operations.private_service.children_info_by_parent_civil_id import (
    ChildrenInfoByParentCivilIdListData,
    ChildrenInfoByParentCivilIdResponse,
)
from xyp.operations.private_service.id_card_info_em import (
    IdCardInfoEmListAddress,
    IdCardInfoEmResponse,
)
from xyp.operations.private_service.kindergarten_description import (
    KindergartenDescriptionResponse,
)
from xyp.operations.private_service.result_kindergarten_enrollment import (
    ResultKindergartenEnrollmentListData,
    ResultKindergartenEnrollmentResponse,
)
from xyp.operations.private_service.send_kindergarten_enrollment import (
    SendKindergartenEnrollmentResponse,
)

__all__ = [
    "CheckKindergartenEnrollmentResponse",
    "ChildrenInfoByParentCivilIdListData",
    "ChildrenInfoByParentCivilIdResponse",
    "IdCardInfoEmListAddress",
    "IdCardInfoEmResponse",
    "KindergartenDescriptionResponse",
    "ResultKindergartenEnrollmentListData",
    "ResultKindergartenEnrollmentResponse",
    "SendKindergartenEnrollmentResponse",
]
