"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS300190_CitizenServicePackageNumberInquiryService (health, Эрүүл мэндийн даатгалын ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS300190_CitizenServicePackageNumberInquiryService"


class CitizenServicePackageNumberInquiryServiceListData(XypModel):
    """Жагсаалт"""

    total_amount_citizen: float | None = Field(
        default=None, alias="totalAmountCitizen", description="Иргэний төлөх дүн"
    )
    totol_amount_insurance: float | None = Field(
        default=None, alias="totolAmountInsurance", description="ЭМД-с хөнгөлөх дүн"
    )
    package_id: str | None = Field(default=None, alias="packageId", description="Багцын дугаар")
    year: int | None = Field(default=None, alias="year", description="Тусламж үйлчилгээний жил")
    month: int | None = Field(default=None, alias="month", description="Тусламж үйлчилгээний сар")


class CitizenServicePackageNumberInquiryServiceResponse(XypModel):
    """WS300190_CitizenServicePackageNumberInquiryService: Иргэний авсан тусламж үйлчилгээний багцын дугаар лавлах сервис"""

    list_data: list[CitizenServicePackageNumberInquiryServiceListData] | None = Field(
        default=None, alias="listData", description="Жагсаалт"
    )


def citizen_service_package_number_inquiry_service(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> CitizenServicePackageNumberInquiryServiceResponse:
    """WS300190_CitizenServicePackageNumberInquiryService: Иргэний авсан тусламж үйлчилгээний багцын дугаар лавлах сервис

    Provider: Эрүүл мэндийн даатгалын ерөнхий газар

    Args:
        regnum: Иргэний РД
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(CitizenServicePackageNumberInquiryServiceResponse, data)


async def citizen_service_package_number_inquiry_service_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> CitizenServicePackageNumberInquiryServiceResponse:
    """WS300190_CitizenServicePackageNumberInquiryService: Иргэний авсан тусламж үйлчилгээний багцын дугаар лавлах сервис

    Provider: Эрүүл мэндийн даатгалын ерөнхий газар

    Args:
        regnum: Иргэний РД
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(CitizenServicePackageNumberInquiryServiceResponse, data)
