"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS300114_eHealthListService (health, Эрүүл мэндийн яам)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS300114_eHealthListService"


class EHealthListServiceResponse(XypModel):
    """WS300114_eHealthListService: EHealth Эмнэлгийн хуудасны мэдээлэл харах"""

    result_data: str | None = Field(default=None, alias="resultData", description="үр дүн")


def e_health_list_service(
    self: SyncService,
    *,
    hospital_id: int | None = None,
    pid: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EHealthListServiceResponse:
    """WS300114_eHealthListService: EHealth Эмнэлгийн хуудасны мэдээлэл харах

    Provider: Эрүүл мэндийн яам

    Args:
        hospital_id: эмнэлгийн дугаар
        pid: Эмнэлгийн хуудасны дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "hospitalId": hospital_id,
            "pid": pid,
        },
        auth,
        operator,
    )
    return parse_model(EHealthListServiceResponse, data)


async def e_health_list_service_async(
    self: AsyncService,
    *,
    hospital_id: int | None = None,
    pid: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EHealthListServiceResponse:
    """WS300114_eHealthListService: EHealth Эмнэлгийн хуудасны мэдээлэл харах

    Provider: Эрүүл мэндийн яам

    Args:
        hospital_id: эмнэлгийн дугаар
        pid: Эмнэлгийн хуудасны дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "hospitalId": hospital_id,
            "pid": pid,
        },
        auth,
        operator,
    )
    return parse_model(EHealthListServiceResponse, data)
