"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS300125_eHospitalByAddress (health, Эрүүл мэндийн даатгалын ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS300125_eHospitalByAddress"


class EHospitalByAddressListData(XypModel):
    address_id: int | None = Field(default=None, alias="addressId")
    hospital_id: int | None = Field(default=None, alias="hospitalId")
    hospital_name: str | None = Field(default=None, alias="hospitalName")


class EHospitalByAddressResponse(XypModel):
    """WS300125_eHospitalByAddress: Сонгосон баг хороонд байгаа өрхийн эмнэлгүүд"""

    list_data: list[EHospitalByAddressListData] | None = Field(default=None, alias="listData")


def e_hospital_by_address(
    self: SyncService,
    *,
    addressid: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EHospitalByAddressResponse:
    """WS300125_eHospitalByAddress: Сонгосон баг хороонд байгаа өрхийн эмнэлгүүд

    Provider: Эрүүл мэндийн даатгалын ерөнхий газар

    Args:
        addressid: addressid
    """
    data = self._transport.call(
        _OPERATION,
        {
            "addressid": addressid,
        },
        auth,
        operator,
    )
    return parse_model(EHospitalByAddressResponse, data)


async def e_hospital_by_address_async(
    self: AsyncService,
    *,
    addressid: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EHospitalByAddressResponse:
    """WS300125_eHospitalByAddress: Сонгосон баг хороонд байгаа өрхийн эмнэлгүүд

    Provider: Эрүүл мэндийн даатгалын ерөнхий газар

    Args:
        addressid: addressid
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "addressid": addressid,
        },
        auth,
        operator,
    )
    return parse_model(EHospitalByAddressResponse, data)
