"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS300126_eHospitalCheckPatientExists (health, Эрүүл мэндийн даатгалын ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS300126_eHospitalCheckPatientExists"


class EHospitalCheckPatientExistsResponse(XypModel):
    """WS300126_eHospitalCheckPatientExists: EHospital Тухайн эмнэлэгт хэрэглэгч бүртгэлтэй эсэх"""

    check_code: int | None = Field(
        default=None, alias="checkCode", description="хүсэлтийн хариу код"
    )


def e_hospital_check_patient_exists(
    self: SyncService,
    *,
    regnum: str | None = None,
    hospital_id: int | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EHospitalCheckPatientExistsResponse:
    """WS300126_eHospitalCheckPatientExists: EHospital Тухайн эмнэлэгт хэрэглэгч бүртгэлтэй эсэх

    Provider: Эрүүл мэндийн даатгалын ерөнхий газар

    Args:
        regnum: регистрийн дугаар
        hospital_id: эмнэлгийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "hospitalId": hospital_id,
        },
        auth,
        operator,
    )
    return parse_model(EHospitalCheckPatientExistsResponse, data)


async def e_hospital_check_patient_exists_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    hospital_id: int | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EHospitalCheckPatientExistsResponse:
    """WS300126_eHospitalCheckPatientExists: EHospital Тухайн эмнэлэгт хэрэглэгч бүртгэлтэй эсэх

    Provider: Эрүүл мэндийн даатгалын ерөнхий газар

    Args:
        regnum: регистрийн дугаар
        hospital_id: эмнэлгийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "hospitalId": hospital_id,
        },
        auth,
        operator,
    )
    return parse_model(EHospitalCheckPatientExistsResponse, data)
