"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS300171_GetChildBirth (health, Эрүүл мэндийн яам)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS300171_GetChildBirth"


class GetChildBirthResponse(XypModel):
    """WS300171_GetChildBirth: Тухайн хүүхдийн төрөлтийн мэдээллийг буцаах сервис"""

    birth_date: str | None = Field(default=None, alias="birthDate")
    hospital: str | None = Field(default=None, alias="hospital")
    weight: str | None = Field(default=None, alias="weight")
    height: str | None = Field(default=None, alias="height")
    tcircle: str | None = Field(default=None, alias="tcircle")
    mcircle: str | None = Field(default=None, alias="mcircle")
    gender: str | None = Field(default=None, alias="gender")


def get_child_birth(
    self: SyncService,
    *,
    mother_regnum: str | None = None,
    child_regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetChildBirthResponse:
    """WS300171_GetChildBirth: Тухайн хүүхдийн төрөлтийн мэдээллийг буцаах сервис

    Provider: Эрүүл мэндийн яам

    Args:
        mother_regnum: Ээжийн регистр
        child_regnum: Хүүхдийн регистр
    """
    data = self._transport.call(
        _OPERATION,
        {
            "motherRegnum": mother_regnum,
            "childRegnum": child_regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetChildBirthResponse, data)


async def get_child_birth_async(
    self: AsyncService,
    *,
    mother_regnum: str | None = None,
    child_regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetChildBirthResponse:
    """WS300171_GetChildBirth: Тухайн хүүхдийн төрөлтийн мэдээллийг буцаах сервис

    Provider: Эрүүл мэндийн яам

    Args:
        mother_regnum: Ээжийн регистр
        child_regnum: Хүүхдийн регистр
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "motherRegnum": mother_regnum,
            "childRegnum": child_regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetChildBirthResponse, data)
