"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS300184_MultiLicenseInfo (health, Эрүүл мэндийн хөгжлийн төв)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS300184_MultiLicenseInfo"


class MultiLicenseInfoLicenses(XypModel):
    """Лицензийн жагсаалт"""

    license_number: str | None = Field(
        default=None, alias="licenseNumber", description="Лицензийн дугаар"
    )
    license_type: str | None = Field(
        default=None, alias="licenseType", description="Лицензийн төрөл"
    )
    exp_date: str | None = Field(
        default=None, alias="expDate", description="Лицензийн хүчинтэй хугацаа дуусах YYYY-MM-DD"
    )
    license_state: str | None = Field(
        default=None, alias="licenseState", description="Лицензийн төлөв"
    )
    valid_start: str | None = Field(
        default=None, alias="validStart", description="Лицензийн хүчинтэй хугацаа эхлэх YYYY-MM-DD"
    )


class MultiLicenseInfoResponse(XypModel):
    """WS300184_MultiLicenseInfo: Нэг болон түүнээс дээш лицензтэй хүний мэдээлэл шалгах"""

    lastname: str | None = Field(default=None, alias="lastname", description="Иргэний овог")
    firstname: str | None = Field(default=None, alias="firstname", description="Иргэний нэр")
    licenses: list[MultiLicenseInfoLicenses] | None = Field(
        default=None, alias="licenses", description="Лицензийн жагсаалт"
    )


def multi_license_info(
    self: SyncService,
    *,
    regnum: str | None = None,
    civil_id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> MultiLicenseInfoResponse:
    """WS300184_MultiLicenseInfo: Нэг болон түүнээс дээш лицензтэй хүний мэдээлэл шалгах

    Provider: Эрүүл мэндийн хөгжлийн төв

    Args:
        regnum: Иргэний регистрийн дугаар
        civil_id: Иргэний бүртгэлийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "civilId": civil_id,
        },
        auth,
        operator,
    )
    return parse_model(MultiLicenseInfoResponse, data)


async def multi_license_info_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    civil_id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> MultiLicenseInfoResponse:
    """WS300184_MultiLicenseInfo: Нэг болон түүнээс дээш лицензтэй хүний мэдээлэл шалгах

    Provider: Эрүүл мэндийн хөгжлийн төв

    Args:
        regnum: Иргэний регистрийн дугаар
        civil_id: Иргэний бүртгэлийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "civilId": civil_id,
        },
        auth,
        operator,
    )
    return parse_model(MultiLicenseInfoResponse, data)
