<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Insurance;

use Xyp\Extras;

/**
 * Response of WS100512_checkIsInsuredInfo: Нийгмийн даатгалд даатгуусан эсэх.
 *
 * Provider: Нийгмийн даатгалын ерөнхий газар
 */
final readonly class CheckIsInsuredInfoResponse
{
    /**
     * @param bool|null $insured Даатгуулсан эсэх
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?bool $insured = null,
        public Extras $xyp = new Extras(),
    ) {}
}
