<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Insurance;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of WS100507_getInsureeWorkHistoryInfo: Даатгуулагчийн сүүлийн таван жил ажилласан түүх дамжуулах сервис.
 *
 * Provider: Нийгмийн даатгалын ерөнхий газар
 */
final readonly class GetInsureeWorkHistoryInfoResponse
{
    /**
     * @param list<mixed> $listData Сүүлийн таван жилийн ажилласан түүхийн жагсаалт
     * @param string|null $firstName Нэр
     * @param string|null $lastName Овог
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        #[ListOf('any')]
        public array $listData = [],
        public ?string $firstName = null,
        public ?string $lastName = null,
        public Extras $xyp = new Extras(),
    ) {}
}
