"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS400115_BasicEducationCertificateSupplementEn (education, Боловсролын мэдээллийн технологийн Төв)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS400115_BasicEducationCertificateSupplementEn"


class BasicEducationCertificateSupplementEnElectiveGradeLists(XypModel):
    """Жагсаалт"""

    enrollment_category_code: str | None = Field(
        default=None, alias="enrollmentCategoryCode", description="Судлагдахууны төрлийн код"
    )
    subject_area_id: int | None = Field(
        default=None, alias="subjectAreaId", description="Судлагдахууны дугаар"
    )
    course_name: str | None = Field(default=None, alias="courseName", description="Хичээлийн нэр")
    course_grade: str | None = Field(default=None, alias="courseGrade", description="Хичээлийн дүн")


class BasicEducationCertificateSupplementEnMandatoryGradeLists(XypModel):
    """Жагсаалт"""

    enrollment_category_code: str | None = Field(
        default=None, alias="enrollmentCategoryCode", description="Судлагдахууны төрлийн код"
    )
    subject_area_id: int | None = Field(
        default=None, alias="subjectAreaId", description="Судлагдахууны дугаар"
    )
    course_name: str | None = Field(default=None, alias="courseName", description="Хичээлийн нэр")
    course_grade: str | None = Field(default=None, alias="courseGrade", description="Хичээлийн дүн")


class BasicEducationCertificateSupplementEnExamList(XypModel):
    """Жагсаалт"""

    exam_name: str | None = Field(default=None, alias="examName", description="Шалгалтын нэр")
    score: str | None = Field(default=None, alias="score", description="Шалгалтын оноо")
    exam_id: int | None = Field(default=None, alias="examId", description="Шалгалтын дугаар")


class BasicEducationCertificateSupplementEnResponse(XypModel):
    """WS400115_BasicEducationCertificateSupplementEn: Суурь боловсролын үнэмлэхний хавсралт лавлах /Англи хэлээр/"""

    elective_grade_lists: list[BasicEducationCertificateSupplementEnElectiveGradeLists] | None = (
        Field(default=None, alias="electiveGradeLists", description="Жагсаалт")
    )
    regnum: str | None = Field(default=None, alias="regnum", description="Регистрийн дугаар")
    last_name: str | None = Field(default=None, alias="lastName", description="Эцэг/эхийн нэр")
    first_name: str | None = Field(default=None, alias="firstName", description="Өөрийн нэр")
    institution_id: int | None = Field(
        default=None, alias="institutionId", description="Байгууллагын дугаар"
    )
    institution_name: str | None = Field(
        default=None, alias="institutionName", description="Байгууллагын нэр"
    )
    org_regnum: str | None = Field(
        default=None, alias="orgRegnum", description="Байгууллагын Регистрийн дугаар"
    )
    degree_name: str | None = Field(
        default=None, alias="degreeName", description="Боловсролын баримт бичгийн төрлийн нэр"
    )
    confer_academic_year: str | None = Field(
        default=None, alias="conferAcademicYear", description="Төгссөн хичээлийн жил"
    )
    confer_date: str | None = Field(default=None, alias="conferDate", description="Төгссөн огноо")
    mandatory_grade_lists: list[BasicEducationCertificateSupplementEnMandatoryGradeLists] | None = (
        Field(default=None, alias="mandatoryGradeLists", description="Жагсаалт")
    )
    exam_list: list[BasicEducationCertificateSupplementEnExamList] | None = Field(
        default=None, alias="examList", description="Жагсаалт"
    )
    degree_id_number: str | None = Field(
        default=None,
        alias="degreeIdNumber",
        description="Боловсролын баримт бичгийн төрлийн дугаар",
    )
    family_name: str | None = Field(default=None, alias="familyName", description="Ургийн овог")


def basic_education_certificate_supplement_en(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> BasicEducationCertificateSupplementEnResponse:
    """WS400115_BasicEducationCertificateSupplementEn: Суурь боловсролын үнэмлэхний хавсралт лавлах /Англи хэлээр/

    Provider: Боловсролын мэдээллийн технологийн Төв

    Args:
        regnum: Регистр
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(BasicEducationCertificateSupplementEnResponse, data)


async def basic_education_certificate_supplement_en_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> BasicEducationCertificateSupplementEnResponse:
    """WS400115_BasicEducationCertificateSupplementEn: Суурь боловсролын үнэмлэхний хавсралт лавлах /Англи хэлээр/

    Provider: Боловсролын мэдээллийн технологийн Төв

    Args:
        regnum: Регистр
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(BasicEducationCertificateSupplementEnResponse, data)
