"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS400101_ueeReferenceService (education, Боловсрол шинжлэх ухааны яам)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS400101_ueeReferenceService"


class UeeReferenceServiceResponse(XypModel):
    """WS400101_ueeReferenceService: БОЛОВСРОЛЫН ҮНЭЛГЭЭНИЙ ТӨВ ЭЛСЭЛТИЙН ЕРӨНХИЙ ШАЛГАЛТЫН ЛАВЛАГАА"""

    reference_id: str | None = Field(
        default=None, alias="referenceId", description="лавлагааны дугаар"
    )
    regnum: str | None = Field(default=None, alias="regnum", description="регистр")
    lastname: str | None = Field(default=None, alias="lastname", description="овог")
    firstname: str | None = Field(default=None, alias="firstname", description="нэр")


def uee_reference_service(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> UeeReferenceServiceResponse:
    """WS400101_ueeReferenceService: БОЛОВСРОЛЫН ҮНЭЛГЭЭНИЙ ТӨВ ЭЛСЭЛТИЙН ЕРӨНХИЙ ШАЛГАЛТЫН ЛАВЛАГАА

    Provider: Боловсрол шинжлэх ухааны яам

    Args:
        regnum: регистрийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(UeeReferenceServiceResponse, data)


async def uee_reference_service_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> UeeReferenceServiceResponse:
    """WS400101_ueeReferenceService: БОЛОВСРОЛЫН ҮНЭЛГЭЭНИЙ ТӨВ ЭЛСЭЛТИЙН ЕРӨНХИЙ ШАЛГАЛТЫН ЛАВЛАГАА

    Provider: Боловсрол шинжлэх ухааны яам

    Args:
        regnum: регистрийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(UeeReferenceServiceResponse, data)
