<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

/**
 * `listData` in the response of WS100111_aimagCityInfo.
 */
final readonly class AimagCityInfoListData
{
    /**
     * @param string|null $aimagCityCode
     * @param string|null $aimagCityName
     */
    public function __construct(
        public ?string $aimagCityCode = null,
        public ?string $aimagCityName = null,
    ) {}
}
