<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

/**
 * `listData` in the response of WS100118_citizenBirthInfo.
 */
final readonly class CitizenBirthInfoListData
{
    /**
     * @param string|null $regnum
     * @param string|null $forename
     * @param string|null $surname
     * @param string|null $givenName
     * @param string|null $sexCode
     * @param string|null $sexName
     * @param string|null $birthDate
     * @param string|null $aimagCityCode
     * @param string|null $aimagCityName
     * @param string|null $soumDistrictCode
     * @param string|null $soumDistrctName
     * @param string|null $bagKhorooCode
     * @param string|null $bagKhorooName
     * @param string|null $fullAddress
     * @param string|null $motherRegnum
     * @param string|null $fatherRegnum
     * @param string|null $regDate
     * @param int|null $civilId
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $forename = null,
        public ?string $surname = null,
        public ?string $givenName = null,
        public ?string $sexCode = null,
        public ?string $sexName = null,
        public ?string $birthDate = null,
        public ?string $aimagCityCode = null,
        public ?string $aimagCityName = null,
        public ?string $soumDistrictCode = null,
        public ?string $soumDistrctName = null,
        public ?string $bagKhorooCode = null,
        public ?string $bagKhorooName = null,
        public ?string $fullAddress = null,
        public ?string $motherRegnum = null,
        public ?string $fatherRegnum = null,
        public ?string $regDate = null,
        public ?int $civilId = null,
    ) {}
}
