<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

use Xyp\Extras;

/**
 * Response of WS101124_citizenHighSchoolDescription: ерөнхий боловсролын сургуульд суралцаж байгаа тодорхойлолтийн мэдээлэл дуудах.
 *
 * Provider: Боловсрол шинжлэх ухааны яам
 */
final readonly class CitizenHighSchoolDescriptionResponse
{
    /**
     * @param string|null $regnum регистрийн дугаар
     * @param string|null $lastname овог
     * @param string|null $firstname нэр
     * @param string|null $academicYearFrom эхлэх хугацаа
     * @param string|null $academicYearTo дуусах хугацаа
     * @param string|null $schoolName сургуулийн нэр
     * @param string|null $academicLevelName анги
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $lastname = null,
        public ?string $firstname = null,
        public ?string $academicYearFrom = null,
        public ?string $academicYearTo = null,
        public ?string $schoolName = null,
        public ?string $academicLevelName = null,
        public Extras $xyp = new Extras(),
    ) {}
}
