<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

/**
 * Input of WS101187_CivilServiceEmployeeInfo: Төрийн албан хаагчийн мэдээлэл авах сервис.
 *
 * Provider: Төрийн албаны зөвлөл
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class CivilServiceEmployeeInfoParams
{
    /**
     * @param string|null $regnum Регистрийн дугаар
     * @param string|null $civilId Бүртгэлийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $civilId = null,
    ) {}
}
