<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

use Xyp\Date;
use Xyp\Extras;

/**
 * Response of WS100133_getCitizenDeceaseInfo: Нас барсны бүртгэлийн лавлагаа.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class GetCitizenDeceaseInfoResponse
{
    /**
     * @param string|null $regnum Иргэний
     * @param string|null $lastName Эцэг/эхийн
     * @param string|null $firstName Нэр
     * @param Date|null $deceaseDate Нас
     * @param string|null $deceaseCity Аймаг/Нийслэл
     * @param string|null $deceaseDistrict Сум/Дүүрэг
     * @param string|null $deceasePlaceName Нас
     * @param string|null $deceaseCauseName шалтгаан
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $lastName = null,
        public ?string $firstName = null,
        public ?Date $deceaseDate = null,
        public ?string $deceaseCity = null,
        public ?string $deceaseDistrict = null,
        public ?string $deceasePlaceName = null,
        public ?string $deceaseCauseName = null,
        public Extras $xyp = new Extras(),
    ) {}
}
