<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

use Xyp\Extras;

/**
 * Response of WS101158_GetStampReference: Тамга тэмдэгийн лавлагааны сервис.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class GetStampReferenceResponse
{
    /**
     * @param string|null $companyName Оноосон нэр
     * @param string|null $orgRegnum Хуулийн этгээдийн регистрийн дугаар
     * @param string|null $companyTypeName Хуулийн этгээдийн хэлбэр
     * @param string|null $description тамга,тэмдэг дахин авсан шалтгаан
     * @param string|null $stampNumber Тамга тэмдэгийн хяналтын дугаар
     * @param string|null $createdDate Бүртгэсэн огноо
     * @param string|null $isStamp тамга, тэмдэг эсэх
     * @param string|null $status Шинэ, дахин
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $companyName = null,
        public ?string $orgRegnum = null,
        public ?string $companyTypeName = null,
        public ?string $description = null,
        public ?string $stampNumber = null,
        public ?string $createdDate = null,
        public ?string $isStamp = null,
        public ?string $status = null,
        public Extras $xyp = new Extras(),
    ) {}
}
