<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

/**
 * Жагсаалт
 *
 * `listData` in the response of WS102101_RegnumInfoEnglish.
 */
final readonly class RegnumInfoEnglishListData
{
    /**
     * @param string|null $regnum Регистрийн дугаар
     * @param string|null $forename Овог (англи)
     * @param string|null $surname Эцгийн нэр (англи)
     * @param string|null $givenName Өөрийн нэр (англи)
     * @param string|null $birthDate Төрсөн огноо
     * @param string|null $sexName Хүйс
     * @param int|null $civilId Бүртгэлийн дугаар
     * @param string|null $citizenship Иргэншил
     */
    public function __construct(
        public ?string $regnum = null,
        public ?string $forename = null,
        public ?string $surname = null,
        public ?string $givenName = null,
        public ?string $birthDate = null,
        public ?string $sexName = null,
        public ?int $civilId = null,
        public ?string $citizenship = null,
    ) {}
}
