<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Citizen;

use Xyp\Extras;

/**
 * Response of WS101157_SVCMarriageRestores: Гэрлэлт сэргээсний бүртгэлийн лавлагаа.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class SVCMarriageRestoresResponse
{
    /**
     * @param string|null $regId
     * @param string|null $husNationalityName
     * @param string|null $husRegnum
     * @param string|null $wiNationalityName
     * @param string|null $wiRegnum
     * @param string|null $husGivenName
     * @param string|null $husStatus
     * @param string|null $wiRegisteredNum
     * @param string|null $marriedDate
     * @param string|null $wiSurname
     * @param string|null $wiForename
     * @param string|null $wiGivenName
     * @param string|null $decisionDate
     * @param string|null $regCity
     * @param string|null $husRegisteredNum
     * @param string|null $husForename
     * @param string|null $husSurname
     * @param string|null $wiStatus
     * @param string|null $decisionOrg
     * @param string|null $decisionNum
     * @param string|null $regDistrict
     * @param string|null $regDate
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?string $regId = null,
        public ?string $husNationalityName = null,
        public ?string $husRegnum = null,
        public ?string $wiNationalityName = null,
        public ?string $wiRegnum = null,
        public ?string $husGivenName = null,
        public ?string $husStatus = null,
        public ?string $wiRegisteredNum = null,
        public ?string $marriedDate = null,
        public ?string $wiSurname = null,
        public ?string $wiForename = null,
        public ?string $wiGivenName = null,
        public ?string $decisionDate = null,
        public ?string $regCity = null,
        public ?string $husRegisteredNum = null,
        public ?string $husForename = null,
        public ?string $husSurname = null,
        public ?string $wiStatus = null,
        public ?string $decisionOrg = null,
        public ?string $decisionNum = null,
        public ?string $regDistrict = null,
        public ?string $regDate = null,
        public Extras $xyp = new Extras(),
    ) {}
}
