"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100202_getPropertyList (property, Улсын бүртгэлийн ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100202_getPropertyList"


class GetPropertyListListData(XypModel):
    property_nation_register_number: str | None = Field(
        default=None, alias="propertyNationRegisterNumber"
    )
    code_name: str | None = Field(default=None, alias="codeName")
    code: str | None = Field(default=None, alias="code")
    property_size: str | None = Field(default=None, alias="propertySize")
    property_service_id: str | None = Field(default=None, alias="propertyServiceId")
    service_name: str | None = Field(default=None, alias="serviceName")
    service_type: str | None = Field(default=None, alias="serviceType")
    service_date: str | None = Field(default=None, alias="serviceDate")
    person_corp_id: str | None = Field(default=None, alias="personCorpId")
    lastname: str | None = Field(default=None, alias="lastname")
    firstname: str | None = Field(default=None, alias="firstname")
    person_name_corp: str | None = Field(default=None, alias="personNameCorp")
    ownership_status: str | None = Field(default=None, alias="ownershipStatus")
    ownership_id: str | None = Field(default=None, alias="ownershipId")
    full_address: str | None = Field(default=None, alias="fullAddress")
    moved_date: str | None = Field(default=None, alias="movedDate")
    moved_count: int | None = Field(default=None, alias="movedCount")
    moved_justification: str | None = Field(default=None, alias="movedJustification")


class GetPropertyListResponse(XypModel):
    """WS100202_getPropertyList: Үл хөдлөх хөрөнгийн жагсаалт авах сервис"""

    list_data: list[GetPropertyListListData] | None = Field(default=None, alias="listData")


def get_property_list(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetPropertyListResponse:
    """WS100202_getPropertyList: Үл хөдлөх хөрөнгийн жагсаалт авах сервис

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        regnum: regnum
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetPropertyListResponse, data)


async def get_property_list_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetPropertyListResponse:
    """WS100202_getPropertyList: Үл хөдлөх хөрөнгийн жагсаалт авах сервис

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        regnum: regnum
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(GetPropertyListResponse, data)
