"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100328_checkLegalEntityNameInfo (legal_entity, Улсын бүртгэлийн ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100328_checkLegalEntityNameInfo"


class CheckLegalEntityNameInfoResponse(XypModel):
    """WS100328_checkLegalEntityNameInfo: Хуулийн этгээдийн нэр буцаах сервис"""

    legal_entity_name: str | None = Field(
        default=None, alias="legalEntityName", description="Хуулийн этгээдийн нэр"
    )


def check_legal_entity_name_info(
    self: SyncService,
    *,
    legal_entity_number: int | None = None,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> CheckLegalEntityNameInfoResponse:
    """WS100328_checkLegalEntityNameInfo: Хуулийн этгээдийн нэр буцаах сервис

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        legal_entity_number: Хуулийн этгээдийн дугаар
        regnum: регистрийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "legalEntityNumber": legal_entity_number,
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(CheckLegalEntityNameInfoResponse, data)


async def check_legal_entity_name_info_async(
    self: AsyncService,
    *,
    legal_entity_number: int | None = None,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> CheckLegalEntityNameInfoResponse:
    """WS100328_checkLegalEntityNameInfo: Хуулийн этгээдийн нэр буцаах сервис

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        legal_entity_number: Хуулийн этгээдийн дугаар
        regnum: регистрийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "legalEntityNumber": legal_entity_number,
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(CheckLegalEntityNameInfoResponse, data)
