"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100324_legalEntityGeneralInfo (legal_entity, Улсын бүртгэлийн ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100324_legalEntityGeneralInfo"


class LegalEntityGeneralInfoResponse(XypModel):
    """WS100324_legalEntityGeneralInfo: Хуулийн этгээдийн үндсэн мэдээлэл"""

    company_regnum: str | None = Field(
        default=None, alias="companyRegnum", description="Хуулийн этгээдийн регистрийн дугаар"
    )
    company_name: str | None = Field(default=None, alias="companyName", description="Оноосон нэр")
    department_name: str | None = Field(
        default=None,
        alias="departmentName",
        description="Улсын бүртгэлд бүртгэсэн байгууллагын нэр",
    )
    decision_number: str | None = Field(
        default=None,
        alias="decisionNumber",
        description="Улсын бүртгэлд бүртгэсэн шийдвэрийн дугаар",
    )
    decision_date: str | None = Field(
        default=None, alias="decisionDate", description="Улсын бүртгэлд бүртгэсэн шийдвэрийн огноо"
    )
    created_date: str | None = Field(
        default=None, alias="createdDate", description="Улсын бүртгэлд бүртгэсэн бүртгэсэн огноо"
    )
    created_user_name: str | None = Field(
        default=None,
        alias="createdUserName",
        description="Улсын бүртгэлд бүртгэсэн бүртгэсэн ажилтан",
    )
    state_regnum: str | None = Field(
        default=None, alias="stateRegnum", description="Хувийн хэргийн дугаар"
    )
    profit_type_name: str | None = Field(
        default=None, alias="profitTypeName", description="Хуулийн этгээдийн төрөл"
    )
    description: str | None = Field(
        default=None, alias="description", description="Хуулийн этгээдийн хэлбэр"
    )
    description_code: str | None = Field(
        default=None, alias="descriptionCode", description="Хуулийн этгээдийн код"
    )
    ownership_type_name: str | None = Field(
        default=None, alias="ownershipTypeName", description="Өмчийн хэлбэр"
    )
    ownership_type_code: str | None = Field(
        default=None, alias="ownershipTypeCode", description="Өмчийн хэлбэр"
    )
    company_founder_count: int | None = Field(
        default=None, alias="companyFounderCount", description="Хувьцаа эзсмшигч, гишүүний тоо"
    )
    founder_document_name: str | None = Field(
        default=None, alias="founderDocumentName", description="Үүсгэн байгуулах баримт бичгийн нэр"
    )
    founder_decision_name: str | None = Field(
        default=None, alias="founderDecisionName", description="Үүсгэн байгуулах шийдвэрийн нэр"
    )
    founder_decision_number: str | None = Field(
        default=None,
        alias="founderDecisionNumber",
        description="Үүсгэн байгуулах шийдвэрийн дугаар",
    )
    regulation_date: str | None = Field(
        default=None, alias="regulationDate", description="Үүсгэн байгуулах дурмийн огноо"
    )
    contract_date: str | None = Field(
        default=None, alias="contractDate", description="Үүсгэн байгуулах гэрээний огноо"
    )


def legal_entity_general_info(
    self: SyncService,
    *,
    legal_entity_number: int | None = None,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> LegalEntityGeneralInfoResponse:
    """WS100324_legalEntityGeneralInfo: Хуулийн этгээдийн үндсэн мэдээлэл

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        legal_entity_number: Хуулийн этгээдийн дугаар
        regnum: регистрийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "legalEntityNumber": legal_entity_number,
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(LegalEntityGeneralInfoResponse, data)


async def legal_entity_general_info_async(
    self: AsyncService,
    *,
    legal_entity_number: int | None = None,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> LegalEntityGeneralInfoResponse:
    """WS100324_legalEntityGeneralInfo: Хуулийн этгээдийн үндсэн мэдээлэл

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        legal_entity_number: Хуулийн этгээдийн дугаар
        regnum: регистрийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "legalEntityNumber": legal_entity_number,
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(LegalEntityGeneralInfoResponse, data)
