// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package payment

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// CitizenBSLoanInfoParams is the input of WS100839_citizenBSLoanInfo. Every field is
// optional; a zero value is left out of the request.
type CitizenBSLoanInfoParams struct {
	Regnum        string `xyp:"regnum"`
	Purpose       string `xyp:"purpose"`
	IsForeign     *bool  `xyp:"isForeign"`
	LiveStockYear *int64 `xyp:"liveStockYear"`
}

// CitizenBSLoanInfoResponse is the response of WS100839_citizenBSLoanInfo: Бүрэн Скор Зээлийн Мэдээллийн сервис.
type CitizenBSLoanInfoResponse struct {
	// Нэр
	Firstname string `xyp:"firstname"`
	// Овог
	Lastname string `xyp:"lastname"`
	// Хаяг
	Address string `xyp:"address"`
	// Регистрийн дугаар
	Regnum string `xyp:"regnum"`
	// Ургийн овог
	Familyname string `xyp:"familyname"`
	// Яс, үндэс
	Nationality string `xyp:"nationality"`
	// Зээлийн тоо
	Count *int64 `xyp:"count"`
	// Зээлийн мэдээллүүд
	Inquiry any `xyp:"inquiry"`
	// Малын А данс
	LiveStockData []any `xyp:"liveStockData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// CitizenBSLoanInfo calls WS100839_citizenBSLoanInfo: Бүрэн Скор Зээлийн Мэдээллийн сервис
//
// Provider: Бүрэн Скор ЗМС ХХК
func (s *Service) CitizenBSLoanInfo(ctx context.Context, params CitizenBSLoanInfoParams, opts ...xyp.CallOption) (*CitizenBSLoanInfoResponse, error) {
	var out CitizenBSLoanInfoResponse
	extras, err := s.client.Invoke(ctx, "WS100839_citizenBSLoanInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
