// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package payment

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// TaxReceiptBankByRegnumParams is the input of WS100838_taxReceiptBankByRegnum. Every field is
// optional; a zero value is left out of the request.
type TaxReceiptBankByRegnumParams struct {
	// Суутган төлөгч байгууллагын татвар төлөгчийн дугаар
	AuthorityPin string `xyp:"authorityPin"`
	// Татварын төрлийн код
	TaxTypeCode string `xyp:"taxTypeCode"`
	// Төрийн сан дахь татварын орлогын данс
	StateAccount string `xyp:"stateAccount"`
	// Төлбөрийн дүн
	Amount string `xyp:"amount"`
	// Татвар төлөгчийн утасны дугаар
	PhoneNo string `xyp:"phoneNo"`
	// цахим шуудан
	Email string `xyp:"email"`
	// Татвар төлөгчийн регистрийн дугаар
	Regnum string `xyp:"regnum"`
	// салбарын код
	BranchCode string `xyp:"branchCode"`
	// дэд салбарын код
	SubBranchCode string `xyp:"subBranchCode"`
	// Тайлбар
	Description string `xyp:"description"`
	// төрөл
	Type string `xyp:"type"`
}

// TaxReceiptBankByRegnumResponse is the response of WS100838_taxReceiptBankByRegnum: Регистрийн дугаараар нэхэмжлэх үүсгэх сервис.
type TaxReceiptBankByRegnumResponse struct {
	// ”Цахим төлбөрийн даалгавар”-ын дугаар
	InvoiceNo string `xyp:"invoiceNo"`
	// нэмэжлэлийн төрөл
	InvoiceType string `xyp:"invoiceType"`
	// Үүссэн огноо
	CreatedDate string `xyp:"createdDate"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// TaxReceiptBankByRegnum calls WS100838_taxReceiptBankByRegnum: Регистрийн дугаараар нэхэмжлэх үүсгэх сервис
//
// Provider: Татварын ерөнхий газар
func (s *Service) TaxReceiptBankByRegnum(ctx context.Context, params TaxReceiptBankByRegnumParams, opts ...xyp.CallOption) (*TaxReceiptBankByRegnumResponse, error) {
	var out TaxReceiptBankByRegnumResponse
	extras, err := s.client.Invoke(ctx, "WS100838_taxReceiptBankByRegnum", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
