// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.transport;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import io.github.baljinnyamday.xyp.XypDate;
import java.util.List;

/**
 * The response of {@code WS100420_getOrganizationVehicleList}: Байгууллагын регистрийн дугаараар
 * машины жагсаалт дуудах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData Мэдээллийн жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record GetOrganizationVehicleListResponse(List<ListData> listData, Extras extras) {

  static GetOrganizationVehicleListResponse decode(ResponseReader reader) {
    return new GetOrganizationVehicleListResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * Мэдээллийн жагсаалт.
   *
   * @param plateNumber Улсын дугаар
   * @param cabinNumber Арлын дугаар
   * @param countryName Улсын нэр
   * @param markName Марк
   * @param modelName Модел
   * @param type Төрөл
   * @param typeId Төрлийн дугаар
   * @param className ангилал
   * @param manCount суудлийн тоо
   * @param wheelPosition хүрдний байрлал
   * @param weight жин
   * @param mass нийт жин
   * @param fueltype түлшний төрөл
   * @param length урд
   * @param width өргөн
   * @param height өндөр
   * @param capacity багтаамж
   * @param motorNumber моторын дугаар
   * @param colorName өнгө
   * @param axleCount тэнхлэгийн тоо
   * @param certificateNumber гэрчилгээний дугаар
   * @param importDate импортоор орж ирсэн огноо
   * @param intent интент
   * @param transmission трансмишн
   * @param buildYear үйлдвэрлэсэн он
   * @param holderCountry эзэмшигчийн улс
   * @param holderRegnum эзэмшигчийн регистрийн дугаар
   * @param holderType эзэмшигчийн төрөл
   * @param holderFirstname эзэмшигчийн нэр
   * @param holderLastname эзэмшигчийн овог
   * @param holderHomephone эзэмшигчийн утасны дугаар
   * @param holderWorkphone эзэмшигчийн утасны дугаар
   * @param holderHandphone эзэмшигчийн утасны дугаар
   * @param holderAddress эзэмшигчийн Бүрэн хаяг
   * @param archiveDate архивласан огноо
   * @param archiveFirstNumber архивласан дугаар
   * @param archiveNumber архивласан дугаар
   * @param startDate өмчлөж эхэсэн огноо
   * @param rfidTag Шошгоны хаяг
   * @param inspAmount Үзлэгийн үнэ
   * @param inspVat Үзлэгийн НӨАТ
   * @param declarationNum Гаалийн мэдүүлгийн дугаар
   * @param modificaceName Өөрчлөлт
   * @param holderId Эзэмшигчийн id
   * @param vehicleId Тээврийн хэрэгслийн id
   * @param purposeId Зориулалт id
   * @param purposeName Зориулалтын нэр
   * @param ownerId Өмчлөгчийн код
   */
  public record ListData(
      String plateNumber,
      String cabinNumber,
      String countryName,
      String markName,
      String modelName,
      String type,
      Long typeId,
      String className,
      Long manCount,
      String wheelPosition,
      Double weight,
      Double mass,
      String fueltype,
      Double length,
      Double width,
      Double height,
      Double capacity,
      String motorNumber,
      String colorName,
      Long axleCount,
      String certificateNumber,
      XypDate importDate,
      String intent,
      String transmission,
      Long buildYear,
      String holderCountry,
      String holderRegnum,
      String holderType,
      String holderFirstname,
      String holderLastname,
      String holderHomephone,
      String holderWorkphone,
      String holderHandphone,
      List<Object> holderAddress,
      XypDate archiveDate,
      String archiveFirstNumber,
      String archiveNumber,
      XypDate startDate,
      String rfidTag,
      String inspAmount,
      String inspVat,
      String declarationNum,
      String modificaceName,
      String holderId,
      String vehicleId,
      String purposeId,
      String purposeName,
      Long ownerId) {

    static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("plateNumber", Decoders.STRING),
          reader.get("cabinNumber", Decoders.STRING),
          reader.get("countryName", Decoders.STRING),
          reader.get("markName", Decoders.STRING),
          reader.get("modelName", Decoders.STRING),
          reader.get("type", Decoders.STRING),
          reader.get("typeId", Decoders.INT),
          reader.get("className", Decoders.STRING),
          reader.get("manCount", Decoders.INT),
          reader.get("wheelPosition", Decoders.STRING),
          reader.get("weight", Decoders.FLOAT),
          reader.get("mass", Decoders.FLOAT),
          reader.get("fueltype", Decoders.STRING),
          reader.get("length", Decoders.FLOAT),
          reader.get("width", Decoders.FLOAT),
          reader.get("height", Decoders.FLOAT),
          reader.get("capacity", Decoders.FLOAT),
          reader.get("motorNumber", Decoders.STRING),
          reader.get("colorName", Decoders.STRING),
          reader.get("axleCount", Decoders.INT),
          reader.get("certificateNumber", Decoders.STRING),
          reader.get("importDate", Decoders.DATE),
          reader.get("intent", Decoders.STRING),
          reader.get("transmission", Decoders.STRING),
          reader.get("buildYear", Decoders.INT),
          reader.get("holderCountry", Decoders.STRING),
          reader.get("holderRegnum", Decoders.STRING),
          reader.get("holderType", Decoders.STRING),
          reader.get("holderFirstname", Decoders.STRING),
          reader.get("holderLastname", Decoders.STRING),
          reader.get("holderHomephone", Decoders.STRING),
          reader.get("holderWorkphone", Decoders.STRING),
          reader.get("holderHandphone", Decoders.STRING),
          reader.get("holderAddress", Decoders.list(Decoders.ANY)),
          reader.get("archiveDate", Decoders.DATE),
          reader.get("archiveFirstNumber", Decoders.STRING),
          reader.get("archiveNumber", Decoders.STRING),
          reader.get("startDate", Decoders.DATE),
          reader.get("rfidTag", Decoders.STRING),
          reader.get("inspAmount", Decoders.STRING),
          reader.get("inspVat", Decoders.STRING),
          reader.get("declarationNum", Decoders.STRING),
          reader.get("modificaceName", Decoders.STRING),
          reader.get("holderId", Decoders.STRING),
          reader.get("vehicleId", Decoders.STRING),
          reader.get("purposeId", Decoders.STRING),
          reader.get("purposeName", Decoders.STRING),
          reader.get("ownerId", Decoders.INT));
    }
  }
}
