// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.transport;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import io.github.baljinnyamday.xyp.XypDate;

/**
 * The response of {@code WS101404_ProfessionalDriverLicenseEnglishInfo}: Мэргэшсэн жолоочийн
 * үнэмлэхний лавлагаа англи сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param id Жолоочийн ID
 * @param register Регистрийн дугаар
 * @param licenseNumber Жолооны үнэмлэхний дугаар
 * @param surname Ургийн овог
 * @param lastname Эцэг/эхийн нэр
 * @param firstname Өөрийн нэр
 * @param surnameEn Ургийн овог /англи/
 * @param lastnameEn Эцэг/эхийн нэр /англи/
 * @param firstnameEn Өөрийн нэр /англи/
 * @param birthdate Төрсөн огноо
 * @param gender Хүйс код
 * @param classB Мэргэшсэн жолоочийн B ангилал олгосон огноо
 * @param classC Мэргэшсэн жолоочийн C ангилал олгосон огноо
 * @param classD Мэргэшсэн жолоочийн D ангилал олгосон огноо
 * @param classE Мэргэшсэн жолоочийн E ангилал олгосон огноо
 * @param classTourist Жуулчин тээвэрлэх ангилал олгосон огноо
 * @param classDanger Аюултай ачаа тээвэрлэх ангилал олгосон огноо
 * @param classInterPassanger Олон улсын зорчигч тээвэрлэх ангилал олгосон огноо
 * @param classInterTransport Олон улсын ачаа тээвэрлэх ангилал олгосон огноо
 * @param epdlNumber Мэргэшсэн жолоочийн цахим үнэмлэхний дугаар
 * @param countryName Иргэншил /улсын нэр/
 * @param eyeColor Нүдний өнгө
 * @param eyeColorCode Нүдний өнгө код
 * @param bloodType Цусны бүлэг
 * @param pdlNumber Мэргэшсэн жолоочийн үнэмлэхний дугаар
 * @param haveLicense Үнэмлэхтэй эсэх
 * @param image Жолоочийн зураг
 * @param genderName Хүйс /англи/
 * @param genderCode Хүйс товчлол /M, F/
 * @param countryCode Улсын код /ISO, жнь MNG/
 * @param pictureUrl Жолоочийн зургийн холбоос
 * @param signatureUrl Гарын үсгийн зургийн холбоос
 * @param dlA Жолооны үнэмлэхний A ангилал олгосон огноо
 * @param dlB Жолооны үнэмлэхний B ангилал олгосон огноо
 * @param dlC Жолооны үнэмлэхний C ангилал олгосон огноо
 * @param dlD Жолооны үнэмлэхний D ангилал олгосон огноо
 * @param dlE Жолооны үнэмлэхний E ангилал олгосон огноо
 * @param dlM Жолооны үнэмлэхний M ангилал олгосон огноо
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record ProfessionalDriverLicenseEnglishInfoResponse(
    Long id,
    String register,
    Long licenseNumber,
    String surname,
    String lastname,
    String firstname,
    String surnameEn,
    String lastnameEn,
    String firstnameEn,
    XypDate birthdate,
    String gender,
    XypDate classB,
    XypDate classC,
    XypDate classD,
    XypDate classE,
    XypDate classTourist,
    XypDate classDanger,
    XypDate classInterPassanger,
    XypDate classInterTransport,
    String epdlNumber,
    String countryName,
    String eyeColor,
    String eyeColorCode,
    String bloodType,
    String pdlNumber,
    Long haveLicense,
    byte[] image,
    String genderName,
    String genderCode,
    String countryCode,
    String pictureUrl,
    String signatureUrl,
    String dlA,
    String dlB,
    String dlC,
    String dlD,
    String dlE,
    String dlM,
    Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static ProfessionalDriverLicenseEnglishInfoResponse decode(ResponseReader reader) {
    return new ProfessionalDriverLicenseEnglishInfoResponse(
        reader.get("id", Decoders.INT),
        reader.get("register", Decoders.STRING),
        reader.get("licenseNumber", Decoders.INT),
        reader.get("surname", Decoders.STRING),
        reader.get("lastname", Decoders.STRING),
        reader.get("firstname", Decoders.STRING),
        reader.get("surnameEn", Decoders.STRING),
        reader.get("lastnameEn", Decoders.STRING),
        reader.get("firstnameEn", Decoders.STRING),
        reader.get("birthdate", Decoders.DATE),
        reader.get("gender", Decoders.STRING),
        reader.get("classB", Decoders.DATE),
        reader.get("classC", Decoders.DATE),
        reader.get("classD", Decoders.DATE),
        reader.get("classE", Decoders.DATE),
        reader.get("classTourist", Decoders.DATE),
        reader.get("classDanger", Decoders.DATE),
        reader.get("classInterPassanger", Decoders.DATE),
        reader.get("classInterTransport", Decoders.DATE),
        reader.get("epdlNumber", Decoders.STRING),
        reader.get("countryName", Decoders.STRING),
        reader.get("eyeColor", Decoders.STRING),
        reader.get("eyeColorCode", Decoders.STRING),
        reader.get("bloodType", Decoders.STRING),
        reader.get("pdlNumber", Decoders.STRING),
        reader.get("haveLicense", Decoders.INT),
        reader.get("image", Decoders.BYTES),
        reader.get("genderName", Decoders.STRING),
        reader.get("genderCode", Decoders.STRING),
        reader.get("countryCode", Decoders.STRING),
        reader.get("pictureUrl", Decoders.STRING),
        reader.get("signatureUrl", Decoders.STRING),
        reader.get("dlA", Decoders.STRING),
        reader.get("dlB", Decoders.STRING),
        reader.get("dlC", Decoders.STRING),
        reader.get("dlD", Decoders.STRING),
        reader.get("dlE", Decoders.STRING),
        reader.get("dlM", Decoders.STRING),
        reader.extras());
  }
}
