// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.transport;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS100441_umnsVehicleInfo}: ӨМНС тээврийн хэрэгслийн лавлагаа.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData мэдээллийн жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record UmnsVehicleInfoResponse(List<ListData> listData, Extras extras) {

  static UmnsVehicleInfoResponse decode(ResponseReader reader) {
    return new UmnsVehicleInfoResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * мэдээллийн жагсаалт.
   *
   * @param buildYear үйлдвэрлэсэн он
   * @param vehicleId төрлийн дугаар
   * @param isOwner эзэмшигч эсэх
   * @param purposeId зориулалтын дугаар
   * @param purposeName зориулалт
   * @param engineCapacity хөдөлгүүрийн багтаамж
   * @param ownerRegnum эзэмшигчийн регистр
   */
  public record ListData(
      Long buildYear,
      Long vehicleId,
      Long isOwner,
      Long purposeId,
      String purposeName,
      Long engineCapacity,
      String ownerRegnum) {

    static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("buildYear", Decoders.INT),
          reader.get("vehicleId", Decoders.INT),
          reader.get("isOwner", Decoders.INT),
          reader.get("purposeId", Decoders.INT),
          reader.get("purposeName", Decoders.STRING),
          reader.get("engineCapacity", Decoders.INT),
          reader.get("ownerRegnum", Decoders.STRING));
    }
  }
}
