<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\LaborWelfare;

/**
 * Input of WS100937_citizenInfoDisabilityCertified: Хөгжлийн бэрхшээлтэй иргэний баталгаажсан мэдээлэл.
 *
 * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class CitizenInfoDisabilityCertifiedParams
{
    /**
     * @param string|null $regnum регистер
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
