<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\LaborWelfare;

use Xyp\Auth;
use Xyp\XypClient;

/**
 * The 19 XYP services of the `labor_welfare` group, served from labor-welfare-1.5.0.
 *
 * Reached through `$xyp->laborWelfare`; every method sends one request through that XypClient.
 */
final class LaborWelfareService
{
    public function __construct(private readonly XypClient $client) {}

    /**
     * Calls WS100909_checkLetter: Байгууллагын регистрын дугаараар ХХҮЕГ-ын албан бичгийн дугаар, төрөл, оны мэдээлэл харах.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function checkLetter(
        CheckLetterParams $params = new CheckLetterParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): CheckLetterResponse {
        return $this->client->invoke(
            'WS100909_checkLetter',
            $params,
            CheckLetterResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100910_jobSeekerInfo: Ажил хайгч иргэдийн мэдээлэл өгөх сервес.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function jobSeekerInfo(
        JobSeekerInfoParams $params = new JobSeekerInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): JobSeekerInfoResponse {
        return $this->client->invoke(
            'WS100910_jobSeekerInfo',
            $params,
            JobSeekerInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100911_pensionInfo: Халамжийн тэтгэвэр авагчийн мэдээлэл.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function pensionInfo(
        PensionInfoParams $params = new PensionInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): PensionInfoResponse {
        return $this->client->invoke(
            'WS100911_pensionInfo',
            $params,
            PensionInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100916_getCitizenLaborInfo: Хөдөлмөрийн зах зээллийн мэдээллийн системд бүртгэлтэй иргэний мэдээлэл.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getCitizenLaborInfo(
        GetCitizenLaborInfoParams $params = new GetCitizenLaborInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetCitizenLaborInfoResponse {
        return $this->client->invoke(
            'WS100916_getCitizenLaborInfo',
            $params,
            GetCitizenLaborInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100918_getHouseholdInfoByRegnum: Өрхийн тэргүүлэгчийн регистрээр өрхийн мэдээлэл авах.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getHouseholdInfoByRegnum(
        GetHouseholdInfoByRegnumParams $params = new GetHouseholdInfoByRegnumParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetHouseholdInfoByRegnumResponse {
        return $this->client->invoke(
            'WS100918_getHouseholdInfoByRegnum',
            $params,
            GetHouseholdInfoByRegnumResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100919_getChildNotification: Мэдэгдэл авах сервис.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getChildNotification(
        GetChildNotificationParams $params = new GetChildNotificationParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetChildNotificationResponse {
        return $this->client->invoke(
            'WS100919_getChildNotification',
            $params,
            GetChildNotificationResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100920_getChildRequestInfo: Хүүхдийн мэдээлэл татах сервис.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getChildRequestInfo(
        GetChildRequestInfoParams $params = new GetChildRequestInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetChildRequestInfoResponse {
        return $this->client->invoke(
            'WS100920_getChildRequestInfo',
            $params,
            GetChildRequestInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100921_setChildRequest: Хадгалсан хүсэлт илгээх.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function setChildRequest(
        SetChildRequestParams $params = new SetChildRequestParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): SetChildRequestResponse {
        return $this->client->invoke(
            'WS100921_setChildRequest',
            $params,
            SetChildRequestResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100922_civilizedConfirmedServices: иргэний баталгаажсан үйлчилгээний мэдээлэл дуудах.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function civilizedConfirmedServices(
        CivilizedConfirmedServicesParams $params = new CivilizedConfirmedServicesParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): CivilizedConfirmedServicesResponse {
        return $this->client->invoke(
            'WS100922_civilizedConfirmedServices',
            $params,
            CivilizedConfirmedServicesResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100926_householdScoreInfo: Өрхийн оноотой холбоотой дэлгэрэнгүй мэдээлэл.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function householdScoreInfo(
        HouseholdScoreInfoParams $params = new HouseholdScoreInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): HouseholdScoreInfoResponse {
        return $this->client->invoke(
            'WS100926_householdScoreInfo',
            $params,
            HouseholdScoreInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100927_householdScoreCheck: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээх.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function householdScoreCheck(
        HouseholdScoreCheckParams $params = new HouseholdScoreCheckParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): HouseholdScoreCheckResponse {
        return $this->client->invoke(
            'WS100927_householdScoreCheck',
            $params,
            HouseholdScoreCheckResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100928_householdScoreCheckInfo: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээсэн эсэхийг шалгах.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function householdScoreCheckInfo(
        HouseholdScoreCheckInfoParams $params = new HouseholdScoreCheckInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): HouseholdScoreCheckInfoResponse {
        return $this->client->invoke(
            'WS100928_householdScoreCheckInfo',
            $params,
            HouseholdScoreCheckInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100929_householdScoreCalculateRequest: Өрхийн оноотой холбоотой мэдээлэл шалгуулах хүсэлт илгээх.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function householdScoreCalculateRequest(
        HouseholdScoreCalculateRequestParams $params = new HouseholdScoreCalculateRequestParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): HouseholdScoreCalculateRequestResponse {
        return $this->client->invoke(
            'WS100929_householdScoreCalculateRequest',
            $params,
            HouseholdScoreCalculateRequestResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100932_getTotalTransactionMonthly: Аймаг дүүргээр олголтын мэдээлэл лавлах сервис.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getTotalTransactionMonthly(
        GetTotalTransactionMonthlyParams $params = new GetTotalTransactionMonthlyParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetTotalTransactionMonthlyResponse {
        return $this->client->invoke(
            'WS100932_getTotalTransactionMonthly',
            $params,
            GetTotalTransactionMonthlyResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100936_setUserService: Хүүхдийн мөнгөн тэтгэмж үйлчилгээ бүртгэх сервис.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function setUserService(
        SetUserServiceParams $params = new SetUserServiceParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): SetUserServiceResponse {
        return $this->client->invoke(
            'WS100936_setUserService',
            $params,
            SetUserServiceResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100937_citizenInfoDisabilityCertified: Хөгжлийн бэрхшээлтэй иргэний баталгаажсан мэдээлэл.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function citizenInfoDisabilityCertified(
        CitizenInfoDisabilityCertifiedParams $params = new CitizenInfoDisabilityCertifiedParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): CitizenInfoDisabilityCertifiedResponse {
        return $this->client->invoke(
            'WS100937_citizenInfoDisabilityCertified',
            $params,
            CitizenInfoDisabilityCertifiedResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100938_getFosterParentServiceInfo: ХӨГЖЛИЙН БЭРХШЭЭЛТЭЙ ХҮҮХДЭЭ АСАРЧ АЖИЛ ХӨДӨЛМӨР ЭРХЛЭЭГҮЙ ЭЦЭГ, ЭХИЙН ҮЙЛЧИЛГЭЭНИЙ МЭДЭЭЛЭЛ ЛАВЛАХ.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getFosterParentServiceInfo(
        GetFosterParentServiceInfoParams $params = new GetFosterParentServiceInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetFosterParentServiceInfoResponse {
        return $this->client->invoke(
            'WS100938_getFosterParentServiceInfo',
            $params,
            GetFosterParentServiceInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100941_getServiceDocumentList: Үйлчилгээний бүрдүүлэх материал лавлах сервис.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getServiceDocumentList(
        GetServiceDocumentListParams $params = new GetServiceDocumentListParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetServiceDocumentListResponse {
        return $this->client->invoke(
            'WS100941_getServiceDocumentList',
            $params,
            GetServiceDocumentListResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100943_belowStandardLevelCitizen: Амьжиргааны баталгаажих түвшнээс доогуур оноотой иргэдийн мэдээллийг дуудах сервис.
     *
     * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function belowStandardLevelCitizen(
        BelowStandardLevelCitizenParams $params = new BelowStandardLevelCitizenParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): BelowStandardLevelCitizenResponse {
        return $this->client->invoke(
            'WS100943_belowStandardLevelCitizen',
            $params,
            BelowStandardLevelCitizenResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }
}
