// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

// Package legalentity holds the 19 XYP services of the `legal_entity` group,
// served from legal-entity-1.5.0.
//
//	import (
//		"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
//		"github.com/baljinnyamday/xyp-sdk/packages/go/xyp/legalentity"
//	)
//
//	client, err := xyp.NewClient(xyp.Options{})
//	service := legalentity.New(client)
package legalentity

import "github.com/baljinnyamday/xyp-sdk/packages/go/xyp"

// Service calls the `legal_entity` group's services through one shared client.
type Service struct{ client *xyp.Client }

// New binds this group's services to client, which stays owned by the caller.
func New(client *xyp.Client) *Service { return &Service{client: client} }
