// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package tax

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// TradeInfoParams is the input of WS100628_tradeInfo. Every field is
// optional; a zero value is left out of the request.
type TradeInfoParams struct {
	// жил
	Year string `xyp:"year"`
	// байгууллагын регистр
	OrgRegnum string `xyp:"orgRegnum"`
	// сар
	Month string `xyp:"month"`
}

// TradeInfoListData: мэдээллийн жагсаалт
type TradeInfoListData struct {
	// дугаар
	Id string `xyp:"id"`
	// Хуулийн этгээдийн регистрийн дугаар
	OrgRegnum string `xyp:"orgRegnum"`
	// Эзэмшигчийн нэр
	FounderName string `xyp:"founderName"`
	// Эзэшигчийн регистрийн дугаар
	FounderRegnum string `xyp:"founderRegnum"`
	// Бизнесийн оноосон нэр
	EntityName string `xyp:"entityName"`
	// Хариуцлагын хэлбэр
	ContractStatus string `xyp:"contractStatus"`
	// Үйл ажиллагааны чиглэл
	OperationCourse string `xyp:"operationCourse"`
	// Үйл ажиллагааны төрөл
	OperationType string `xyp:"operationType"`
	// Үйл ажиллагаа явуулж буй хаягийн мэдээлэл
	Address string `xyp:"address"`
	// Үйл ажиллагаа явуулж буй байршлын өргөрөг
	LocationLat *int64 `xyp:"locationLat"`
	// Үйл ажиллагаа явуулж буй байршлын уртраг
	LocationLng *int64 `xyp:"locationLng"`
	// Үйл ажиллагааны төлөв
	OperationStatus string `xyp:"operationStatus"`
	// Үйл ажиллагааны эрхлэх эрх олгосон огноо
	TradeContractDate xyp.Date `xyp:"tradeContractDate"`
	// Үйл ажиллагааны эрхлэх эрхийн дуусах огноо
	TradeContractEndDate xyp.Date `xyp:"tradeContractEndDate"`
	// Эрх олгосон олгосон байгууллага
	TradeContractOrganization string `xyp:"tradeContractOrganization"`
	// Зөвшөөрөл авагч ААН-ийн удирдлагын овог
	Lastname string `xyp:"lastname"`
	// Зөвшөөрөл авагч ААН-ийн удирдлагын нэр
	DirectorName string `xyp:"directorName"`
	// Зөвшөөрөл авагч ААН-ийн удирдлагын регистрийн дугаар
	DirectorRegnum string `xyp:"directorRegnum"`
}

// TradeInfoResponse is the response of WS100628_tradeInfo: Худалдаа үйлдвэрлэл, үйлчилгээний чиглэлээр үйл ажиллагаа эрхлэх чиглэл, төрөлтэй холбогдох мэдээлэл.
type TradeInfoResponse struct {
	// мэдээллийн жагсаалт
	ListData []TradeInfoListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// TradeInfo calls WS100628_tradeInfo: Худалдаа үйлдвэрлэл, үйлчилгээний чиглэлээр үйл ажиллагаа эрхлэх чиглэл, төрөлтэй холбогдох мэдээлэл
//
// Provider: Нийслэлийн засаг даргын тамгын газар
func (s *Service) TradeInfo(ctx context.Context, params TradeInfoParams, opts ...xyp.CallOption) (*TradeInfoResponse, error) {
	var out TradeInfoResponse
	extras, err := s.client.Invoke(ctx, "WS100628_tradeInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
