/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS100916_getCitizenLaborInfo (laborWelfare, Хөдөлмөр халамж, үйлчилгээний ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS100916_getCitizenLaborInfo";

/** Input of WS100916_getCitizenLaborInfo. */
export interface GetCitizenLaborInfoParams {
  /** регистрийн дугаар */
  readonly regnum?: string;
}

/** хаяг мэдээлэл */
export interface GetCitizenLaborInfoAddresses {
  /** аймгийн нэр */
  readonly provinceName: string | null;
  /** дүүргийн нэр */
  readonly districtName: string | null;
  /** дэд дүүргийн нэр */
  readonly subdistrictName: string | null;
  /** гудамжны нэр */
  readonly streetName: string | null;
  /** орон сууц */
  readonly apartment: string | null;
  /** хаалганы дугаар */
  readonly doorNumber: string | null;
  /** өргөрөг */
  readonly latitude: string | null;
  /** уртраг */
  readonly longitude: string | null;
  /** тайлбар */
  readonly description: string | null;
}

/** // */
export interface GetCitizenLaborInfoDesiredJobs {
  /** байршил */
  readonly locationTypeName: string | null;
  /** ажил */
  readonly jobTypeName: string | null;
  /** ажлын цаг */
  readonly workHourName: string | null;
  /** ажил мэргэжлийн нэр */
  readonly occupationName: string | null;
  /** цалингийн хэмжээ */
  readonly salaryRangeName: string | null;
  readonly roleInfo: string | null;
}

/** WS100916_getCitizenLaborInfo: Хөдөлмөрийн зах зээллийн мэдээллийн системд бүртгэлтэй иргэний мэдээлэл */
export interface GetCitizenLaborInfoResponse {
  /** үүсгэсэн огноо */
  readonly createdDate: string | null;
  /** төрөлийн код */
  readonly typeCode: string | null;
  /** гадаад */
  readonly abroad: boolean | null;
  /** дугаар */
  readonly id: number | null;
  /** боловсролын түвшний код */
  readonly educationLevelCode: string | null;
  /** боловсролын түвшний нэр */
  readonly educationLevelName: string | null;
  /** мэргэжлийн нэр */
  readonly professionName: string | null;
  /** чадварын Код */
  readonly abilityCode: string | null;
  /** Нэр */
  readonly firstName: string | null;
  /** төрсөн өдөр */
  readonly birthDate: string | null;
  /** хайгчийн төлөвийн дугаар */
  readonly seekerStatusCode: string | null;
  /** хайгчийн төлөвийн нэр */
  readonly seekerStatusName: string | null;
  /** хаяг мэдээлэл */
  readonly addresses: readonly GetCitizenLaborInfoAddresses[] | null;
  /** // */
  readonly desiredJobs: readonly GetCitizenLaborInfoDesiredJobs[] | null;
  /** // */
  readonly username: string | null;
  /** төлөвийн код */
  readonly statusCode: string | null;
  /** төлөвийн нэр */
  readonly statusName: string | null;
  /** шалтгаан нэр */
  readonly reasonName: string | null;
  /** чадвар */
  readonly abilityName: string | null;
  /** туршлагатай */
  readonly experienced: boolean | null;
  /** төрөлийн нэр */
  readonly typeName: string | null;
  /** регистер */
  readonly regnum: string | null;
  /** улсын бүртгэлийн дугаар */
  readonly civilId: string | null;
  /** Ургын овог */
  readonly surname: string | null;
  /** Овог */
  readonly lastName: string | null;
  /** хүйсийн код */
  readonly genderCode: string | null;
  /** хүйсийн нэр */
  readonly genderName: string | null;
  /** // */
  readonly purposeCode: string | null;
  /** // */
  readonly purposeName: string | null;
  /** утас */
  readonly phone: string | null;
  /** хайсан огноо */
  readonly soughtDate: string | null;
  /** ажилд орсон огноо */
  readonly hiredDate: string | null;
  /** аймгийн нэр */
  readonly provinceName: string | null;
  /** дүүргийн нэр */
  readonly districtName: string | null;
  /** дэд дүүргийн нэр */
  readonly subdistrictName: string | null;
  /** албан газарын нэр */
  readonly officeName: string | null;
  /** сүүлд өөрчлөгдсөн огноо */
  readonly lastModifiedDate: string | null;
  /** мэйл */
  readonly email: string | null;
  /** Аймаг/хот */
  readonly aimag: string | null;
  /** Баг/хороо */
  readonly bag: string | null;
  /** Бүртгүүлсэн дугаар */
  readonly mobile: string | null;
  /** Сум/дүүрэг */
  readonly soum: string | null;
  /** Хүсч буй цалингийн дээд хэмжээ */
  readonly salaryMax: number | null;
  /** Хүсч буй цалингийн доод хэмжээ */
  readonly salaryMin: number | null;
  /** Хөдөлмөрийн ур чадвар */
  readonly skill: string | null;
  /** Хүсч буй ажлын байр */
  readonly wantActivity: string | null;
  /** Хүсч буй ажлын байрны байршил */
  readonly wantAimag: string | null;
  /** Хүсч буй мэрэгэжил */
  readonly wantOccupation: string | null;
  /** Хүсч буй ажлын байрны байршил сум/хороо */
  readonly wantSoum: string | null;
  /** Хүсч буй ажлын байрны төрөл */
  readonly wantType: string | null;
}

const SCHEMA: Schema = {
  createdDate: "string",
  typeCode: "string",
  abroad: "bool",
  id: "int",
  educationLevelCode: "string",
  educationLevelName: "string",
  professionName: "string",
  abilityCode: "string",
  firstName: "string",
  birthDate: "string",
  seekerStatusCode: "string",
  seekerStatusName: "string",
  addresses: { list: { object: { provinceName: "string", districtName: "string", subdistrictName: "string", streetName: "string", apartment: "string", doorNumber: "string", latitude: "string", longitude: "string", description: "string" } } },
  desiredJobs: { list: { object: { locationTypeName: "string", jobTypeName: "string", workHourName: "string", occupationName: "string", salaryRangeName: "string", roleInfo: "string" } } },
  username: "string",
  statusCode: "string",
  statusName: "string",
  reasonName: "string",
  abilityName: "string",
  experienced: "bool",
  typeName: "string",
  regnum: "string",
  civilId: "string",
  surname: "string",
  lastName: "string",
  genderCode: "string",
  genderName: "string",
  purposeCode: "string",
  purposeName: "string",
  phone: "string",
  soughtDate: "string",
  hiredDate: "string",
  provinceName: "string",
  districtName: "string",
  subdistrictName: "string",
  officeName: "string",
  lastModifiedDate: "string",
  email: "string",
  aimag: "string",
  bag: "string",
  mobile: "string",
  soum: "string",
  salaryMax: "float",
  salaryMin: "float",
  skill: "string",
  wantActivity: "string",
  wantAimag: "string",
  wantOccupation: "string",
  wantSoum: "string",
  wantType: "string",
};

/**
 * WS100916_getCitizenLaborInfo: Хөдөлмөрийн зах зээллийн мэдээллийн системд бүртгэлтэй иргэний мэдээлэл
 *
 * Provider: Хөдөлмөр халамж, үйлчилгээний ерөнхий газар
 */
export async function getCitizenLaborInfo(transport: Transport, params: GetCitizenLaborInfoParams = {}, options: CallOptions = {}): Promise<XypResult<GetCitizenLaborInfoResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<GetCitizenLaborInfoResponse>("GetCitizenLaborInfoResponse", SCHEMA, data);
}
