// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.legalentity;

import io.github.baljinnyamday.xyp.Params;
import io.github.baljinnyamday.xyp.RequestParams;
import io.github.baljinnyamday.xyp.XypDate;

/**
 * The request of {@link LegalEntityClient#getCustomsOffnsInfo}, XYP operation {@code
 * WS100327_getCustomsOffnsInfo}.
 *
 * <p>Every field is optional: a field left {@code null} is not sent. Instances are immutable;
 * create one with {@link #builder()}.
 */
public final class GetCustomsOffnsInfoParams implements RequestParams {
  private final String regnum;
  private final XypDate startDate;
  private final XypDate endDate;

  private GetCustomsOffnsInfoParams(Builder builder) {
    this.regnum = builder.regnum;
    this.startDate = builder.startDate;
    this.endDate = builder.endDate;
  }

  /**
   * Returns a builder with every field unset.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Байгууллагын регистрийн дугаар.
   *
   * @return the value, or {@code null} when it is not set
   */
  public String regnum() {
    return regnum;
  }

  /**
   * Лавлагаанд хамаарах эхлэх огноо.
   *
   * @return the value, or {@code null} when it is not set
   */
  public XypDate startDate() {
    return startDate;
  }

  /**
   * Лавлагаанд хамаарах дуусах огноо.
   *
   * @return the value, or {@code null} when it is not set
   */
  public XypDate endDate() {
    return endDate;
  }

  @Override
  public Params toParams() {
    return Params.builder()
        .add("regnum", regnum)
        .add("startDate", startDate)
        .add("endDate", endDate)
        .build();
  }

  /**
   * Builds a {@link GetCustomsOffnsInfoParams}. Every setter accepts {@code null}, which leaves the
   * field out of the request. A builder is not thread-safe; it can be reused, and setting a field
   * again does not change the params it has already built.
   */
  public static final class Builder {
    private String regnum;
    private XypDate startDate;
    private XypDate endDate;

    private Builder() {}

    /**
     * Байгууллагын регистрийн дугаар.
     *
     * @param regnum the value, or {@code null}
     * @return this builder
     */
    public Builder regnum(String regnum) {
      this.regnum = regnum;
      return this;
    }

    /**
     * Лавлагаанд хамаарах эхлэх огноо.
     *
     * @param startDate the value, or {@code null}
     * @return this builder
     */
    public Builder startDate(XypDate startDate) {
      this.startDate = startDate;
      return this;
    }

    /**
     * Лавлагаанд хамаарах дуусах огноо.
     *
     * @param endDate the value, or {@code null}
     * @return this builder
     */
    public Builder endDate(XypDate endDate) {
      this.endDate = endDate;
      return this;
    }

    /**
     * Returns the params set so far.
     *
     * @return a new, immutable {@link GetCustomsOffnsInfoParams}
     */
    public GetCustomsOffnsInfoParams build() {
      return new GetCustomsOffnsInfoParams(this);
    }
  }
}
