// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.legalentity;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS100337_getEbalanceInfo}: Хуулийн этгээдийн мэдээлэл шалгах Ebalance.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param positionId positionId
 * @param createdUserName createdUserName
 * @param createdDate createdDate
 * @param companyRegnum companyRegnum
 * @param rowStatusName rowStatusName
 * @param lastName lastName
 * @param firstName firstName
 * @param countryName countryName
 * @param regnum regnum
 * @param positionName positionName
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record GetEbalanceInfoResponse(
    String positionId,
    String createdUserName,
    String createdDate,
    String companyRegnum,
    String rowStatusName,
    String lastName,
    String firstName,
    String countryName,
    String regnum,
    String positionName,
    Extras extras) {

  static GetEbalanceInfoResponse decode(ResponseReader reader) {
    return new GetEbalanceInfoResponse(
        reader.get("positionId", Decoders.STRING),
        reader.get("createdUserName", Decoders.STRING),
        reader.get("createdDate", Decoders.STRING),
        reader.get("companyRegnum", Decoders.STRING),
        reader.get("rowStatusName", Decoders.STRING),
        reader.get("lastName", Decoders.STRING),
        reader.get("firstName", Decoders.STRING),
        reader.get("countryName", Decoders.STRING),
        reader.get("regnum", Decoders.STRING),
        reader.get("positionName", Decoders.STRING),
        reader.extras());
  }
}
