// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.legalentity;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;

/**
 * The response of {@code WS100324_legalEntityGeneralInfo}: Хуулийн этгээдийн үндсэн мэдээлэл.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param companyRegnum Хуулийн этгээдийн регистрийн дугаар
 * @param companyName Оноосон нэр
 * @param departmentName Улсын бүртгэлд бүртгэсэн байгууллагын нэр
 * @param decisionNumber Улсын бүртгэлд бүртгэсэн шийдвэрийн дугаар
 * @param decisionDate Улсын бүртгэлд бүртгэсэн шийдвэрийн огноо
 * @param createdDate Улсын бүртгэлд бүртгэсэн бүртгэсэн огноо
 * @param createdUserName Улсын бүртгэлд бүртгэсэн бүртгэсэн ажилтан
 * @param stateRegnum Хувийн хэргийн дугаар
 * @param profitTypeName Хуулийн этгээдийн төрөл
 * @param description Хуулийн этгээдийн хэлбэр
 * @param descriptionCode Хуулийн этгээдийн код
 * @param ownershipTypeName Өмчийн хэлбэр
 * @param ownershipTypeCode Өмчийн хэлбэр
 * @param companyFounderCount Хувьцаа эзсмшигч, гишүүний тоо
 * @param founderDocumentName Үүсгэн байгуулах баримт бичгийн нэр
 * @param founderDecisionName Үүсгэн байгуулах шийдвэрийн нэр
 * @param founderDecisionNumber Үүсгэн байгуулах шийдвэрийн дугаар
 * @param regulationDate Үүсгэн байгуулах дурмийн огноо
 * @param contractDate Үүсгэн байгуулах гэрээний огноо
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record LegalEntityGeneralInfoResponse(
    String companyRegnum,
    String companyName,
    String departmentName,
    String decisionNumber,
    String decisionDate,
    String createdDate,
    String createdUserName,
    String stateRegnum,
    String profitTypeName,
    String description,
    String descriptionCode,
    String ownershipTypeName,
    String ownershipTypeCode,
    Long companyFounderCount,
    String founderDocumentName,
    String founderDecisionName,
    String founderDecisionNumber,
    String regulationDate,
    String contractDate,
    Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static LegalEntityGeneralInfoResponse decode(ResponseReader reader) {
    return new LegalEntityGeneralInfoResponse(
        reader.get("companyRegnum", Decoders.STRING),
        reader.get("companyName", Decoders.STRING),
        reader.get("departmentName", Decoders.STRING),
        reader.get("decisionNumber", Decoders.STRING),
        reader.get("decisionDate", Decoders.STRING),
        reader.get("createdDate", Decoders.STRING),
        reader.get("createdUserName", Decoders.STRING),
        reader.get("stateRegnum", Decoders.STRING),
        reader.get("profitTypeName", Decoders.STRING),
        reader.get("description", Decoders.STRING),
        reader.get("descriptionCode", Decoders.STRING),
        reader.get("ownershipTypeName", Decoders.STRING),
        reader.get("ownershipTypeCode", Decoders.STRING),
        reader.get("companyFounderCount", Decoders.INT),
        reader.get("founderDocumentName", Decoders.STRING),
        reader.get("founderDecisionName", Decoders.STRING),
        reader.get("founderDecisionNumber", Decoders.STRING),
        reader.get("regulationDate", Decoders.STRING),
        reader.get("contractDate", Decoders.STRING),
        reader.extras());
  }
}
