// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

/**
 * The 19 XYP services of the {@code legal_entity} group, served from {@code legal-entity-1.5.0}.
 *
 * <p>Call them through {@link io.github.baljinnyamday.xyp.legalentity.LegalEntityClient}, which
 * {@code XypClient.legalEntity()} returns.
 */
package io.github.baljinnyamday.xyp.legalentity;
