// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package citizen

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// CitizenGraduateSchoolListParams is the input of WS100155_citizenGraduateSchoolList. Every field is
// optional; a zero value is left out of the request.
type CitizenGraduateSchoolListParams struct {
	// Регистрийн дугаар
	Regnum string `xyp:"regnum"`
}

// CitizenGraduateSchoolListListData: Мэдээллийн жагсаалт
type CitizenGraduateSchoolListListData struct {
	// Боловсролын дугаар
	EducationId string `xyp:"educationId"`
	// Сургуулийн нэр
	InstitutionName string `xyp:"institutionName"`
	// Боловсролын зэрэг
	DergeeName string `xyp:"dergeeName"`
	// Төгссөн жил
	ConferYear string `xyp:"conferYear"`
	// Мэргэжил/Хөтөлбөр
	ProgramName string `xyp:"programName"`
	// Мэргэжлийн индекс
	EducationCode string `xyp:"educationCode"`
}

// CitizenGraduateSchoolListResponse is the response of WS100155_citizenGraduateSchoolList: Иргэний дүүргэсэн дээд сургуулиудын жагсаалт.
type CitizenGraduateSchoolListResponse struct {
	// Мэдээллийн жагсаалт
	ListData []CitizenGraduateSchoolListListData `xyp:"listData"`
	Result   string                              `xyp:"result"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// CitizenGraduateSchoolList calls WS100155_citizenGraduateSchoolList: Иргэний дүүргэсэн дээд сургуулиудын жагсаалт
//
// Provider: Боловсрол шинжлэх ухааны яам
func (s *Service) CitizenGraduateSchoolList(ctx context.Context, params CitizenGraduateSchoolListParams, opts ...xyp.CallOption) (*CitizenGraduateSchoolListResponse, error) {
	var out CitizenGraduateSchoolListResponse
	extras, err := s.client.Invoke(ctx, "WS100155_citizenGraduateSchoolList", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
