// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package citizen

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// GetDissolvedLegalEntityInfoParams is the input of WS101159_GetDissolvedLegalEntityInfo. Every field is
// optional; a zero value is left out of the request.
type GetDissolvedLegalEntityInfoParams struct {
	// Хуулийн этгээдийн Регситрийн дугаар
	OrgRegnum string `xyp:"orgRegnum"`
	// Гүйцэтгэх удирадлагын регистрийн дугаар
	Regnum string `xyp:"regnum"`
}

// GetDissolvedLegalEntityInfoResponse is the response of WS101159_GetDissolvedLegalEntityInfo: Татан буугдсан хуулийн этгээдийн лавлагааны сервис.
type GetDissolvedLegalEntityInfoResponse struct {
	// Оноосон нэр
	CompanyName string `xyp:"companyName"`
	// Хуулийн этгээдийн регистрийн дугаар
	OrgRegnum string `xyp:"orgRegnum"`
	// Бүртгэсэн огноо
	CreatedDate     string `xyp:"createdDate"`
	CompanyTypeName string `xyp:"companyTypeName"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// GetDissolvedLegalEntityInfo calls WS101159_GetDissolvedLegalEntityInfo: Татан буугдсан хуулийн этгээдийн лавлагааны сервис
//
// Provider: Улсын бүртгэлийн ерөнхий газар
func (s *Service) GetDissolvedLegalEntityInfo(ctx context.Context, params GetDissolvedLegalEntityInfoParams, opts ...xyp.CallOption) (*GetDissolvedLegalEntityInfoResponse, error) {
	var out GetDissolvedLegalEntityInfoResponse
	extras, err := s.client.Invoke(ctx, "WS101159_GetDissolvedLegalEntityInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
