// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package citizen

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// PassportInfoSecondTimeParams is the input of WS100141_passportInfoSecondTime. Every field is
// optional; a zero value is left out of the request.
type PassportInfoSecondTimeParams struct {
	// Иргэний хувийн дугаар
	CivilId string `xyp:"civilId"`
	// регистрийн дугаар
	Regnum string `xyp:"regnum"`
}

// PassportInfoSecondTimeResponse is the response of WS100141_passportInfoSecondTime: Үндэсний энгийн гадаад паспорт дахин авсан тухай лавлагаа.
type PassportInfoSecondTimeResponse struct {
	// Иргэний регистрийн дугаар
	Regnum any `xyp:"regnum"`
	// Ургийн овог
	Forename string `xyp:"forename"`
	// Эцэг/эхийн нэр
	Surname string `xyp:"surname"`
	// Нэр
	Givenname string `xyp:"givenname"`
	// Олгосон огноо
	IssuedDate xyp.Date `xyp:"issuedDate"`
	// Гадаад паспортын E дугаар
	PassportNum string `xyp:"passportNum"`
	// Өмнөх паспортын олгосон огноо
	InvIssuedDate xyp.Date `xyp:"invIssuedDate"`
	// Өмнөх паспортын E дугаар
	InvPassportNum string `xyp:"invPassportNum"`
	// Шалтгаан
	InvCauseName string `xyp:"invCauseName"`
	// Бүртгэлийн дугаар
	RegisteredNum string `xyp:"registeredNum"`
	// Иргэншил
	Citizenship string `xyp:"citizenship"`
	// Хүйс
	Sex string `xyp:"sex"`
	// Төрсөн огноо
	BirthDate string `xyp:"birthDate"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// PassportInfoSecondTime calls WS100141_passportInfoSecondTime: Үндэсний энгийн гадаад паспорт дахин авсан тухай лавлагаа
//
// Provider: Улсын бүртгэлийн ерөнхий газар
func (s *Service) PassportInfoSecondTime(ctx context.Context, params PassportInfoSecondTimeParams, opts ...xyp.CallOption) (*PassportInfoSecondTimeResponse, error) {
	var out PassportInfoSecondTimeResponse
	extras, err := s.client.Invoke(ctx, "WS100141_passportInfoSecondTime", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
