"""GENERATED by xyp-generator from spec/services.json. Do not edit.

GS10089_EnergyQualificationCertificateService (government_service, Эрчим хүчний яам)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "GS10089_EnergyQualificationCertificateService"


class EnergyQualificationCertificateServiceResponse(XypModel):
    """GS10089_EnergyQualificationCertificateService: Эрчим хүчний салбарын мэргэшлийн зэрэг эзэмшигчийн сертификатын мэдээлэл id-аар лавлах"""

    last_name: str | None = Field(default=None, alias="lastName", description="Овог")
    first_name: str | None = Field(default=None, alias="firstName", description="Нэр")
    id: str | None = Field(default=None, alias="id", description="Сертификатын id")
    decision_num: str | None = Field(
        default=None, alias="decisionNum", description="Тушаалын дугаар"
    )
    decision_date: str | None = Field(
        default=None, alias="decisionDate", description="Тушаалын огноо"
    )
    certificate_num: str | None = Field(
        default=None, alias="certificateNum", description="Гэрчилгээний дугаар"
    )
    profession_code: str | None = Field(
        default=None, alias="professionCode", description="Мэргэжлийн код"
    )
    certificate_name: str | None = Field(
        default=None, alias="certificateName", description="Мэргэшлийн зэргийн нэр"
    )
    valid_year: str | None = Field(
        default=None,
        alias="validYear",
        description="Тушаалын огнооноос хүчинтэй байх жил (0 бол хугацаагүй сунгасан)",
    )
    profession_desc: str | None = Field(
        default=None, alias="professionDesc", description="Мэргэжлийн нэр"
    )
    expire_date: str | None = Field(
        default=None,
        alias="expireDate",
        description="Сертификатын дуусах огноо (Хоосон бол хугацаагүй сунгасан буюу үргэлж хүчинтэй байна)",
    )
    certificate_status: str | None = Field(
        default=None, alias="certificateStatus", description='Төлөв: "Хүчинтэй" / "Хүчингүй"'
    )


def energy_qualification_certificate_service(
    self: SyncService,
    *,
    id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EnergyQualificationCertificateServiceResponse:
    """GS10089_EnergyQualificationCertificateService: Эрчим хүчний салбарын мэргэшлийн зэрэг эзэмшигчийн сертификатын мэдээлэл id-аар лавлах

    Provider: Эрчим хүчний яам

    Args:
        id: Сертификатын id (GS10088_EnergyQualificationService сервисийн listData-аас авна)
    """
    data = self._transport.call(
        _OPERATION,
        {
            "id": id,
        },
        auth,
        operator,
    )
    return parse_model(EnergyQualificationCertificateServiceResponse, data)


async def energy_qualification_certificate_service_async(
    self: AsyncService,
    *,
    id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> EnergyQualificationCertificateServiceResponse:
    """GS10089_EnergyQualificationCertificateService: Эрчим хүчний салбарын мэргэшлийн зэрэг эзэмшигчийн сертификатын мэдээлэл id-аар лавлах

    Provider: Эрчим хүчний яам

    Args:
        id: Сертификатын id (GS10088_EnergyQualificationService сервисийн listData-аас авна)
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "id": id,
        },
        auth,
        operator,
    )
    return parse_model(EnergyQualificationCertificateServiceResponse, data)
