"""GENERATED by xyp-generator from spec/services.json. Do not edit.

GS10050_GetSoumDistrictListByZipcode (government_service, Цагдаагийн ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "GS10050_GetSoumDistrictListByZipcode"


class GetSoumDistrictListByZipcodeList(XypModel):
    """жагсаалт"""

    zip_code: int | None = Field(default=None, alias="zipCode", description="Аймгийн зипкод")
    name: str | None = Field(default=None, alias="name", description="Аймгийн нэр")


class GetSoumDistrictListByZipcodeResponse(XypModel):
    """GS10050_GetSoumDistrictListByZipcode: Сум/дүүргийн жагсаалт"""

    list_: list[GetSoumDistrictListByZipcodeList] | None = Field(
        default=None, alias="list", description="жагсаалт"
    )


def get_soum_district_list_by_zipcode(
    self: SyncService,
    *,
    zip_code: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetSoumDistrictListByZipcodeResponse:
    """GS10050_GetSoumDistrictListByZipcode: Сум/дүүргийн жагсаалт

    Provider: Цагдаагийн ерөнхий газар

    Args:
        zip_code: Аймгийн зипкод
    """
    data = self._transport.call(
        _OPERATION,
        {
            "zipCode": zip_code,
        },
        auth,
        operator,
    )
    return parse_model(GetSoumDistrictListByZipcodeResponse, data)


async def get_soum_district_list_by_zipcode_async(
    self: AsyncService,
    *,
    zip_code: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetSoumDistrictListByZipcodeResponse:
    """GS10050_GetSoumDistrictListByZipcode: Сум/дүүргийн жагсаалт

    Provider: Цагдаагийн ерөнхий газар

    Args:
        zip_code: Аймгийн зипкод
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "zipCode": zip_code,
        },
        auth,
        operator,
    )
    return parse_model(GetSoumDistrictListByZipcodeResponse, data)
