"""GENERATED by xyp-generator from spec/services.json. Do not edit.

GS10024_notaryVehicleInfo (government_service, Монголын Нотариатчдын Танхим)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "GS10024_notaryVehicleInfo"


class NotaryVehicleInfoListData(XypModel):
    bookid: str | None = Field(
        default=None, alias="bookid", description="Итгэмжлэлийн давтагдашгүй дугаар"
    )
    employeename: str | None = Field(
        default=None, alias="employeename", description="Нотариатчийн нэр"
    )
    stateregnumber: str | None = Field(default=None, alias="stateregnumber")
    booknumber: str | None = Field(
        default=None, alias="booknumber", description="Итгэмжлэлийн тухайн жил дэх дугаар"
    )
    bookyear: str | None = Field(default=None, alias="bookyear", description="Итгэмжлэл хийсэн он")
    bookdate: str | None = Field(
        default=None, alias="bookdate", description="Итгэмжлэл хийсэн огноо цаг"
    )
    itemname: str | None = Field(default=None, alias="itemname", description="Итгэмжлэлийн нэр")
    wfmstatusname: str | None = Field(
        default=None, alias="wfmstatusname", description="Итгэмжлэлийн төлөв"
    )
    physicalpath: str | None = Field(default=None, alias="physicalpath", description="файлын зам")
    stateserialnumber: str | None = Field(
        default=None, alias="stateserialnumber", description="улсын дугаар"
    )
    vehiclename: str | None = Field(
        default=None, alias="vehiclename", description="тээврийн хэрэгсэлийн нэр"
    )
    manufacturedyear: str | None = Field(
        default=None, alias="manufacturedyear", description="лдвэрлэсэн он"
    )
    certificatedate: str | None = Field(
        default=None, alias="certificatedate", description="гэрчилгээний огноо"
    )
    certificatenumber: str | None = Field(
        default=None, alias="certificatenumber", description="гэрчилгээний дугаар"
    )
    modelnumber: str | None = Field(
        default=None, alias="modelnumber", description="марк, үйлдвэрлэгч"
    )
    color: str | None = Field(default=None, alias="color", description="өнгө")
    customnumber: str | None = Field(
        default=None, alias="customnumber", description="гаалын дугаар"
    )
    vincode: str | None = Field(default=None, alias="vincode", description="арлын дугаар")
    semantictypename: str | None = Field(default=None, alias="semantictypename")
    semantic_id: str | None = Field(default=None, alias="semanticId")
    item_category_id: str | None = Field(default=None, alias="itemCategoryId")


class NotaryVehicleInfoResponse(XypModel):
    """GS10024_notaryVehicleInfo: үйлдэл болон тээврийн хэрэгслийн мэдээллийг дуудах вебсервис"""

    list_data: list[NotaryVehicleInfoListData] | None = Field(default=None, alias="listData")


def notary_vehicle_info(
    self: SyncService,
    *,
    regnum: str | None = None,
    category_id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> NotaryVehicleInfoResponse:
    """GS10024_notaryVehicleInfo: үйлдэл болон тээврийн хэрэгслийн мэдээллийг дуудах вебсервис

    Provider: Монголын Нотариатчдын Танхим

    Args:
        regnum: рд
        category_id: categoryId
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "categoryId": category_id,
        },
        auth,
        operator,
    )
    return parse_model(NotaryVehicleInfoResponse, data)


async def notary_vehicle_info_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    category_id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> NotaryVehicleInfoResponse:
    """GS10024_notaryVehicleInfo: үйлдэл болон тээврийн хэрэгслийн мэдээллийг дуудах вебсервис

    Provider: Монголын Нотариатчдын Танхим

    Args:
        regnum: рд
        category_id: categoryId
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
            "categoryId": category_id,
        },
        auth,
        operator,
    )
    return parse_model(NotaryVehicleInfoResponse, data)
