"""GENERATED by xyp-generator from spec/services.json. Do not edit.

GS10081_PaymentInfoService (government_service, Шүүхийн Шинжилгээний Ерөнхий Газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "GS10081_PaymentInfoService"


class PaymentInfoServiceResponse(XypModel):
    """GS10081_PaymentInfoService: Төлбөр төлөх мэдээлэл дуудах сервис"""

    deceased_info_id: str | None = Field(
        default=None, alias="deceasedInfoId", description="нас барсан хүний мэдээллийн ID"
    )
    surname: str | None = Field(default=None, alias="surname", description="овог")
    given_name: str | None = Field(default=None, alias="givenName", description="нэр")
    age: int | None = Field(default=None, alias="age", description="нас")
    is_foreigner: bool | None = Field(default=None, alias="isForeigner", description="гадаад эсэх")
    coffin_length: str | None = Field(default=None, alias="coffinLength", description="авсны урт")
    coffin_width: str | None = Field(default=None, alias="coffinWidth", description="авсны өргөн")
    is_payment_exempt: bool | None = Field(
        default=None, alias="isPaymentExempt", description="төлбөрөөс чөлөөлөгдсөн эсэх"
    )
    payment_autopsied: int | None = Field(
        default=None, alias="paymentAutopsied", description="задлангийн төлбөр"
    )
    storage_days: int | None = Field(
        default=None, alias="storageDays", description="хадгалсан хоног"
    )
    payment_storage: int | None = Field(
        default=None, alias="paymentStorage", description="хадгалалтын төлбөр"
    )
    payment_total: int | None = Field(default=None, alias="paymentTotal", description="нийт төлбөр")


def payment_info_service(
    self: SyncService,
    *,
    hall_id: str | None = None,
    hall_date: str | None = None,
    deceased_info_id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> PaymentInfoServiceResponse:
    """GS10081_PaymentInfoService: Төлбөр төлөх мэдээлэл дуудах сервис

    Provider: Шүүхийн Шинжилгээний Ерөнхий Газар

    Args:
        hall_id: hallId
        hall_date: hallDate
        deceased_info_id: deceasedInfoId
    """
    data = self._transport.call(
        _OPERATION,
        {
            "hallId": hall_id,
            "hallDate": hall_date,
            "deceasedInfoId": deceased_info_id,
        },
        auth,
        operator,
    )
    return parse_model(PaymentInfoServiceResponse, data)


async def payment_info_service_async(
    self: AsyncService,
    *,
    hall_id: str | None = None,
    hall_date: str | None = None,
    deceased_info_id: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> PaymentInfoServiceResponse:
    """GS10081_PaymentInfoService: Төлбөр төлөх мэдээлэл дуудах сервис

    Provider: Шүүхийн Шинжилгээний Ерөнхий Газар

    Args:
        hall_id: hallId
        hall_date: hallDate
        deceased_info_id: deceasedInfoId
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "hallId": hall_id,
            "hallDate": hall_date,
            "deceasedInfoId": deceased_info_id,
        },
        auth,
        operator,
    )
    return parse_model(PaymentInfoServiceResponse, data)
