"""GENERATED by xyp-generator from spec/services.json. Do not edit.

GS10022_studentSoldierInfo (government_service, Боловсрол шинжлэх ухааны яам)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypDate, XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "GS10022_studentSoldierInfo"


class StudentSoldierInfoResponse(XypModel):
    """GS10022_studentSoldierInfo: оюутан цэргийн мэдээлэл дуудах"""

    enterprise_id: int | None = Field(
        default=None, alias="enterpriseId", description="Интерпрайзын дугаар"
    )
    institution_id: int | None = Field(
        default=None, alias="institutionId", description="Сургалтын байгууллагын дугаар"
    )
    institution_name: str | None = Field(
        default=None, alias="institutionName", description="Сургалтын байгууллагын нэр"
    )
    city_code: str | None = Field(default=None, alias="cityCode", description="Аймаг, хотын код")
    city_name: str | None = Field(default=None, alias="cityName", description="Аймаг, хотын нэр")
    district_code: str | None = Field(
        default=None, alias="districtCode", description="Сум, дүүргийн код"
    )
    district_name: str | None = Field(
        default=None, alias="districtName", description="Сум, дүүргийн нэр"
    )
    bag_code: str | None = Field(default=None, alias="bagCode", description="Баг, хорооны код")
    bag_name: str | None = Field(default=None, alias="bagName", description="Баг, хорооны нэр")
    school_id: int | None = Field(
        default=None, alias="schoolId", description="Салбар сургуулийн дугаар"
    )
    school_name: str | None = Field(
        default=None, alias="schoolName", description="Салбар сургуулийн нэр"
    )
    school_city_code: str | None = Field(
        default=None, alias="schoolCityCode", description="Салбар сургуулийн Аймаг, хотын код"
    )
    school_city_name: str | None = Field(
        default=None, alias="schoolCityName", description="Салбар сургуулийн Аймаг, хотын нэр"
    )
    school_district_code: str | None = Field(
        default=None, alias="schoolDistrictCode", description="Салбар сургуулийн Сум, дүүргийн код"
    )
    school_district_name: str | None = Field(
        default=None, alias="schoolDistrictName", description="Салбар сургуулийн Сум, дүүргийн нэр"
    )
    regnum: str | None = Field(default=None, alias="regnum", description="Регистр")
    last_name: str | None = Field(default=None, alias="lastName", description="Овог")
    first_name: str | None = Field(default=None, alias="firstName", description="Нэр")
    education_field_code: str | None = Field(
        default=None, alias="educationFieldCode", description="Мэргэжлийн чиглэлийн индекс"
    )
    education_field_name: str | None = Field(
        default=None, alias="educationFieldName", description="Мэргэжлийн чиглэлийн нэр"
    )
    program_name: str | None = Field(
        default=None, alias="programName", description="Хөтөлбөрийн нэр"
    )
    academic_level: str | None = Field(
        default=None, alias="academicLevel", description="түвшин, дамжаа"
    )
    effective_start_date: XypDate | None = Field(
        default=None, alias="effectiveStartDate", description="Идэвхитэй болсон огноо"
    )
    total_gpa: float | None = Field(default=None, alias="totalGpa", description="Голч")


def student_soldier_info(
    self: SyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> StudentSoldierInfoResponse:
    """GS10022_studentSoldierInfo: оюутан цэргийн мэдээлэл дуудах

    Provider: Боловсрол шинжлэх ухааны яам

    Args:
        regnum: регистрийн дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(StudentSoldierInfoResponse, data)


async def student_soldier_info_async(
    self: AsyncService,
    *,
    regnum: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> StudentSoldierInfoResponse:
    """GS10022_studentSoldierInfo: оюутан цэргийн мэдээлэл дуудах

    Provider: Боловсрол шинжлэх ухааны яам

    Args:
        regnum: регистрийн дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "regnum": regnum,
        },
        auth,
        operator,
    )
    return parse_model(StudentSoldierInfoResponse, data)
