"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100432_getVehicleInspectionDataByPlateNo (transport, Авто тээврийн үндэсний төв)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100432_getVehicleInspectionDataByPlateNo"


class GetVehicleInspectionDataByPlateNoListData(XypModel):
    """мэдээлийн жагсаалт"""

    plate_no: str | None = Field(
        default=None, alias="plateNo", description="тээврийн хэрэгслийн улсын дугаар"
    )
    inspection_date: str | None = Field(
        default=None, alias="inspectionDate", description="шалгалтын огноо"
    )
    expire_date: str | None = Field(default=None, alias="expireDate", description="дуусах огноо")
    report_url: str | None = Field(
        default=None, alias="reportUrl", description="хяналтын үзлэгийн дүгнэлтийн хуудас"
    )


class GetVehicleInspectionDataByPlateNoResponse(XypModel):
    """WS100432_getVehicleInspectionDataByPlateNo: Техникийн хяналтын мэдээллийг тээврийн хэрэгслийн улсын дугаараар шалгах"""

    list_data: list[GetVehicleInspectionDataByPlateNoListData] | None = Field(
        default=None, alias="listData", description="мэдээлийн жагсаалт"
    )


def get_vehicle_inspection_data_by_plate_no(
    self: SyncService,
    *,
    plate_no: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetVehicleInspectionDataByPlateNoResponse:
    """WS100432_getVehicleInspectionDataByPlateNo: Техникийн хяналтын мэдээллийг тээврийн хэрэгслийн улсын дугаараар шалгах

    Provider: Авто тээврийн үндэсний төв

    Args:
        plate_no: тээврийн хэрэгслийн улсын дугаар
    """
    data = self._transport.call(
        _OPERATION,
        {
            "plateNo": plate_no,
        },
        auth,
        operator,
    )
    return parse_model(GetVehicleInspectionDataByPlateNoResponse, data)


async def get_vehicle_inspection_data_by_plate_no_async(
    self: AsyncService,
    *,
    plate_no: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> GetVehicleInspectionDataByPlateNoResponse:
    """WS100432_getVehicleInspectionDataByPlateNo: Техникийн хяналтын мэдээллийг тээврийн хэрэгслийн улсын дугаараар шалгах

    Provider: Авто тээврийн үндэсний төв

    Args:
        plate_no: тээврийн хэрэгслийн улсын дугаар
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "plateNo": plate_no,
        },
        auth,
        operator,
    )
    return parse_model(GetVehicleInspectionDataByPlateNoResponse, data)
