<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

/**
 * Input of WS100246_electricRequirementRequestList: Цахилгааны техникийн нөхцөлийн хүсэлтийн жагсаалт авах.
 *
 * Provider: Эрчим хүчний яам
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class ElectricRequirementRequestListParams
{
    /**
     * @param string|null $regnum регистрийн дугаар
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
