<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

use Xyp\Extras;

/**
 * Response of WS100243_electricRequirementRequest: Цахилгааны техникийн нөхцөлийн хүсэлт илгээх.
 *
 * Provider: Эрчим хүчний яам
 */
final readonly class ElectricRequirementRequestResponse
{
    /**
     * @param int|null $requestId
     * @param string|null $status Хүсэлтийн шийдвэрлэлт ямар түвшинд байгааг харуулна
     * @param string|null $finishedProcess Хүсэлтийн шийдвэрлэлт хэдэн хувийн гүйцэтгэлтэй байгааг харуулна
     * @param string|null $companyInCharge Уг хүсэлтийг шийдвэрлэхээр хувиарлагдсан байгууллагын нэр
     * @param string|null $createdDate Уг хүсэлтийг үүсгэсэн огноо
     * @param string|null $lastUpdatedDate Хүсэлт гаргагч уг хүсэлтийг өөрчилсөн сүүлийн огноо
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        public ?int $requestId = null,
        public ?string $status = null,
        public ?string $finishedProcess = null,
        public ?string $companyInCharge = null,
        public ?string $createdDate = null,
        public ?string $lastUpdatedDate = null,
        public Extras $xyp = new Extras(),
    ) {}
}
