<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

use Xyp\Attribute\ListOf;
use Xyp\Extras;

/**
 * Response of WS100252_getPropertyInfoByNationalPropertyNumberEng: Иргэний эд хөрөнгийн англи лавлагааг эд хөрөнгийн дугаараар дуудах сервис.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
final readonly class GetPropertyInfoByNationalPropertyNumberEngResponse
{
    /**
     * @param list<GetPropertyInfoByNationalPropertyNumberEngData> $data жагсаалт
     * @param Extras $xyp What this class could not hold: ->mismatches lists the response fields that did not fit (they kept their default), ->raw is the whole response tree.
     */
    public function __construct(
        #[ListOf(GetPropertyInfoByNationalPropertyNumberEngData::class)]
        public array $data = [],
        public Extras $xyp = new Extras(),
    ) {}
}
