<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

/**
 * Input of WS100235_landCadastreApplicantInfo: Газрын кадастрын нэгж талбарын өргөдөл гаргагчын мэдээлэл.
 *
 * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class LandCadastreApplicantInfoParams
{
    /**
     * @param string|null $id Нэгж талбарын дугаар
     */
    public function __construct(
        public ?string $id = null,
    ) {}
}
