<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

/**
 * мэдээллийн жагсаалт
 *
 * `listData` in the response of WS100238_landCadastreVicinityInfo.
 */
final readonly class LandCadastreVicinityInfoListData
{
    /**
     * @param string|null $oldParcelId Хуучин нэгж талбарын дугаар
     * @param string|null $addressKhashaa Хашааны дугаар
     * @param string|null $addressStreetname Гудамжны нэр
     * @param string|null $validFrom Үнэлгээний бүсийн код
     * @param string|null $validTill Үнэлгээний бүсийн нэр
     * @param string|null $description Газар ашиглалтын төрөл
     * @param int|null $landuse Газар ашиглалтын төрлийн код
     * @param string|null $areaM2 Тайлбайн мэдээлэ
     * @param string|null $fillColor
     * @param string|null $boundaryColor
     * @param string|null $boundaryWidth
     * @param string|null $geom
     * @param string|null $utmGeom
     * @param string|null $blockNo
     * @param string|null $textGeometry
     * @param string|null $parcelId Нэгж талбарын дугаар
     */
    public function __construct(
        public ?string $oldParcelId = null,
        public ?string $addressKhashaa = null,
        public ?string $addressStreetname = null,
        public ?string $validFrom = null,
        public ?string $validTill = null,
        public ?string $description = null,
        public ?int $landuse = null,
        public ?string $areaM2 = null,
        public ?string $fillColor = null,
        public ?string $boundaryColor = null,
        public ?string $boundaryWidth = null,
        public ?string $geom = null,
        public ?string $utmGeom = null,
        public ?string $blockNo = null,
        public ?string $textGeometry = null,
        public ?string $parcelId = null,
    ) {}
}
