<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

use Xyp\Auth;
use Xyp\XypClient;

/**
 * The 30 XYP services of the `property` group, served from property-1.5.0.
 *
 * Reached through `$xyp->property`; every method sends one request through that XypClient.
 */
final class PropertyService
{
    public function __construct(private readonly XypClient $client) {}

    /**
     * Calls WS100201_getPropertyInfo: Үл хөдлөх хөрөнгийн мэдээлэл дамжуулах сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getPropertyInfo(
        GetPropertyInfoParams $params = new GetPropertyInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetPropertyInfoResponse {
        return $this->client->invoke(
            'WS100201_getPropertyInfo',
            $params,
            GetPropertyInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100202_getPropertyList: Үл хөдлөх хөрөнгийн жагсаалт авах сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getPropertyList(
        GetPropertyListParams $params = new GetPropertyListParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetPropertyListResponse {
        return $this->client->invoke(
            'WS100202_getPropertyList',
            $params,
            GetPropertyListResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100203_isPropertyCheck: Эд хөрөнгөтэй эсэх сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function isPropertyCheck(
        IsPropertyCheckParams $params = new IsPropertyCheckParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): IsPropertyCheckResponse {
        return $this->client->invoke(
            'WS100203_isPropertyCheck',
            $params,
            IsPropertyCheckResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100218_landOwningCertificateInfo: Газар эзэмших, ашиглах, эрхийн гэрчилгээний мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landOwningCertificateInfo(
        LandOwningCertificateInfoParams $params = new LandOwningCertificateInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandOwningCertificateInfoResponse {
        return $this->client->invoke(
            'WS100218_landOwningCertificateInfo',
            $params,
            LandOwningCertificateInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100219_landOwningContractInfo: Газар эзэмших, ашиглах, эрхийн гэрээ мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landOwningContractInfo(
        LandOwningContractInfoParams $params = new LandOwningContractInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandOwningContractInfoResponse {
        return $this->client->invoke(
            'WS100219_landOwningContractInfo',
            $params,
            LandOwningContractInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100220_landCadastralMapInfo: Газрын кадастрын зурагийн мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landCadastralMapInfo(
        LandCadastralMapInfoParams $params = new LandCadastralMapInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandCadastralMapInfoResponse {
        return $this->client->invoke(
            'WS100220_landCadastralMapInfo',
            $params,
            LandCadastralMapInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100221_landOwningDecisionInfo: Захирамжын мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landOwningDecisionInfo(
        LandOwningDecisionInfoParams $params = new LandOwningDecisionInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandOwningDecisionInfoResponse {
        return $this->client->invoke(
            'WS100221_landOwningDecisionInfo',
            $params,
            LandOwningDecisionInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100222_getCadastralMap: Кадастрын зураг авах.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getCadastralMap(
        GetCadastralMapParams $params = new GetCadastralMapParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetCadastralMapResponse {
        return $this->client->invoke(
            'WS100222_getCadastralMap',
            $params,
            GetCadastralMapResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100225_propertyValueInfo: Үл хөдлөхийн үнэлгээний мэдээлэл.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function propertyValueInfo(
        PropertyValueInfoParams $params = new PropertyValueInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): PropertyValueInfoResponse {
        return $this->client->invoke(
            'WS100225_propertyValueInfo',
            $params,
            PropertyValueInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100234_landCadastreAgreementInfo: Газрын кадастрын нэгж талбарын гэрээний мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landCadastreAgreementInfo(
        LandCadastreAgreementInfoParams $params = new LandCadastreAgreementInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandCadastreAgreementInfoResponse {
        return $this->client->invoke(
            'WS100234_landCadastreAgreementInfo',
            $params,
            LandCadastreAgreementInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100235_landCadastreApplicantInfo: Газрын кадастрын нэгж талбарын өргөдөл гаргагчын мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landCadastreApplicantInfo(
        LandCadastreApplicantInfoParams $params = new LandCadastreApplicantInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandCadastreApplicantInfoResponse {
        return $this->client->invoke(
            'WS100235_landCadastreApplicantInfo',
            $params,
            LandCadastreApplicantInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100236_landCadastreQR: Газрын кадастрын нэгж талбарын QR код.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landCadastreQR(
        LandCadastreQRParams $params = new LandCadastreQRParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandCadastreQRResponse {
        return $this->client->invoke(
            'WS100236_landCadastreQR',
            $params,
            LandCadastreQRResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100237_cadastreApplicantStatusInfo: Газрын кадастрын нэгж талбарын өргөдлийн явцын мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function cadastreApplicantStatusInfo(
        CadastreApplicantStatusInfoParams $params = new CadastreApplicantStatusInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): CadastreApplicantStatusInfoResponse {
        return $this->client->invoke(
            'WS100237_cadastreApplicantStatusInfo',
            $params,
            CadastreApplicantStatusInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100238_landCadastreVicinityInfo: Газрын кадастрын нэгж талбарын ойр орчмын байршлын мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landCadastreVicinityInfo(
        LandCadastreVicinityInfoParams $params = new LandCadastreVicinityInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandCadastreVicinityInfoResponse {
        return $this->client->invoke(
            'WS100238_landCadastreVicinityInfo',
            $params,
            LandCadastreVicinityInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100239_propertyDetailsBetweenDate: Үл хөдлөхийн бүртгэлд орсон мэдээлэл хугацааны хооронд.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function propertyDetailsBetweenDate(
        PropertyDetailsBetweenDateParams $params = new PropertyDetailsBetweenDateParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): PropertyDetailsBetweenDateResponse {
        return $this->client->invoke(
            'WS100239_propertyDetailsBetweenDate',
            $params,
            PropertyDetailsBetweenDateResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100240_landInfoByPersonIdAndParcelId: Хэрэглэгчийн дугаар болон нэгж талбарын дугаараар газартай холбоотой бүх мэдээлэл.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landInfoByPersonIdAndParcelId(
        LandInfoByPersonIdAndParcelIdParams $params = new LandInfoByPersonIdAndParcelIdParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandInfoByPersonIdAndParcelIdResponse {
        return $this->client->invoke(
            'WS100240_landInfoByPersonIdAndParcelId',
            $params,
            LandInfoByPersonIdAndParcelIdResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100241_landSettlementAct: Газрын төлбөр тооцоо нийлсэн акт.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function landSettlementAct(
        LandSettlementActParams $params = new LandSettlementActParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): LandSettlementActResponse {
        return $this->client->invoke(
            'WS100241_landSettlementAct',
            $params,
            LandSettlementActResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100243_electricRequirementRequest: Цахилгааны техникийн нөхцөлийн хүсэлт илгээх.
     *
     * Provider: Эрчим хүчний яам
     *
     * @throws \Xyp\Exception\XypException
     */
    public function electricRequirementRequest(
        ElectricRequirementRequestParams $params = new ElectricRequirementRequestParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): ElectricRequirementRequestResponse {
        return $this->client->invoke(
            'WS100243_electricRequirementRequest',
            $params,
            ElectricRequirementRequestResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100244_electricRequirementRequestDetails: Цахилгааны техникийн нөхцөлийн хүсэлтийн дэлгэрэнгүй мэдээлэл авах.
     *
     * Provider: Эрчим хүчний яам
     *
     * @throws \Xyp\Exception\XypException
     */
    public function electricRequirementRequestDetails(
        ElectricRequirementRequestDetailsParams $params = new ElectricRequirementRequestDetailsParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): ElectricRequirementRequestDetailsResponse {
        return $this->client->invoke(
            'WS100244_electricRequirementRequestDetails',
            $params,
            ElectricRequirementRequestDetailsResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100245_electricRequirementRequestHold: Цахилгааны техникийн нөхцөлийн хүсэлт засварлах.
     *
     * Provider: Эрчим хүчний яам
     *
     * @throws \Xyp\Exception\XypException
     */
    public function electricRequirementRequestHold(
        ElectricRequirementRequestHoldParams $params = new ElectricRequirementRequestHoldParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): ElectricRequirementRequestHoldResponse {
        return $this->client->invoke(
            'WS100245_electricRequirementRequestHold',
            $params,
            ElectricRequirementRequestHoldResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100246_electricRequirementRequestList: Цахилгааны техникийн нөхцөлийн хүсэлтийн жагсаалт авах.
     *
     * Provider: Эрчим хүчний яам
     *
     * @throws \Xyp\Exception\XypException
     */
    public function electricRequirementRequestList(
        ElectricRequirementRequestListParams $params = new ElectricRequirementRequestListParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): ElectricRequirementRequestListResponse {
        return $this->client->invoke(
            'WS100246_electricRequirementRequestList',
            $params,
            ElectricRequirementRequestListResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100247_electricRequirementRequestRemove: Цахилгааны техникийн нөхцөлийн хүсэлт устгах.
     *
     * Provider: Эрчим хүчний яам
     *
     * @throws \Xyp\Exception\XypException
     */
    public function electricRequirementRequestRemove(
        ElectricRequirementRequestRemoveParams $params = new ElectricRequirementRequestRemoveParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): ElectricRequirementRequestRemoveResponse {
        return $this->client->invoke(
            'WS100247_electricRequirementRequestRemove',
            $params,
            ElectricRequirementRequestRemoveResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100248_umnsPropertyInfo: ӨМНС үл хөдлөх хөрөнгийн мэдээлэл.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function umnsPropertyInfo(
        UmnsPropertyInfoParams $params = new UmnsPropertyInfoParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): UmnsPropertyInfoResponse {
        return $this->client->invoke(
            'WS100248_umnsPropertyInfo',
            $params,
            UmnsPropertyInfoResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100249_getPropertyTypeList: Эд хөрөнгөтэй эсэх төрлөөр.
     *
     * Provider: Газар зохион байгуулалт, геодези, зураг зүйн газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getPropertyTypeList(
        GetPropertyTypeListParams $params = new GetPropertyTypeListParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetPropertyTypeListResponse {
        return $this->client->invoke(
            'WS100249_getPropertyTypeList',
            $params,
            GetPropertyTypeListResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100251_getPropertyInfoEng: Иргэний эд хөрөнгийн англи лавлагааг авах сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getPropertyInfoEng(
        GetPropertyInfoEngParams $params = new GetPropertyInfoEngParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetPropertyInfoEngResponse {
        return $this->client->invoke(
            'WS100251_getPropertyInfoEng',
            $params,
            GetPropertyInfoEngResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100252_getPropertyInfoByNationalPropertyNumberEng: Иргэний эд хөрөнгийн англи лавлагааг эд хөрөнгийн дугаараар дуудах сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getPropertyInfoByNationalPropertyNumberEng(
        GetPropertyInfoByNationalPropertyNumberEngParams $params = new GetPropertyInfoByNationalPropertyNumberEngParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetPropertyInfoByNationalPropertyNumberEngResponse {
        return $this->client->invoke(
            'WS100252_getPropertyInfoByNationalPropertyNumberEng',
            $params,
            GetPropertyInfoByNationalPropertyNumberEngResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100253_getPropertyInfoCertificate: Үл хөдлөхийн гэрчилгээний хуулбар харах сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getPropertyInfoCertificate(
        GetPropertyInfoCertificateParams $params = new GetPropertyInfoCertificateParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetPropertyInfoCertificateResponse {
        return $this->client->invoke(
            'WS100253_getPropertyInfoCertificate',
            $params,
            GetPropertyInfoCertificateResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100254_getBankPropertyInquiry: Үл хөдлөх эд хөрөнгийн дэлгэрэнгүй лавлагаа-Банк.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function getBankPropertyInquiry(
        GetBankPropertyInquiryParams $params = new GetBankPropertyInquiryParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): GetBankPropertyInquiryResponse {
        return $this->client->invoke(
            'WS100254_getBankPropertyInquiry',
            $params,
            GetBankPropertyInquiryResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100255_hasBankPropertyInquiry: Үл хөдлөх эд хөрөнгөтэй эсэх лавлагаа- Банк.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function hasBankPropertyInquiry(
        HasBankPropertyInquiryParams $params = new HasBankPropertyInquiryParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): HasBankPropertyInquiryResponse {
        return $this->client->invoke(
            'WS100255_hasBankPropertyInquiry',
            $params,
            HasBankPropertyInquiryResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }

    /**
     * Calls WS100256_propertyInfoEng: Иргэний эд хөрөнгийн англи лавлагааг авах сервис.
     *
     * Provider: Улсын бүртгэлийн ерөнхий газар
     *
     * @throws \Xyp\Exception\XypException
     */
    public function propertyInfoEng(
        PropertyInfoEngParams $params = new PropertyInfoEngParams(),
        ?Auth $auth = null,
        ?Auth $operator = null,
    ): PropertyInfoEngResponse {
        return $this->client->invoke(
            'WS100256_propertyInfoEng',
            $params,
            PropertyInfoEngResponse::class,
            auth: $auth,
            operator: $operator,
        );
    }
}
