<?php

declare(strict_types=1);

// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

namespace Xyp\Property;

/**
 * Input of WS100248_umnsPropertyInfo: ӨМНС үл хөдлөх хөрөнгийн мэдээлэл.
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 *
 * Every field is optional: null, '' and [] are left out of the request.
 */
final readonly class UmnsPropertyInfoParams
{
    /**
     * @param string|null $regnum мэдээллийн жагсаалт
     */
    public function __construct(
        public ?string $regnum = null,
    ) {}
}
