"""GENERATED by xyp-generator from spec/services.json. Do not edit.

The `health` group: 76 services served from health-1.5.0.
Each service lives in its own module under `xyp.operations.health`.
"""

from __future__ import annotations

from xyp._service import AsyncService, SyncService
from xyp.operations.health import (
    check_payment_months as _check_payment_months,
)
from xyp.operations.health import (
    check_prescription_infoby_regnum as _check_prescription_infoby_regnum,
)
from xyp.operations.health import (
    citizen_image_diagnosis_and_analysis_info as _citizen_image_diagnosis_and_analysis_info,
)
from xyp.operations.health import (
    citizen_monthly_service_usage_inquiry_service as _citizen_monthly_service_usage_inquiry_service,
)
from xyp.operations.health import (
    citizen_questionnaire_submit_service as _citizen_questionnaire_submit_service,
)
from xyp.operations.health import (
    citizen_service_package_number_inquiry_service as _citizen_service_package_number_inquiry_service,
)
from xyp.operations.health import (
    covid_pcr_last_result_info as _covid_pcr_last_result_info,
)
from xyp.operations.health import (
    docter_degree_info as _docter_degree_info,
)
from xyp.operations.health import (
    doctor_license_check as _doctor_license_check,
)
from xyp.operations.health import (
    e_health_check_patient_exists as _e_health_check_patient_exists,
)
from xyp.operations.health import (
    e_health_create_patient as _e_health_create_patient,
)
from xyp.operations.health import (
    e_health_get_analysis_dates as _e_health_get_analysis_dates,
)
from xyp.operations.health import (
    e_health_get_analysis_result as _e_health_get_analysis_result,
)
from xyp.operations.health import (
    e_health_get_free_time_list as _e_health_get_free_time_list,
)
from xyp.operations.health import (
    e_health_get_hospitals as _e_health_get_hospitals,
)
from xyp.operations.health import (
    e_health_get_medical_services as _e_health_get_medical_services,
)
from xyp.operations.health import (
    e_health_list_service as _e_health_list_service,
)
from xyp.operations.health import (
    e_health_online_appointment_order as _e_health_online_appointment_order,
)
from xyp.operations.health import (
    e_health_online_time_order_list as _e_health_online_time_order_list,
)
from xyp.operations.health import (
    e_health_time_order_approve as _e_health_time_order_approve,
)
from xyp.operations.health import (
    e_health_time_order_cancel as _e_health_time_order_cancel,
)
from xyp.operations.health import (
    e_hospital_by_address as _e_hospital_by_address,
)
from xyp.operations.health import (
    e_hospital_check_patient_exists as _e_hospital_check_patient_exists,
)
from xyp.operations.health import (
    e_hospital_citizen_analysis_info as _e_hospital_citizen_analysis_info,
)
from xyp.operations.health import (
    e_hospital_create_patient as _e_hospital_create_patient,
)
from xyp.operations.health import (
    e_hospital_find_address as _e_hospital_find_address,
)
from xyp.operations.health import (
    e_hospital_get_analysis_dates as _e_hospital_get_analysis_dates,
)
from xyp.operations.health import (
    e_hospital_get_analysis_result as _e_hospital_get_analysis_result,
)
from xyp.operations.health import (
    e_hospital_get_free_time_list as _e_hospital_get_free_time_list,
)
from xyp.operations.health import (
    e_hospital_get_hospitals as _e_hospital_get_hospitals,
)
from xyp.operations.health import (
    e_hospital_get_medical_services as _e_hospital_get_medical_services,
)
from xyp.operations.health import (
    e_hospital_online_appointment_order as _e_hospital_online_appointment_order,
)
from xyp.operations.health import (
    e_hospital_online_time_order_list as _e_hospital_online_time_order_list,
)
from xyp.operations.health import (
    e_hospital_time_order_approve as _e_hospital_time_order_approve,
)
from xyp.operations.health import (
    e_hospital_time_order_cancel as _e_hospital_time_order_cancel,
)
from xyp.operations.health import (
    early_detection_service as _early_detection_service,
)
from xyp.operations.health import (
    get_active_pregnancy as _get_active_pregnancy,
)
from xyp.operations.health import (
    get_all_druglistings_info as _get_all_druglistings_info,
)
from xyp.operations.health import (
    get_ambulatory as _get_ambulatory,
)
from xyp.operations.health import (
    get_ambulatory_dtl as _get_ambulatory_dtl,
)
from xyp.operations.health import (
    get_blood_type_service as _get_blood_type_service,
)
from xyp.operations.health import (
    get_child_birth as _get_child_birth,
)
from xyp.operations.health import (
    get_child_book as _get_child_book,
)
from xyp.operations.health import (
    get_child_book_check_ups as _get_child_book_check_ups,
)
from xyp.operations.health import (
    get_children_birth_info as _get_children_birth_info,
)
from xyp.operations.health import (
    get_data_by_form_summary as _get_data_by_form_summary,
)
from xyp.operations.health import (
    get_drug_info as _get_drug_info,
)
from xyp.operations.health import (
    get_ecare_by_regnum as _get_ecare_by_regnum,
)
from xyp.operations.health import (
    get_emd_service_history as _get_emd_service_history,
)
from xyp.operations.health import (
    get_form13_a_info as _get_form13_a_info,
)
from xyp.operations.health import (
    get_form13_a_list as _get_form13_a_list,
)
from xyp.operations.health import (
    get_health_insurance_premium_list as _get_health_insurance_premium_list,
)
from xyp.operations.health import (
    get_hospital_list_info as _get_hospital_list_info,
)
from xyp.operations.health import (
    get_hospital_operation_info as _get_hospital_operation_info,
)
from xyp.operations.health import (
    get_hospitals_from_distance as _get_hospitals_from_distance,
)
from xyp.operations.health import (
    get_kid_question_result as _get_kid_question_result,
)
from xyp.operations.health import (
    get_kindergarten_analysis_result_by_child_regno as _get_kindergarten_analysis_result_by_child_regno,
)
from xyp.operations.health import (
    get_personal_info as _get_personal_info,
)
from xyp.operations.health import (
    get_receipt_by_regnum_and_number as _get_receipt_by_regnum_and_number,
)
from xyp.operations.health import (
    get_streptococcus as _get_streptococcus,
)
from xyp.operations.health import (
    get_vaccine_by_regnum_info as _get_vaccine_by_regnum_info,
)
from xyp.operations.health import (
    h_info_nc_diseases_report as _h_info_nc_diseases_report,
)
from xyp.operations.health import (
    medicine_import_insert as _medicine_import_insert,
)
from xyp.operations.health import (
    multi_degree_info as _multi_degree_info,
)
from xyp.operations.health import (
    multi_license_info as _multi_license_info,
)
from xyp.operations.health import (
    pregnancy_control_note_reference_info as _pregnancy_control_note_reference_info,
)
from xyp.operations.health import (
    pregnancy_summary as _pregnancy_summary,
)
from xyp.operations.health import (
    preventive_screening_info as _preventive_screening_info,
)
from xyp.operations.health import (
    receive_service_complain_data as _receive_service_complain_data,
)
from xyp.operations.health import (
    receive_tablet_complain as _receive_tablet_complain,
)
from xyp.operations.health import (
    request_prescription_register as _request_prescription_register,
)
from xyp.operations.health import (
    search_drug_images_by_barcode as _search_drug_images_by_barcode,
)
from xyp.operations.health import (
    search_for_drug_instructions_by_barcode as _search_for_drug_instructions_by_barcode,
)
from xyp.operations.health import (
    service_for_donor_card_check as _service_for_donor_card_check,
)
from xyp.operations.health import (
    service_for_sending_health_insurance as _service_for_sending_health_insurance,
)
from xyp.operations.health import (
    white_book_detail_info as _white_book_detail_info,
)


class HealthService(SyncService):
    """76 XYP services served from health-1.5.0."""

    e_health_get_hospitals = _e_health_get_hospitals.e_health_get_hospitals
    e_health_get_analysis_result = _e_health_get_analysis_result.e_health_get_analysis_result
    e_health_get_analysis_dates = _e_health_get_analysis_dates.e_health_get_analysis_dates
    e_health_check_patient_exists = _e_health_check_patient_exists.e_health_check_patient_exists
    e_health_create_patient = _e_health_create_patient.e_health_create_patient
    e_health_get_medical_services = _e_health_get_medical_services.e_health_get_medical_services
    e_health_get_free_time_list = _e_health_get_free_time_list.e_health_get_free_time_list
    e_health_online_time_order_list = (
        _e_health_online_time_order_list.e_health_online_time_order_list
    )
    e_health_online_appointment_order = (
        _e_health_online_appointment_order.e_health_online_appointment_order
    )
    e_health_time_order_approve = _e_health_time_order_approve.e_health_time_order_approve
    e_health_time_order_cancel = _e_health_time_order_cancel.e_health_time_order_cancel
    e_health_list_service = _e_health_list_service.e_health_list_service
    get_blood_type_service = _get_blood_type_service.get_blood_type_service
    early_detection_service = _early_detection_service.early_detection_service
    covid_pcr_last_result_info = _covid_pcr_last_result_info.covid_pcr_last_result_info
    medicine_import_insert = _medicine_import_insert.medicine_import_insert
    h_info_nc_diseases_report = _h_info_nc_diseases_report.h_info_nc_diseases_report
    get_form13_a_list = _get_form13_a_list.get_form13_a_list
    get_form13_a_info = _get_form13_a_info.get_form13_a_info
    e_hospital_find_address = _e_hospital_find_address.e_hospital_find_address
    e_hospital_by_address = _e_hospital_by_address.e_hospital_by_address
    e_hospital_check_patient_exists = (
        _e_hospital_check_patient_exists.e_hospital_check_patient_exists
    )
    e_hospital_citizen_analysis_info = (
        _e_hospital_citizen_analysis_info.e_hospital_citizen_analysis_info
    )
    e_hospital_create_patient = _e_hospital_create_patient.e_hospital_create_patient
    e_hospital_get_analysis_dates = _e_hospital_get_analysis_dates.e_hospital_get_analysis_dates
    e_hospital_get_analysis_result = _e_hospital_get_analysis_result.e_hospital_get_analysis_result
    e_hospital_get_free_time_list = _e_hospital_get_free_time_list.e_hospital_get_free_time_list
    e_hospital_get_hospitals = _e_hospital_get_hospitals.e_hospital_get_hospitals
    e_hospital_get_medical_services = (
        _e_hospital_get_medical_services.e_hospital_get_medical_services
    )
    e_hospital_online_appointment_order = (
        _e_hospital_online_appointment_order.e_hospital_online_appointment_order
    )
    e_hospital_online_time_order_list = (
        _e_hospital_online_time_order_list.e_hospital_online_time_order_list
    )
    e_hospital_time_order_approve = _e_hospital_time_order_approve.e_hospital_time_order_approve
    e_hospital_time_order_cancel = _e_hospital_time_order_cancel.e_hospital_time_order_cancel
    doctor_license_check = _doctor_license_check.doctor_license_check
    docter_degree_info = _docter_degree_info.docter_degree_info
    get_drug_info = _get_drug_info.get_drug_info
    check_prescription_infoby_regnum = (
        _check_prescription_infoby_regnum.check_prescription_infoby_regnum
    )
    get_receipt_by_regnum_and_number = (
        _get_receipt_by_regnum_and_number.get_receipt_by_regnum_and_number
    )
    request_prescription_register = _request_prescription_register.request_prescription_register
    citizen_image_diagnosis_and_analysis_info = (
        _citizen_image_diagnosis_and_analysis_info.citizen_image_diagnosis_and_analysis_info
    )
    get_emd_service_history = _get_emd_service_history.get_emd_service_history
    get_vaccine_by_regnum_info = _get_vaccine_by_regnum_info.get_vaccine_by_regnum_info
    get_all_druglistings_info = _get_all_druglistings_info.get_all_druglistings_info
    search_for_drug_instructions_by_barcode = (
        _search_for_drug_instructions_by_barcode.search_for_drug_instructions_by_barcode
    )
    search_drug_images_by_barcode = _search_drug_images_by_barcode.search_drug_images_by_barcode
    get_hospital_list_info = _get_hospital_list_info.get_hospital_list_info
    get_hospital_operation_info = _get_hospital_operation_info.get_hospital_operation_info
    get_health_insurance_premium_list = (
        _get_health_insurance_premium_list.get_health_insurance_premium_list
    )
    check_payment_months = _check_payment_months.check_payment_months
    get_data_by_form_summary = _get_data_by_form_summary.get_data_by_form_summary
    service_for_sending_health_insurance = (
        _service_for_sending_health_insurance.service_for_sending_health_insurance
    )
    pregnancy_control_note_reference_info = (
        _pregnancy_control_note_reference_info.pregnancy_control_note_reference_info
    )
    receive_service_complain_data = _receive_service_complain_data.receive_service_complain_data
    receive_tablet_complain = _receive_tablet_complain.receive_tablet_complain
    get_ambulatory = _get_ambulatory.get_ambulatory
    get_ambulatory_dtl = _get_ambulatory_dtl.get_ambulatory_dtl
    get_hospitals_from_distance = _get_hospitals_from_distance.get_hospitals_from_distance
    get_active_pregnancy = _get_active_pregnancy.get_active_pregnancy
    get_personal_info = _get_personal_info.get_personal_info
    get_ecare_by_regnum = _get_ecare_by_regnum.get_ecare_by_regnum
    get_children_birth_info = _get_children_birth_info.get_children_birth_info
    get_child_birth = _get_child_birth.get_child_birth
    get_child_book_check_ups = _get_child_book_check_ups.get_child_book_check_ups
    get_child_book = _get_child_book.get_child_book
    get_kid_question_result = _get_kid_question_result.get_kid_question_result
    pregnancy_summary = _pregnancy_summary.pregnancy_summary
    service_for_donor_card_check = _service_for_donor_card_check.service_for_donor_card_check
    get_kindergarten_analysis_result_by_child_regno = _get_kindergarten_analysis_result_by_child_regno.get_kindergarten_analysis_result_by_child_regno
    multi_degree_info = _multi_degree_info.multi_degree_info
    multi_license_info = _multi_license_info.multi_license_info
    get_streptococcus = _get_streptococcus.get_streptococcus
    preventive_screening_info = _preventive_screening_info.preventive_screening_info
    white_book_detail_info = _white_book_detail_info.white_book_detail_info
    citizen_service_package_number_inquiry_service = _citizen_service_package_number_inquiry_service.citizen_service_package_number_inquiry_service
    citizen_monthly_service_usage_inquiry_service = (
        _citizen_monthly_service_usage_inquiry_service.citizen_monthly_service_usage_inquiry_service
    )
    citizen_questionnaire_submit_service = (
        _citizen_questionnaire_submit_service.citizen_questionnaire_submit_service
    )


class AsyncHealthService(AsyncService):
    """76 XYP services served from health-1.5.0."""

    e_health_get_hospitals = _e_health_get_hospitals.e_health_get_hospitals_async
    e_health_get_analysis_result = _e_health_get_analysis_result.e_health_get_analysis_result_async
    e_health_get_analysis_dates = _e_health_get_analysis_dates.e_health_get_analysis_dates_async
    e_health_check_patient_exists = (
        _e_health_check_patient_exists.e_health_check_patient_exists_async
    )
    e_health_create_patient = _e_health_create_patient.e_health_create_patient_async
    e_health_get_medical_services = (
        _e_health_get_medical_services.e_health_get_medical_services_async
    )
    e_health_get_free_time_list = _e_health_get_free_time_list.e_health_get_free_time_list_async
    e_health_online_time_order_list = (
        _e_health_online_time_order_list.e_health_online_time_order_list_async
    )
    e_health_online_appointment_order = (
        _e_health_online_appointment_order.e_health_online_appointment_order_async
    )
    e_health_time_order_approve = _e_health_time_order_approve.e_health_time_order_approve_async
    e_health_time_order_cancel = _e_health_time_order_cancel.e_health_time_order_cancel_async
    e_health_list_service = _e_health_list_service.e_health_list_service_async
    get_blood_type_service = _get_blood_type_service.get_blood_type_service_async
    early_detection_service = _early_detection_service.early_detection_service_async
    covid_pcr_last_result_info = _covid_pcr_last_result_info.covid_pcr_last_result_info_async
    medicine_import_insert = _medicine_import_insert.medicine_import_insert_async
    h_info_nc_diseases_report = _h_info_nc_diseases_report.h_info_nc_diseases_report_async
    get_form13_a_list = _get_form13_a_list.get_form13_a_list_async
    get_form13_a_info = _get_form13_a_info.get_form13_a_info_async
    e_hospital_find_address = _e_hospital_find_address.e_hospital_find_address_async
    e_hospital_by_address = _e_hospital_by_address.e_hospital_by_address_async
    e_hospital_check_patient_exists = (
        _e_hospital_check_patient_exists.e_hospital_check_patient_exists_async
    )
    e_hospital_citizen_analysis_info = (
        _e_hospital_citizen_analysis_info.e_hospital_citizen_analysis_info_async
    )
    e_hospital_create_patient = _e_hospital_create_patient.e_hospital_create_patient_async
    e_hospital_get_analysis_dates = (
        _e_hospital_get_analysis_dates.e_hospital_get_analysis_dates_async
    )
    e_hospital_get_analysis_result = (
        _e_hospital_get_analysis_result.e_hospital_get_analysis_result_async
    )
    e_hospital_get_free_time_list = (
        _e_hospital_get_free_time_list.e_hospital_get_free_time_list_async
    )
    e_hospital_get_hospitals = _e_hospital_get_hospitals.e_hospital_get_hospitals_async
    e_hospital_get_medical_services = (
        _e_hospital_get_medical_services.e_hospital_get_medical_services_async
    )
    e_hospital_online_appointment_order = (
        _e_hospital_online_appointment_order.e_hospital_online_appointment_order_async
    )
    e_hospital_online_time_order_list = (
        _e_hospital_online_time_order_list.e_hospital_online_time_order_list_async
    )
    e_hospital_time_order_approve = (
        _e_hospital_time_order_approve.e_hospital_time_order_approve_async
    )
    e_hospital_time_order_cancel = _e_hospital_time_order_cancel.e_hospital_time_order_cancel_async
    doctor_license_check = _doctor_license_check.doctor_license_check_async
    docter_degree_info = _docter_degree_info.docter_degree_info_async
    get_drug_info = _get_drug_info.get_drug_info_async
    check_prescription_infoby_regnum = (
        _check_prescription_infoby_regnum.check_prescription_infoby_regnum_async
    )
    get_receipt_by_regnum_and_number = (
        _get_receipt_by_regnum_and_number.get_receipt_by_regnum_and_number_async
    )
    request_prescription_register = (
        _request_prescription_register.request_prescription_register_async
    )
    citizen_image_diagnosis_and_analysis_info = (
        _citizen_image_diagnosis_and_analysis_info.citizen_image_diagnosis_and_analysis_info_async
    )
    get_emd_service_history = _get_emd_service_history.get_emd_service_history_async
    get_vaccine_by_regnum_info = _get_vaccine_by_regnum_info.get_vaccine_by_regnum_info_async
    get_all_druglistings_info = _get_all_druglistings_info.get_all_druglistings_info_async
    search_for_drug_instructions_by_barcode = (
        _search_for_drug_instructions_by_barcode.search_for_drug_instructions_by_barcode_async
    )
    search_drug_images_by_barcode = (
        _search_drug_images_by_barcode.search_drug_images_by_barcode_async
    )
    get_hospital_list_info = _get_hospital_list_info.get_hospital_list_info_async
    get_hospital_operation_info = _get_hospital_operation_info.get_hospital_operation_info_async
    get_health_insurance_premium_list = (
        _get_health_insurance_premium_list.get_health_insurance_premium_list_async
    )
    check_payment_months = _check_payment_months.check_payment_months_async
    get_data_by_form_summary = _get_data_by_form_summary.get_data_by_form_summary_async
    service_for_sending_health_insurance = (
        _service_for_sending_health_insurance.service_for_sending_health_insurance_async
    )
    pregnancy_control_note_reference_info = (
        _pregnancy_control_note_reference_info.pregnancy_control_note_reference_info_async
    )
    receive_service_complain_data = (
        _receive_service_complain_data.receive_service_complain_data_async
    )
    receive_tablet_complain = _receive_tablet_complain.receive_tablet_complain_async
    get_ambulatory = _get_ambulatory.get_ambulatory_async
    get_ambulatory_dtl = _get_ambulatory_dtl.get_ambulatory_dtl_async
    get_hospitals_from_distance = _get_hospitals_from_distance.get_hospitals_from_distance_async
    get_active_pregnancy = _get_active_pregnancy.get_active_pregnancy_async
    get_personal_info = _get_personal_info.get_personal_info_async
    get_ecare_by_regnum = _get_ecare_by_regnum.get_ecare_by_regnum_async
    get_children_birth_info = _get_children_birth_info.get_children_birth_info_async
    get_child_birth = _get_child_birth.get_child_birth_async
    get_child_book_check_ups = _get_child_book_check_ups.get_child_book_check_ups_async
    get_child_book = _get_child_book.get_child_book_async
    get_kid_question_result = _get_kid_question_result.get_kid_question_result_async
    pregnancy_summary = _pregnancy_summary.pregnancy_summary_async
    service_for_donor_card_check = _service_for_donor_card_check.service_for_donor_card_check_async
    get_kindergarten_analysis_result_by_child_regno = _get_kindergarten_analysis_result_by_child_regno.get_kindergarten_analysis_result_by_child_regno_async
    multi_degree_info = _multi_degree_info.multi_degree_info_async
    multi_license_info = _multi_license_info.multi_license_info_async
    get_streptococcus = _get_streptococcus.get_streptococcus_async
    preventive_screening_info = _preventive_screening_info.preventive_screening_info_async
    white_book_detail_info = _white_book_detail_info.white_book_detail_info_async
    citizen_service_package_number_inquiry_service = _citizen_service_package_number_inquiry_service.citizen_service_package_number_inquiry_service_async
    citizen_monthly_service_usage_inquiry_service = _citizen_monthly_service_usage_inquiry_service.citizen_monthly_service_usage_inquiry_service_async
    citizen_questionnaire_submit_service = (
        _citizen_questionnaire_submit_service.citizen_questionnaire_submit_service_async
    )
