// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.education;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.util.List;

/**
 * The response of {@code WS400122_DiplomaCopyBilingualService}: Дипломын хуулбар/англи, монгол/
 * дуудах сервис.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param detailData Жагсаалт
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record DiplomaCopyBilingualServiceResponse(List<DetailData> detailData, Extras extras) {

  static DiplomaCopyBilingualServiceResponse decode(ResponseReader reader) {
    return new DiplomaCopyBilingualServiceResponse(
        reader.get("detailData", Decoders.list(Decoders.object(DetailData::decode))),
        reader.extras());
  }

  /**
   * Жагсаалт.
   *
   * @param url pdf url/англи, монгол/
   */
  public record DetailData(String url) {

    static DetailData decode(ResponseReader reader) {
      return new DetailData(reader.get("url", Decoders.STRING));
    }
  }
}
