// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package io.github.baljinnyamday.xyp.education;

import io.github.baljinnyamday.xyp.Decoders;
import io.github.baljinnyamday.xyp.Extras;
import io.github.baljinnyamday.xyp.ResponseReader;
import java.math.BigDecimal;
import java.util.List;

/**
 * The response of {@code WS400107_studentCard}: Оюутны цахим карт.
 *
 * <p>A field XYP left out, or sent in a shape this record does not expect, is {@code null} (an
 * empty list for a list); {@link #extras()} tells the two apart.
 *
 * @param listData Оюутны мэдээлэл
 * @param extras the response fields that did not fit this record (their component is {@code null}
 *     or empty) and the raw response, including the fields this record does not declare
 */
public record StudentCardResponse(List<ListData> listData, Extras extras) {

  /**
   * Decodes this record from a response tree. The generated client uses it; it is public so you can
   * decode a tree you already hold, with {@link ResponseReader#decode}.
   *
   * @param reader the reader over this record's element
   * @return the decoded record
   */
  public static StudentCardResponse decode(ResponseReader reader) {
    return new StudentCardResponse(
        reader.get("listData", Decoders.list(Decoders.object(ListData::decode))), reader.extras());
  }

  /**
   * Оюутны мэдээлэл.
   *
   * @param academicLevel Курс, дамжаа
   * @param address Сургалтын байгууллагын хаяг /салбар сургуулийн хаяг нийслэл, орон нутаг/
   * @param educationLevelId 1-&amp;
   * @param academicShiftId 1-&amp;
   * @param academicShiftName "Боловсролын хэлбэр Өдөр Орой Эчнээ-"
   * @param programId Оюутны цахим үнэмлэхний дугаар
   * @param institutionName Сургуулийн нэр
   * @param schoolName Салбар сургуулийн нэр
   * @param lastName Овог
   * @param firstName Нэр
   * @param fieldName Сургалтын хөтөлбөрийн нэр
   * @param fieldCode Сургалтын хөтөлбөрийн индекс
   * @param levelName Боловсролын түвшин
   * @param institutionId the {@code institutionId} field
   */
  public record ListData(
      String academicLevel,
      String address,
      String educationLevelId,
      String academicShiftId,
      String academicShiftName,
      String programId,
      String institutionName,
      String schoolName,
      String lastName,
      String firstName,
      String fieldName,
      String fieldCode,
      String levelName,
      BigDecimal institutionId) {

    /**
     * Decodes this record from a response tree. The generated client uses it; it is public so you
     * can decode a tree you already hold, with {@link ResponseReader#decode}.
     *
     * @param reader the reader over this record's element
     * @return the decoded record
     */
    public static ListData decode(ResponseReader reader) {
      return new ListData(
          reader.get("academicLevel", Decoders.STRING),
          reader.get("address", Decoders.STRING),
          reader.get("educationLevelId", Decoders.STRING),
          reader.get("academicShiftId", Decoders.STRING),
          reader.get("academicShiftName", Decoders.STRING),
          reader.get("programId", Decoders.STRING),
          reader.get("institutionName", Decoders.STRING),
          reader.get("schoolName", Decoders.STRING),
          reader.get("lastName", Decoders.STRING),
          reader.get("firstName", Decoders.STRING),
          reader.get("fieldName", Decoders.STRING),
          reader.get("fieldCode", Decoders.STRING),
          reader.get("levelName", Decoders.STRING),
          reader.get("institutionId", Decoders.DECIMAL));
    }
  }
}
