"""GENERATED by xyp-generator from spec/services.json. Do not edit.

WS100837_paymentReceived (payment, Улсын бүртгэлийн ерөнхий газар)
"""
# Operation modules are this package's own internals, so they may use the service's transport.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from pydantic import Field

from xyp._models import XypModel, parse_model
from xyp._service import AsyncService, SyncService
from xyp.auth import CitizenAuth, OperatorAuth

_OPERATION = "WS100837_paymentReceived"


class PaymentReceivedResponse(XypModel):
    """WS100837_paymentReceived: Төлбөр хүлээн авсан мэдээллийн сервес"""

    code: int | None = Field(default=None, alias="code", description="амжилттай бол 0")
    msg: str | None = Field(default=None, alias="msg", description="хариу мэдэгдэл")


def payment_received(
    self: SyncService,
    *,
    service_code: str | None = None,
    org_password: str | None = None,
    org_token: str | None = None,
    org_code: str | None = None,
    org_name: str | None = None,
    regnum: str | None = None,
    program_type: str | None = None,
    document_number: str | None = None,
    amount: str | None = None,
    product_id: str | None = None,
    product_name: str | None = None,
    source_id: str | None = None,
    bank_name: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> PaymentReceivedResponse:
    """WS100837_paymentReceived: Төлбөр хүлээн авсан мэдээллийн сервес

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        service_code: Сервисын нэр
        org_password: Нууц үг
        org_token: Токен
        org_code: Байгууллагын код
        org_name: Байгууллагын нэр
        regnum: Регистрийн дугаар
        program_type: программын төрөл
        document_number: баримт бичгийн дугаар
        amount: дүн
        product_id: бүтээгдэхүүний дугаар
        product_name: бүтээгдэхүүний нэр
        source_id: эх сурвалж
        bank_name: банкны нэр
    """
    data = self._transport.call(
        _OPERATION,
        {
            "serviceCode": service_code,
            "orgPassword": org_password,
            "orgToken": org_token,
            "orgCode": org_code,
            "orgName": org_name,
            "regnum": regnum,
            "programType": program_type,
            "documentNumber": document_number,
            "amount": amount,
            "productId": product_id,
            "productName": product_name,
            "sourceId": source_id,
            "bankName": bank_name,
        },
        auth,
        operator,
    )
    return parse_model(PaymentReceivedResponse, data)


async def payment_received_async(
    self: AsyncService,
    *,
    service_code: str | None = None,
    org_password: str | None = None,
    org_token: str | None = None,
    org_code: str | None = None,
    org_name: str | None = None,
    regnum: str | None = None,
    program_type: str | None = None,
    document_number: str | None = None,
    amount: str | None = None,
    product_id: str | None = None,
    product_name: str | None = None,
    source_id: str | None = None,
    bank_name: str | None = None,
    auth: CitizenAuth | None = None,
    operator: OperatorAuth | None = None,
) -> PaymentReceivedResponse:
    """WS100837_paymentReceived: Төлбөр хүлээн авсан мэдээллийн сервес

    Provider: Улсын бүртгэлийн ерөнхий газар

    Args:
        service_code: Сервисын нэр
        org_password: Нууц үг
        org_token: Токен
        org_code: Байгууллагын код
        org_name: Байгууллагын нэр
        regnum: Регистрийн дугаар
        program_type: программын төрөл
        document_number: баримт бичгийн дугаар
        amount: дүн
        product_id: бүтээгдэхүүний дугаар
        product_name: бүтээгдэхүүний нэр
        source_id: эх сурвалж
        bank_name: банкны нэр
    """
    data = await self._transport.call(
        _OPERATION,
        {
            "serviceCode": service_code,
            "orgPassword": org_password,
            "orgToken": org_token,
            "orgCode": org_code,
            "orgName": org_name,
            "regnum": regnum,
            "programType": program_type,
            "documentNumber": document_number,
            "amount": amount,
            "productId": product_id,
            "productName": product_name,
            "sourceId": source_id,
            "bankName": bank_name,
        },
        auth,
        operator,
    )
    return parse_model(PaymentReceivedResponse, data)
