// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package health

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// EHealthGetFreeTimeListParams is the input of WS300108_eHealthGetFreeTimeList. Every field is
// optional; a zero value is left out of the request.
type EHealthGetFreeTimeListParams struct {
	// эмнэлэгийн дугаар
	HospitalId *int64 `xyp:"hospitalId"`
	// Үйлчилгээний дугаар
	ServiceId string `xyp:"serviceId"`
	// эхлэх огноо "yyyy-MM-dd"
	StartDate string `xyp:"startDate"`
	// дуусах огноо "yyyy-MM-dd"
	EndDate string `xyp:"endDate"`
}

// EHealthGetFreeTimeListListData: сул цагийн жагсаалт
type EHealthGetFreeTimeListListData struct {
	// сул цагийн огноо
	Date string `xyp:"date"`
	// цагийн дугаарлалт
	Num *int64 `xyp:"num"`
	// сул цаг
	Time string `xyp:"time"`
}

// EHealthGetFreeTimeListResponse is the response of WS300108_eHealthGetFreeTimeList: EHealth сонгосон үйлчилгээний сул цагийг интервалаар харах.
type EHealthGetFreeTimeListResponse struct {
	// сул цагийн жагсаалт
	ListData []EHealthGetFreeTimeListListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// EHealthGetFreeTimeList calls WS300108_eHealthGetFreeTimeList: EHealth сонгосон үйлчилгээний сул цагийг интервалаар харах
//
// Provider: Эрүүл мэндийн яам
func (s *Service) EHealthGetFreeTimeList(ctx context.Context, params EHealthGetFreeTimeListParams, opts ...xyp.CallOption) (*EHealthGetFreeTimeListResponse, error) {
	var out EHealthGetFreeTimeListResponse
	extras, err := s.client.Invoke(ctx, "WS300108_eHealthGetFreeTimeList", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
