// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package health

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// EHospitalTimeOrderApproveParams is the input of WS300136_eHospitalTimeOrderApprove. Every field is
// optional; a zero value is left out of the request.
type EHospitalTimeOrderApproveParams struct {
	// Эмнэлгийн дугаар
	HospitalId *int64 `xyp:"hospitalId"`
	// Баталгаажуулах код
	VerifyCode string `xyp:"verifyCode"`
}

// EHospitalTimeOrderApproveResponse is the response of WS300136_eHospitalTimeOrderApprove: EHospital Цаг захиалгын бүртгэл баталгаажуулах.
type EHospitalTimeOrderApproveResponse struct {
	// хүсэлтийн хариу код
	CheckCode *int64 `xyp:"checkCode"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// EHospitalTimeOrderApprove calls WS300136_eHospitalTimeOrderApprove: EHospital Цаг захиалгын бүртгэл баталгаажуулах
//
// Provider: Эрүүл мэндийн даатгалын ерөнхий газар
func (s *Service) EHospitalTimeOrderApprove(ctx context.Context, params EHospitalTimeOrderApproveParams, opts ...xyp.CallOption) (*EHospitalTimeOrderApproveResponse, error) {
	var out EHospitalTimeOrderApproveResponse
	extras, err := s.client.Invoke(ctx, "WS300136_eHospitalTimeOrderApprove", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
