// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package health

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// EHospitalGetHospitalsParams is the input of WS300132_eHospitalGetHospitals. Every field is
// optional; a zero value is left out of the request.
type EHospitalGetHospitalsParams struct {
	IsGov *int64 `xyp:"isGov"`
}

// EHospitalGetHospitalsListData: эмнэлгийн жагсаалт
type EHospitalGetHospitalsListData struct {
	// эмнэлгийн дугаар
	HospitalId *int64 `xyp:"hospitalId"`
	// эмнэлгийн нэр
	HospitalName string `xyp:"hospitalName"`
	// эрэмбэ
	Priority string `xyp:"priority"`
}

// EHospitalGetHospitalsResponse is the response of WS300132_eHospitalGetHospitals: EHospital эмнэлгийн жагсаалт дуудах сервис.
type EHospitalGetHospitalsResponse struct {
	// эмнэлгийн жагсаалт
	ListData []EHospitalGetHospitalsListData `xyp:"listData"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// EHospitalGetHospitals calls WS300132_eHospitalGetHospitals: EHospital эмнэлгийн жагсаалт дуудах сервис
//
// Provider: Эрүүл мэндийн даатгалын ерөнхий газар
func (s *Service) EHospitalGetHospitals(ctx context.Context, params EHospitalGetHospitalsParams, opts ...xyp.CallOption) (*EHospitalGetHospitalsResponse, error) {
	var out EHospitalGetHospitalsResponse
	extras, err := s.client.Invoke(ctx, "WS300132_eHospitalGetHospitals", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
