// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package health

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// GetHospitalOperationInfoParams is the input of WS300151_GetHospitalOperationInfo. Every field is
// optional; a zero value is left out of the request.
type GetHospitalOperationInfoParams struct {
	// Төлөв
	Status *bool `xyp:"status"`
}

// GetHospitalOperationInfoData: Жагсаалт
type GetHospitalOperationInfoData struct {
	// Үйл ажиллагааны чиглэлийн дугаар
	Id *int64 `xyp:"id"`
	// Үйл ажиллагааны чиглэлийн код
	Code string `xyp:"code"`
	// Үйл ажиллагааны чиглэлийн нэр
	Name string `xyp:"name"`
	// Идэвхитэй эсэх. 1-тийм, 0-үгүй
	Status *int64 `xyp:"status"`
}

// GetHospitalOperationInfoResponse is the response of WS300151_GetHospitalOperationInfo: Эмнэлгийн үйл ажиллагааны чиглэлийн мэдэллийг татах сервис.
type GetHospitalOperationInfoResponse struct {
	// Жагсаалт
	Data []GetHospitalOperationInfoData `xyp:"data"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// GetHospitalOperationInfo calls WS300151_GetHospitalOperationInfo: Эмнэлгийн үйл ажиллагааны чиглэлийн мэдэллийг татах сервис
//
// Provider: Эрүүл мэндийн яам
func (s *Service) GetHospitalOperationInfo(ctx context.Context, params GetHospitalOperationInfoParams, opts ...xyp.CallOption) (*GetHospitalOperationInfoResponse, error) {
	var out GetHospitalOperationInfoResponse
	extras, err := s.client.Invoke(ctx, "WS300151_GetHospitalOperationInfo", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
