// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package governmentservice

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// AgriculturalIncentiveReceiptServiceParams is the input of GS10064_AgriculturalIncentiveReceiptService. Every field is
// optional; a zero value is left out of the request.
type AgriculturalIncentiveReceiptServiceParams struct {
	// Урамшуулалт хамрагдсан этгээдийн регистр
	Regnum string `xyp:"regnum"`
	// Төлбөрийн баримтын он
	Year *int64 `xyp:"year"`
	// Төлбөрийн баримтын сар
	Month *int64 `xyp:"month"`
	// Төлбөрийн баримтны ДДТД
	Ddtd string `xyp:"ddtd"`
	// Урамшуулалд хамрагдсан огноо
	BonusDate string `xyp:"bonusDate"`
	// Баримтын урамшуулал олгогдсон төлөв 0 бол цуцлагдсан, 1 бол олгогдохоор илгээсэн, 2 бол олгогдсон
	Status *int64 `xyp:"status"`
}

// AgriculturalIncentiveReceiptServiceResponse is the response of GS10064_AgriculturalIncentiveReceiptService: ХАА-н урамшуулалд хамрагдсан төлбөрийн баримтын мэдээлэл хадгалах сервис.
type AgriculturalIncentiveReceiptServiceResponse struct {
	// хариу
	Msg string `xyp:"msg"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// AgriculturalIncentiveReceiptService calls GS10064_AgriculturalIncentiveReceiptService: ХАА-н урамшуулалд хамрагдсан төлбөрийн баримтын мэдээлэл хадгалах сервис
//
// Provider: Татварын ерөнхий газар
func (s *Service) AgriculturalIncentiveReceiptService(ctx context.Context, params AgriculturalIncentiveReceiptServiceParams, opts ...xyp.CallOption) (*AgriculturalIncentiveReceiptServiceResponse, error) {
	var out AgriculturalIncentiveReceiptServiceResponse
	extras, err := s.client.Invoke(ctx, "GS10064_AgriculturalIncentiveReceiptService", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
