// Code generated by xyp-generator from spec/services.json. DO NOT EDIT.

package governmentservice

import (
	"context"

	"github.com/baljinnyamday/xyp-sdk/packages/go/xyp"
)

// CreateComplaintRatingParams is the input of GS10066_CreateComplaintRating. Every field is
// optional; a zero value is left out of the request.
type CreateComplaintRatingParams struct {
	SessionId       *int64 `xyp:"sessionId"`
	LastDepartment  string `xyp:"lastDepartment"`
	Rating          *int64 `xyp:"rating"`
	Description     string `xyp:"description"`
	RatingReasonIds []any  `xyp:"ratingReasonIds"`
}

// CreateComplaintRatingResponse is the response of GS10066_CreateComplaintRating: Санал асуулга Үнэлгээ өгөх.
type CreateComplaintRatingResponse struct {
	RatingId *int64 `xyp:"ratingId"`

	// Xyp carries what this struct could not. Mismatches lists the response
	// fields that did not fit the model (they kept their zero value), and Raw is
	// the whole response, including fields this struct does not declare.
	Xyp xyp.Extras `xyp:"-"`
}

// CreateComplaintRating calls GS10066_CreateComplaintRating: Санал асуулга Үнэлгээ өгөх
//
// Provider: Засгийн газрын Хэрэг эрхлэх газар
func (s *Service) CreateComplaintRating(ctx context.Context, params CreateComplaintRatingParams, opts ...xyp.CallOption) (*CreateComplaintRatingResponse, error) {
	var out CreateComplaintRatingResponse
	extras, err := s.client.Invoke(ctx, "GS10066_CreateComplaintRating", params, &out, opts...)
	if err != nil {
		return nil, err
	}
	out.Xyp = extras
	return &out, nil
}
