/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS100108_citizenLookUpInfo (citizen, Улсын бүртгэлийн ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS100108_citizenLookUpInfo";

/** Input of WS100108_citizenLookUpInfo. */
export interface CitizenLookUpInfoParams {
  /** нэр */
  readonly firstname?: string;
  /** овог */
  readonly lastname?: string;
  /** регистэр */
  readonly regnum?: string;
  /** ургийн овог */
  readonly surname?: string;
  /** төрөл */
  readonly type?: number;
}

/** жагсаалт */
export interface CitizenLookUpInfoListData {
  /** Бүртгэлийн ID */
  readonly civilId: string | null;
  /** Регистрийн дугаар */
  readonly regnum: string | null;
  /** Ургийн овог */
  readonly firstname: string | null;
  /** Эцэг/эх/ийн нэр */
  readonly lastname: string | null;
  /** Нэр */
  readonly surname: string | null;
  /** Төрсөн огноо */
  readonly birthDateAsText: string | null;
  /** Хүйс */
  readonly gender: string | null;
  /** Харъяалал */
  readonly nationality: string | null;
  /** Яс, үндсэн */
  readonly originName: string | null;
  /** Төлөв */
  readonly civilStatusName: string | null;
  /** Дэлгэрэнгүй хаяг */
  readonly fullAddress: string | null;
  /** Эхийн регистрийн дугаар */
  readonly motherRegnum: string | null;
  /** Эцгийн регистрийн дугаар */
  readonly fatherRegnum: string | null;
  /** Нас барсан огноо */
  readonly deceaseDateAsText: string | null;
  /** Нас барсан аймаг/хотын нэр */
  readonly deceaseAimagCityName: string | null;
  /** Нас барсан сум/дүүрэг нэр */
  readonly deceaseSoumDistrictName: string | null;
  /** Нас барсан шалтгаан */
  readonly deceaseCaouseName: string | null;
  /** Зарлигын дугаар */
  readonly ordinanceNum: string | null;
  /** Зарлигын огноо */
  readonly ordinanceDateAsText: string | null;
  /** Харяатаас гарсан шалтгаан */
  readonly denationalizationName: string | null;
  /** Харъяатаас гарсан улс */
  readonly denationalizationNationalityName: string | null;
}

/** WS100108_citizenLookUpInfo: Иргэний мэдээлэл хайх */
export interface CitizenLookUpInfoResponse {
  /** жагсаалт */
  readonly listData: readonly CitizenLookUpInfoListData[] | null;
}

const SCHEMA: Schema = {
  listData: {
    list: {
      object: {
        civilId: "string",
        regnum: "string",
        firstname: "string",
        lastname: "string",
        surname: "string",
        birthDateAsText: "string",
        gender: "string",
        nationality: "string",
        originName: "string",
        civilStatusName: "string",
        fullAddress: "string",
        motherRegnum: "string",
        fatherRegnum: "string",
        deceaseDateAsText: "string",
        deceaseAimagCityName: "string",
        deceaseSoumDistrictName: "string",
        deceaseCaouseName: "string",
        ordinanceNum: "string",
        ordinanceDateAsText: "string",
        denationalizationName: "string",
        denationalizationNationalityName: "string",
      },
    },
  },
};

/**
 * WS100108_citizenLookUpInfo: Иргэний мэдээлэл хайх
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
export async function citizenLookUpInfo(transport: Transport, params: CitizenLookUpInfoParams = {}, options: CallOptions = {}): Promise<XypResult<CitizenLookUpInfoResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      firstname: params.firstname,
      lastname: params.lastname,
      regnum: params.regnum,
      surname: params.surname,
      type: params.type,
    },
    options,
  );
  return decodeResponse<CitizenLookUpInfoResponse>("CitizenLookUpInfoResponse", SCHEMA, data);
}
