/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS101125_citizenKindergartenDescription (citizen, Боловсрол шинжлэх ухааны яам)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS101125_citizenKindergartenDescription";

/** Input of WS101125_citizenKindergartenDescription. */
export interface CitizenKindergartenDescriptionParams {
  /** Регистрийн дугаар */
  readonly regnum?: string;
}

/** WS101125_citizenKindergartenDescription: сургуулийн өмнөх боловсролын сургалтын байгууллагад суралцаж байгаа тодорхойлолтийн мэдээлэл дуудах */
export interface CitizenKindergartenDescriptionResponse {
  /** регистрийн дугаар */
  readonly regnum: string | null;
  /** овог */
  readonly lastname: string | null;
  /** нэр */
  readonly firstname: string | null;
  /** эхлэх хугацаа */
  readonly academicYearFrom: string | null;
  /** дуусах хугацаа */
  readonly academicYearTo: string | null;
  /** сургуулийн нэр */
  readonly schoolName: string | null;
  /** анги */
  readonly academicLevelName: string | null;
}

const SCHEMA: Schema = { regnum: "string", lastname: "string", firstname: "string", academicYearFrom: "string", academicYearTo: "string", schoolName: "string", academicLevelName: "string" };

/**
 * WS101125_citizenKindergartenDescription: сургуулийн өмнөх боловсролын сургалтын байгууллагад суралцаж байгаа тодорхойлолтийн мэдээлэл дуудах
 *
 * Provider: Боловсрол шинжлэх ухааны яам
 */
export async function citizenKindergartenDescription(transport: Transport, params: CitizenKindergartenDescriptionParams = {}, options: CallOptions = {}): Promise<XypResult<CitizenKindergartenDescriptionResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
    },
    options,
  );
  return decodeResponse<CitizenKindergartenDescriptionResponse>("CitizenKindergartenDescriptionResponse", SCHEMA, data);
}
