/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS101187_CivilServiceEmployeeInfo (citizen, Төрийн албаны зөвлөл)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS101187_CivilServiceEmployeeInfo";

/** Input of WS101187_CivilServiceEmployeeInfo. */
export interface CivilServiceEmployeeInfoParams {
  /** Регистрийн дугаар */
  readonly regnum?: string;
  /** Бүртгэлийн дугаар */
  readonly civilId?: string;
}

/** WS101187_CivilServiceEmployeeInfo: Төрийн албан хаагчийн мэдээлэл авах сервис */
export interface CivilServiceEmployeeInfoResponse {
  /** Байгууллагын бүртгэлийн дугаар */
  readonly orgRegnum: string | null;
  /** Байгууллагын нэр */
  readonly orgName: string | null;
  /** Эдийн засгийн ангиллын төрөл */
  readonly orgEconomicTypeName: string | null;
  /** Эдийн засгийн төрөл */
  readonly orgSubEconomicTypeName: string | null;
  /** Харьяалагдах хэлтэс */
  readonly departmentName: string | null;
  /** Албан тушаалын код */
  readonly positionCode: string | null;
  /** Албан тушаалын нэр */
  readonly positionName: string | null;
  /** Албан тушаалын төрөл / түвшин */
  readonly positionTypeName: string | null;
  /** Ажлын код */
  readonly jobCode: string | null;
  /** Ажлын нэр */
  readonly jobName: string | null;
  /** Албан тушаалын зэрэглэл */
  readonly jobCategoryName: string | null;
  /** Албан тушаалын зэрэг */
  readonly jobGradeName: string | null;
  /** Төрийн албаны ангилал */
  readonly govCategoryName: string | null;
  /** Эцгийн нэр */
  readonly foreName: string | null;
  /** Овог */
  readonly surName: string | null;
  /** Нэр */
  readonly givenName: string | null;
  /** Хүйс */
  readonly genderCode: string | null;
  /** Төрсөн өдөр */
  readonly birthDate: string | null;
  /** Регистрийн дугаар */
  readonly regnum: string | null;
  /** Бүртгэлийн дугаар */
  readonly civilId: string | null;
}

const SCHEMA: Schema = {
  orgRegnum: "string",
  orgName: "string",
  orgEconomicTypeName: "string",
  orgSubEconomicTypeName: "string",
  departmentName: "string",
  positionCode: "string",
  positionName: "string",
  positionTypeName: "string",
  jobCode: "string",
  jobName: "string",
  jobCategoryName: "string",
  jobGradeName: "string",
  govCategoryName: "string",
  foreName: "string",
  surName: "string",
  givenName: "string",
  genderCode: "string",
  birthDate: "string",
  regnum: "string",
  civilId: "string",
};

/**
 * WS101187_CivilServiceEmployeeInfo: Төрийн албан хаагчийн мэдээлэл авах сервис
 *
 * Provider: Төрийн албаны зөвлөл
 */
export async function civilServiceEmployeeInfo(transport: Transport, params: CivilServiceEmployeeInfoParams = {}, options: CallOptions = {}): Promise<XypResult<CivilServiceEmployeeInfoResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      regnum: params.regnum,
      civilId: params.civilId,
    },
    options,
  );
  return decodeResponse<CivilServiceEmployeeInfoResponse>("CivilServiceEmployeeInfoResponse", SCHEMA, data);
}
