/**
 * GENERATED by xyp-generator from spec/services.json. Do not edit.
 *
 * WS101190_LegalEntityNameValidityService (citizen, Улсын бүртгэлийн ерөнхий газар)
 */

import { decodeResponse, type Schema, type XypResult } from "../../schema.js";
import type { CallOptions, Transport } from "../../transport.js";

const OPERATION = "WS101190_LegalEntityNameValidityService";

/** Input of WS101190_LegalEntityNameValidityService. */
export interface LegalEntityNameValidityServiceParams {
  /** Төрөл */
  readonly type?: number;
  /** Регистр */
  readonly personRegnum?: string;
}

/** Жагсаалт */
export interface LegalEntityNameValidityServiceNameList {
  /** Бүртгэлийн дугаар */
  readonly bookNumber: string | null;
  /** Оносон нэр (хүсэлтээр өгсөн нэр) */
  readonly requestedName: string | null;
  /** Үүсгэсэн огноо */
  readonly createdDate: string | null;
  /** Хүчинтэй хугацаа дуусах огноо */
  readonly expiryDate: string | null;
  /** Сүүлд өөрчилсөн огноо */
  readonly modifiedDate: string | null;
  /** Улсын бүртгэлийн дугаар */
  readonly stateRegnum: string | null;
}

/** WS101190_LegalEntityNameValidityService: Хуулийн этгээдийн оноосон нэрийн хүчинтэй хугацаа харууулах сервис */
export interface LegalEntityNameValidityServiceResponse {
  /** Жагсаалт */
  readonly nameList: readonly LegalEntityNameValidityServiceNameList[] | null;
}

const SCHEMA: Schema = { nameList: { list: { object: { bookNumber: "string", requestedName: "string", createdDate: "string", expiryDate: "string", modifiedDate: "string", stateRegnum: "string" } } } };

/**
 * WS101190_LegalEntityNameValidityService: Хуулийн этгээдийн оноосон нэрийн хүчинтэй хугацаа харууулах сервис
 *
 * Provider: Улсын бүртгэлийн ерөнхий газар
 */
export async function legalEntityNameValidityService(transport: Transport, params: LegalEntityNameValidityServiceParams = {}, options: CallOptions = {}): Promise<XypResult<LegalEntityNameValidityServiceResponse>> {
  const data = await transport.call(
    OPERATION,
    {
      type: params.type,
      personRegnum: params.personRegnum,
    },
    options,
  );
  return decodeResponse<LegalEntityNameValidityServiceResponse>("LegalEntityNameValidityServiceResponse", SCHEMA, data);
}
